### ISSUE TITLE
Consider unifying client and server connection objects

### ISSUE THREAD

**Issue by muratg** [aspnet/SignalR#1177] opened 2017-12-04 18:14 UTC
Possibly in ConnectionContext.

(Originally called out from https://github.com/aspnet/SignalR/pull/1165/files#r153701670)

**Comment by davidfowl** [comment] 2018-02-21 07:23
Dupe of https://github.com/aspnet/SignalR/issues/1453

**Closed by davidfowl** 2018-02-21 07:23 UTC
