### ISSUE TITLE
Make SignalR Compatible with Telerik Nativescript

### ISSUE THREAD

**Issue by tuckerjt07** [aspnet/SignalR#1926] opened 2018-04-09 23:33 UTC
Would you be open to a pull request to make SignalR compatible with Nativescript? I have identified two areas where code changes are needed and they are relatively small changes, ~ 10 lines of code. The first issue is a JSON.parse issue inside of the ~~HttpClient~~ HttpConnection. For some reason Nativescript errors out if the object attempting to be parsed is already of type object. The second is that iOS sends the message back inside of the HubConnection class as hex data instead of plain text. There just needs to be a check to see if the message can be parsed to JSON or not and a conversion run if it is not able to be parsed. Those two changes seem to have gotten the two compatible. 

Also, Nativescript does not have access to WebSockets or ServerEvents the way SignalR is using them. Putting in a check to see if they were available before attempting to use them would be helpful as well.

**Comment by davidfowl** [comment] 2018-04-10 00:25
Seems like harmless feature detection like things. The problem is that we don't run tests on this platform so I don't know how to prevent future breaking changes. It might be more manageable for telerik to maintain a nativescript fork of the client.

**Comment by tuckerjt07** [comment] 2018-04-10 01:54
I agree but being able to prevent splintering would be nice as well. I could even write nsXXX extension classes that would take care of it and keep it separate but the protection levels of the ```processIncomingData``` (Line 62, HubConnection.ts) and ```startInternal``` (Line 65, HttpConnection.ts) functions would need to change to make them accessible. 

These are the code changes needed I think

```
let negotiateResponse: INegotiateResponse =
    typeof negotiatePayload.content === 'object'
    ? negotiatePayload.content
    : JSON.parse(<string>negotiatePayload.content);
```

(Line 85, HttpConnection.ts)

```
try {
    JSON.parse(data);
}
catch {
    data = decodeURIComponent(data.replace(/\s+/g, '').replace(/[0-9a-f]{2}/g, '%$&'));
    data = data.replace(/<|>/g, '');
}
```

(Inserted Line 69, HubConnection.ts)

**Comment by davidfowl** [comment] 2018-04-10 04:11
That json parse code looks awful. I’m not willing to add that level of hack this early.

**Comment by davidfowl** [comment] 2018-04-10 05:07
@tuckerjt07 would it also make sense to file an issue on https://github.com/NativeScript/NativeScript?

**Comment by tuckerjt07** [comment] 2018-04-10 14:10
Making it extensible would be great. I'm currently working on cleaning that try catch up. It's just a first pass at getting it to work since I just discovered that yesterday. I'm exploring being able to identify it as a hex string and convert it in an external function rather than use the kludge.

On Nativescript's side I don't know that there is an issue there. Since at this level it is all output from native code and the way all the data is keyed to that.

**Comment by davidfowl** [comment] 2018-04-10 14:17
> On Nativescript's side I don't know that there is an issue there. Since at this level it is all output from native code and the way all the data is keyed to that.

You should pose the query to them and let them decide if it's by design or not. It doesn't make much sense on the surface but maybe there's some details missing.

**Comment by NathanaelA** [comment] 2018-04-10 15:55
Not to spam you.   ;-)   But Just so you guys know; I already have a commercial plugin that works with NativeScript and SignalR.    https://nativescript.tools/product/15

**Comment by davidfowl** [comment] 2018-04-10 17:17
@NathanaelA are you going to update it for SignalR Core?

**Comment by tuckerjt07** [comment] 2018-04-10 18:25
@NathanaelA it's not compatible with SignalR Core. Also the current SignalR works with a few minor changes without payment and is actually OpenSource.

**Comment by tuckerjt07** [comment] 2018-04-11 14:28
@NathanaelA will you please quit using my feature request to promote your paid for solution? Your solution involves paying $100 or using a less than solid license.

@davidfowl I'm trying to get a response from the NativeScript team but it may take a bit to get the conversation back on track since there was some confusion added about the purpose of my inquiry to do it being hijacked.

**Comment by NathanaelA** [comment] 2018-04-11 19:04
@tuckerjt07 - Well, I wouldn't have to keep responding if you would quit disparaging my products.   For that matter; if my products bother you so much -- you might want to see how many of my open source ones you are using in your app, or maybe just stop using NativeScript; since some of my code is in it too.   Seriously dude; the only purpose for my response was to help people find a potential solution that does support better battery and network usage because it supports websockets.   If you don't need or want that; it doesn't bother me in the slightest; but layoff the rude behavior; and this will be my last post having to defend it.  

@davidfowl - As someone who has worked with the NativeScript team for many years and committed many fixes; I can tell you right now the odds of this being fixed in NS are not very likely do to where the issue is at.   Too many other components extend from that place and so a fundamental change (changing hex output) might break a lot of other pieces.   The best bet for decent NS compatibility is to add the fix in this library; and add the ability to polyfill certain functions so that TuckerJ07 can easily then just polyfill that method with his code.

**Comment by tuckerjt07** [comment] 2018-04-11 19:35
@NathanaelA the only rude behavior here is you hijacking multiple discussions to self promote. It's also no one's fault but yourself that your public facing documentation for your product is lacking. That's on you not me. Now please let there be a discussion concerning the actual topic and not something you are trying to promote.

**Closed** 2018-11-08 22:45 UTC
