### ISSUE TITLE
Could not load assembly

### ISSUE THREAD

**Issue by elusiven** [aspnet/SignalR#2129] opened 2018-04-22 13:52 UTC
Hi

Trying to install asp net core signalr client on to my xamarin.forms app. I make a brand new xamarin.forms project, then install the signalr client, lastest preview version and an error pop ups. Does this actually works or is using signalr in a xamarin app impossible yet? I need to know since it's part of my dissertation project.  
```

Severity	Code	Description	Project	File	Line	Suppression State
Error		Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Perhaps it doesn't exist in the Mono for Android profile?
File name: 'System.Memory.dll'
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
   at Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences(DirectoryAssemblyResolver resolver, ICollection`1 assemblies, AssemblyDefinition assembly, Boolean topLevel)
   at Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences(DirectoryAssemblyResolver resolver, ICollection`1 assemblies, AssemblyDefinition assembly, Boolean topLevel)
   at Xamarin.Android.Tasks.ResolveAssemblies.Execute(DirectoryAssemblyResolver resolver)	App1.Android			

```

**Comment by davidfowl** [comment] 2018-04-22 14:04
Closing as dupe of https://github.com/aspnet/SignalR/issues/1886. We'll get an update from the Xamarin team to see if there's a version of Visual Studio that supports this.

**Closed by davidfowl** 2018-04-22 14:04 UTC

**Comment by patsadow2** [comment] 2018-05-06 06:13
VS 15.7 the same story.

**Comment by davidfowl** [comment] 2018-05-06 06:35
@patsadow2 Can you put specific details in the linked issue so we can get somebody from the Xamarin team to look at it?
