### ISSUE TITLE
Case issues

### ISSUE THREAD

**Issue by rhegner** [aspnet/SignalR#73] opened 2016-12-14 15:11 UTC
Let's say we have a model like this on the server side:

    class Person
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
    }

A Asp.Net Core Controller serializes this to a JSON with 'firstName' and 'lastName'. So all my client-side classes use this convention.

I realized that SignalR serializes this to 'FirstName' and 'LastName'. This means I can't re-use my client-side classes.

- Is there an easy way to configure this behaviour in SignalR?
- If not, what's the recommended workaround?
- It would be nice if the default behaviour of SignalR was the same as for Controllers.

**Comment by rhegner** [comment] 2016-12-14 15:23
The workaround described [here](https://radu-matei.github.io/blog/aspnet-core-mvc-signalr/) does not seem to work.

**Comment by rhegner** [comment] 2016-12-14 16:37
I found a very ugly workaround. In my hub before returning any object I call the following function on it:

	private object ToCamelCaseObject(object obj)
	{
		var json = JsonConvert.SerializeObject(obj, Formatting.None, SerializerSettings);
		return JsonConvert.DeserializeObject(json);
	}
	private readonly static JsonSerializerSettings SerializerSettings = new JsonSerializerSettings() { ContractResolver = new Serialization.CamelCasePropertyNamesContractResolver() };

PS (not related to this issue but FYI): issue number 71 seems to be one of the biggest show-stoppers at the moment. Would be nice if arbitrary large objects can be transferred soon!

**Comment by radu-matei** [comment] 2016-12-14 17:06
@rhegner What version aof SignalR are you using? The article you pointed to was based on the old SignalR repo you can find here - https://github.com/signalr/signalr

Still, could you provide something I can take a look at?

Thanks!

**Comment by moozzyk** [comment] 2016-12-14 17:22
@rhegner - the problem is that at the moment we just new up JSonSerializer/JSonTextWriter without allowing passing any options (or maybe resolving these from the DI). We are discussing the best way to resolve #71.
Everything here is pretty much work in progress.

**Comment by cruikshj** [comment] 2017-03-29 18:20
I worked around this issue by using my own IInvocationAdapter.  It is simply a copy of JsonNetInvocationAdapter (from the repo) but it uses constructor injection to resolve the JsonSerializer rather than newing one up.

```
public class JsonInvocationAdapter : IInvocationAdapter
{
        public JsonInvocationAdapter(JsonSerializer serializer)
        {
            _serializer = serializer ?? throw new ArgumentNullException(nameof(serializer));
        }
```

then registrating as follows..

```
var jsonSerializerSettings = new JsonSerializerSettings();
jsonSerializerSettings.ContractResolver = new CamelCasePropertyNamesContractResolver();
jsonSerializerSettings.Formatting = Formatting.Indented;
jsonSerializerSettings.Converters.Add(new StringEnumConverter());
services.AddSingleton(JsonSerializer.Create(jsonSerializerSettings));

services.AddSingleton<JsonInvocationAdapter>();
services.AddSignalR(options =>
{
     options.RegisterInvocationAdapter<JsonInvocationAdapter>("json");
});

**Comment by davidfowl** [comment] 2017-06-28 06:31
Tracked by https://github.com/aspnet/SignalR/issues/261

**Closed by davidfowl** 2017-06-28 06:31 UTC
Labels: needs design
