### ISSUE TITLE
The method in hubs can‘t invoke when previous method not finish。。

### ISSUE THREAD

**Issue by polei** [aspnet/SignalR#3229] opened 2018-10-30 12:44 UTC
I have to methos in hubs。

<pre>
        public async Task&lt;Result&gt; Delay (int seconds)
        {
            await Task.Delay(seconds * 1000);
            return new Result {
                success = true,
                msg = seconds + "s"
            };
        }

       public Result Test(string a)
        {
            return new Result {
                success = true,
                msg = a + DateTime.Now
            };
        }
</pre>

When the  **Delay** method is running, the **Test** can't invoke.

**Comment by anurse** [comment] 2018-10-30 15:08
Yes, a connection can only execute one Hub method at a time. This is to ensure the client can't flood the server with requests and consume large amounts of memory. We are considering removing this restriction in the future. https://github.com/aspnet/SignalR/issues/3133 is tracking that work so I'm going to close this as a duplicate.

Duplicate of https://github.com/aspnet/SignalR/issues/3133

**Closed by anurse** 2018-10-30 15:08 UTC
