### ISSUE TITLE
Get current user in "OnDisconnectedAsync"

### ISSUE THREAD

**Issue by mortenbirkelund** [aspnet/SignalR#1345] opened 2018-01-25 13:23 UTC
Anybody who can clarify how i get the current user in the  `OnDisconnectedAsync` method? 

Here is my method
```
        public override async Task OnDisconnectedAsync(Exception exception)
        {
                var user = await _userManager.FindByEmailAsync(Context.User.Identity.Name);

                _chatConnections.Remove(user.Id, Context.ConnectionId);

                await Clients.All.InvokeAsync("UsersLeft", new { userId = user.Id, name = user.Name, photo = user.ProfilePicture });

                await base.OnDisconnectedAsync(exception);
        }
```

But it doesnt work, as the first line, throws an `OperationCanceledException`, and the execution of the rest of the method is terminated.

**Comment by davidfowl** [comment] 2018-01-25 15:17
The code looks fine. Does it consistently throw an OperationCanceledException?

**Comment by mortenbirkelund** [comment] 2018-01-25 15:47
I have just tried to enter and leave the chathub 3 times. 

First time
```
2018-01-25 16:38:03.090 +01:00 [Error] Error when invoking OnDisconnectedAsync on hub.
System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Microsoft.AspNetCore.Identity.EntityFrameworkCore.UserStore`9.FindByEmailAsync(String normalizedEmail, CancellationToken cancellationToken)
   at XXXXX.Hubs.ChatHub.<OnDisconnectedAsync>d__13.MoveNext() in C:\Users\XXXXX\OneDrive\Dokumenter\Visual Studio 2017\Projects\XXXXXX\XXXXXXX\Hubs\ChatHub.cs:line 172
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.HubEndPoint`1.<HubOnDisconnectedAsync>d__15.MoveNext()
```

Second time
```
2018-01-25 16:38:52.062 +01:00 [Error] Error when invoking OnDisconnectedAsync on hub.
System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Microsoft.AspNetCore.Identity.EntityFrameworkCore.UserStore`9.FindByEmailAsync(String normalizedEmail, CancellationToken cancellationToken)
   at XXXXX.Hubs.ChatHub.<OnDisconnectedAsync>d__13.MoveNext() in C:\Users\XXXXX\OneDrive\Dokumenter\Visual Studio 2017\Projects\XXXXXX\XXXXXXX\Hubs\ChatHub.cs:line 172
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.HubEndPoint`1.<HubOnDisconnectedAsync>d__15.MoveNext()
2018-01-25 16:38:52.081 +01:00 [Error] 01/25/2018 16:38:52: ConnectionId "a6eb8e55-989f-4187-a2e6-845065f0b8a3": Failed disposing connection.
System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Microsoft.AspNetCore.Identity.EntityFrameworkCore.UserStore`9.FindByEmailAsync(String normalizedEmail, CancellationToken cancellationToken)
   at XXXXX.Hubs.ChatHub.<OnDisconnectedAsync>d__13.MoveNext() in C:\Users\XXXXX\OneDrive\Dokumenter\Visual Studio 2017\Projects\XXXXXX\XXXXXXX\Hubs\ChatHub.cs:line 172
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.HubEndPoint`1.<HubOnDisconnectedAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.HubEndPoint`1.<RunHubAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.HubEndPoint`1.<OnConnectedAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.SignalR.HubEndPoint`1.<OnConnectedAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Sockets.HttpConnectionDispatcher.<ExecuteApplication>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Sockets.DefaultConnectionContext.<WaitOnTasks>d__56.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Sockets.DefaultConnectionContext.<DisposeAsync>d__55.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Sockets.ConnectionManager.<DisposeAndRemoveAsync>d__14.MoveNext()
```

third time
```
2018-01-25 16:39:30.231 +01:00 [Error] Error when invoking OnDisconnectedAsync on hub.
System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Microsoft.AspNetCore.Identity.EntityFrameworkCore.UserStore`9.FindByEmailAsync(String normalizedEmail, CancellationToken cancellationToken)
   at XXXXX.Hubs.ChatHub.<OnDisconnectedAsync>d__13.MoveNext() in C:\Users\XXXXX\OneDrive\Dokumenter\Visual Studio 2017\Projects\XXXXXX\XXXXXXX\Hubs\ChatHub.cs:line 172
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.HubEndPoint`1.<HubOnDisconnectedAsync>d__15.MoveNext()
```


When viewing the log for a whole day, there are quite alot of these kind of errors, but it it not totally consistent, what error is thrown each time. 

Sometimes this one is also thrown
```

2018-01-25 16:28:27.896 +01:00 [Error] An exception occurred in the database while iterating the results of a query for context type '"XXXXX.Data.ApplicationDbContext"'."
""System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.<EnterCriticalSectionAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.<MoveNext>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<ExecuteSingletonAsyncQuery>d__23`1.MoveNext()"
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.<EnterCriticalSectionAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.<MoveNext>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<ExecuteSingletonAsyncQuery>d__23`1.MoveNext()
```

**Comment by davidfowl** [comment] 2018-01-25 15:50
@HaoK @ajcvickers Why would this throw an exception? Does it have anything to do with the DbContext lifetime?

**Comment by mortenbirkelund** [comment] 2018-01-25 16:05
Hmm. Not sure what happened, but I just happened to notice that on the server, the  "Users Left" is actually invoked, but the errors persists...

**Comment by davidfowl** [comment] 2018-01-25 16:28
I know what the problem is. Identity uses the request aborted token and passes that to all of the database calls. Since the user is disconnected, it causes the exception to be thrown. We need to fix this @HaoK.

**Comment by HaoK** [comment] 2018-01-25 18:33
So a workaround is just to replacing the user manager type.  Instead of the normal AspNetUserManager (which attaches the request aborted, and is the only thing it does :) - https://github.com/aspnet/Identity/blob/dev/src/Identity/AspNetUserManager.cs

Add the base manager before you call AddIdentity:
`services.AddScoped<UserManager<TUser>>();`

**Comment by HaoK** [comment] 2018-01-25 18:38
In terms of longer term behavior @davidfowl should we just add an option to opt out of this hookup?

AddIdentity(o => o.DisableCancellationToken = true) which won't assign the property / always use CancellationToken.None

**Comment by davidfowl** [comment] 2018-01-25 22:06
I think adding an overload that takes a cancellation token.

**Comment by HaoK** [comment] 2018-01-25 22:24
Do you mean add an overload to all user manager methods to take an optional cancellation token?

**Comment by davidfowl** [comment] 2018-01-26 02:09
@HaoK yep

**Comment by mortenbirkelund** [comment] 2018-02-02 19:21
@HaoK I am not quite sure on how to implement the workaround you suggest. Could you elaborate?

**Comment by HaoK** [comment] 2018-02-02 19:24
In startup, you today have `services.AddIdentity<>` I am assuming...

So after that add:
`services.AddScoped<UserManager<TUser>>();`, that should override the AspUserManager that is hookingup the cancellation token with the base class that doesn't, so basically that will disable cancellationtokens for identity.

**Comment by mortenbirkelund** [comment] 2018-02-02 19:50
Oh thanks. I misunderstood, and overcomplicated it then.

**Comment by davidfowl** [comment] 2018-02-02 19:52
Closed in favor of https://github.com/aspnet/Identity/issues/1596

**Closed by davidfowl** 2018-02-02 19:52 UTC
