### ISSUE TITLE
System.TypeLoadException: Could not resolve the signature of a virtual method on iOS

### ISSUE THREAD

**Issue by titonton** [aspnet/SignalR#2518] opened 2018-06-20 21:29 UTC
I am still running into this issue on iOS. Oddly enough it works perfectly on Android.

Xamarin Forms Version: 3.0.0.561731

SignalRCore version: 1.0.1

**Comment by titonton** [comment] 2018-06-20 21:37
This is the full Exception message

`2018-06-20 17:36:09.907 BizPass.iOS[77243:12163253] warning: Could not load signature of Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol:TryParseMessage due to: Could not resolve type with token 01000027 (from typeref, class/assembly System.Buffers.ReadOnlySequence`1, System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51) assembly:System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 type:System.Buffers.ReadOnlySequence`1 member:(null) signature:<none>`

**Comment by titonton** [comment] 2018-06-20 21:38
I had also tried adding the System.Memory package, but of course that didn't work either

**Comment by anurse** [comment] 2018-06-20 22:13
What version of Visual Studio are you using and what are your Xamarin.Android/Xamarin.iOS versions? You have to have Xamarin.iOS 11.14.0.4, which is in Visual Studio 15.8 Preview 3 (and VS for Mac 7.6 Preview 3). I don't believe those have been released yet.

Those updated versions of Xamarin should be released in the coming weeks. If the issue still occurs when running on those versions, then we can reactivate this bug and see what the issue is.

**Closed by anurse** 2018-06-20 22:13 UTC

**Comment by titonton** [comment] 2018-06-21 13:28
Okay sounds good. Thanks for your help man. I'll wait for those versions to come out and try again.

**Comment by shshshdy** [comment] 2018-07-31 14:56
Xamarin.iOS 11.14.0.4, which is in Visual Studio 15.8 Preview 3 (and VS for Mac 7.6 Preview 3)
debug throw
2018-07-31 22:41:30.108 Client.App.iOS[2253:896715] Unhandled managed exception:
Could not resolve the signature of a virtual method (System.TypeLoadException)
  at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) [0x0001b] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.14.0.11/src/Xamarin.iOS/mcs/class/corlib/System.Reflection/MonoMethod.cs:671 
  at System.Reflection.MonoCMethod.DoInvoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0007a] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.14.0.11/src/Xamarin.iOS/mcs/class/corlib/System.Reflection/MonoMethod.cs:652 
  at System.Reflection.MonoCMethod.Invoke (System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.14.0.11/src/Xamarin.iOS/mcs/class/corlib/System.Reflection/MonoMethod.cs:680 
  at System.Reflection.ConstructorInfo.Invoke (System.Object[] parameters) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.14.0.11/src/Xamarin.iOS/mcs/class/corlib/System.Reflection/ConstructorInfo.cs:62 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor (Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite constructorCallSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope scope) [0x00035] in <ef466db513bd4c67869506814ed622c5>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[TArgument,TResult].VisitCallSite (Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceCallSite callSite, TArgument argument) [0x00056] in <ef466db513bd4c67869506814ed622c5>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped (Microsoft.Extensions.DependencyInjection.ServiceLookup.ScopedCallSite scopedCallSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope scope) [0x0002d] in <ef466db513bd4c67869506814ed622c5>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton (Microsoft.Extensions.DependencyInjection.ServiceLookup.SingletonCallSite singletonCallSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope scope) [0x0000d] in <ef466db513bd4c67869506814ed622c5>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[TArgument,TResult].VisitCallSite (Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceCallSite callSite, TArgument argument) [0x00072] in <ef466db513bd4c67869506814ed622c5>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor (Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite constructorCallSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope scope) [0x0001b] in <ef466db513bd4c67869506814ed622c5>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[TArgument,TResult].VisitCallSite (Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceCallSite callSite, TArgument argument) [0x00056] in <ef466db513bd4c67869506814ed622c5>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped (Microsoft.Extensions.DependencyInjection.ServiceLookup.ScopedCallSite scopedCallSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope scope) [0x0002d] in <ef466db513bd4c67869506814ed622c5>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton (Microsoft.Extensions.DependencyInjection.ServiceLookup.SingletonCallSite singletonCallSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope scope) [0x0000d] in <ef466db513bd4c67869506814ed622c5>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[TArgument,TResult].VisitCallSite (Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceCallSite callSite, TArgument argument) [0x00072] in <ef466db513bd4c67869506814ed622c5>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve (Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceCallSite callSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope scope) [0x00000] in <ef466db513bd4c67869506814ed622c5>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine+<>c__DisplayClass1_0.<RealizeService>b__0 (Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope scope) [0x0003e] in <ef466db513bd4c67869506814ed622c5>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService (System.Type serviceType, Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope serviceProviderEngineScope) [0x00032] in <ef466db513bd4c67869506814ed622c5>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService (System.Type serviceType) [0x00008] in <ef466db513bd4c67869506814ed622c5>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService (System.Type serviceType) [0x00000] in <ef466db513bd4c67869506814ed622c5>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T] (System.IServiceProvider provider) [0x0000e] in <4b47b422bc4c4615bbdebe1df9b21b0d>:0 
  at Microsoft.AspNetCore.SignalR.Client.HubConnectionBuilder.Build () [0x00041] in <2fa773d5c6ab4e6a98db7380798c1d64>:0 
  at Client.App.MainPage..ctor () [0x00032] in /Users/ssd/Desktop/SignalRDemo/Client.App/Client.App/MainPage.xaml.cs:24 
  at Client.App.App..ctor () [0x0000f] in /Users/ssd/Desktop/SignalRDemo/Client.App/Client.App/App.xaml.cs:14 
  at Client.App.iOS.AppDelegate.FinishedLaunching (UIKit.UIApplication app, Foundation.NSDictionary options) [0x00007] in /Users/ssd/Desktop/SignalRDemo/Client.App/Client.App.iOS/AppDelegate.cs:26 
  at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.14.0.11/src/Xamarin.iOS/UIKit/UIApplication.cs:79 
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0002c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.14.0.11/src/Xamarin.iOS/UIKit/UIApplication.cs:63 
  at Client.App.iOS.Application.Main (System.String[] args) [0x00001] in /Users/ssd/Desktop/SignalRDemo/Client.App/Client.App.iOS/Main.cs:17

**Comment by anurse** [comment] 2018-07-31 16:14
This issue is closed. If you're encountering an issue please file a new one. Remember to include the exact versions of SignalR packages and your Xamarin version in the bug, as well as the full stack trace.
