### ISSUE TITLE
.WithHeader is removed from RC1 using HubConnectionBuilder

### ISSUE THREAD

**Issue by mintyfusion** [aspnet/SignalR#2269] opened 2018-05-14 21:51 UTC
Previously we were using the following code to pass authentication token to the HubConnectionBuilder

`                hubConnection = new HubConnectionBuilder()
                .WithUrl(Url.SignalR.Value())
                .WithHeader("Authorization", string.Format("bearer {0}", token))
                .Build();`

Now, with RC1 release, that option has disappeared and we are using the below way to pass the token:

`                hubConnection = new HubConnectionBuilder()
                    .WithUrl(Url.SignalR.Value(), options =>
                    {
                        options.Headers = new Dictionary<string, string> { { "Authorization", string.Format("bearer {0}", token) } };
                    }).Build();`

The above causes below exception on StartAsync()

`System.InvalidOperationException: Manager: HubConnectionManager: StartAsync() - System.NotImplementedException: The method or operation is not implemented.
  at System.Net.Http.HttpClientHandler.get_ClientCertificates () [0x00000] in <996a681f30a44cd685a4da54e11956e2>:0 
  at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.CreateHttpClient () [0x0005c] in <dd40c651eaf14486a531dbb173fa57e1>:0 
  at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection..ctor (Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionOptions httpConnectionOptions, Microsoft.Extensions.Logging.ILoggerFactory loggerFactory) [0x00080] in <dd40c651eaf14486a531dbb173fa57e1>:0 
  at Microsoft.AspNetCore.SignalR.Client.HttpConnectionFactory+<ConnectAsync>d__3.MoveNext () [0x00011] in <2d5fd7ae71414f799c1b2fb768dded77>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at Microsoft.AspNetCore.SignalR.Client.HubConnection+<StartAsyncCore>d__31.MoveNext () [0x0012d] in <68ab53cfc0fc419d97809539d3efaad3>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Threading.Tasks.ForceAsyncAwaiter.GetResult () [0x0000c] in <68ab53cfc0fc419d97809539d3efaad3>:0 
  at Microsoft.AspNetCore.SignalR.Client.HubConnection+<StartAsync>d__24.MoveNext () [0x00076] in <68ab53cfc0fc419d97809539d3efaad3>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 `

**Comment by JamesNK** [comment] 2018-05-14 21:55
Hi

What environment are you running the SignalR client from?

**Comment by mintyfusion** [comment] 2018-05-14 21:56
This is Xamarin.Android running Visual Studio 2017 version 15.7.1

**Comment by JamesNK** [comment] 2018-05-14 22:05
Ok. It looks like this issue is the same as this one - https://github.com/aspnet/SignalR/issues/2232

Right now you are unable to use the SignalR C# client from Mono.

**Comment by mintyfusion** [comment] 2018-05-14 22:50
Is there a workaround? Also, what was the reasoning behind removing .WithHeader?

**Comment by JamesNK** [comment] 2018-05-14 22:56
You will need to stick with preview 2 for now.

Setting headers is now done in the configuration action, like you are already doing. Having access to a Dictionary of headers makes it easier to add and copy multiple values compared to `WithHeader`. The error is unrelated to this change.

**Comment by mintyfusion** [comment] 2018-05-14 22:58
Thank You.

**Comment by JamesNK** [comment] 2018-05-15 00:45
Closing as a dupe of https://github.com/aspnet/SignalR/issues/2232

**Closed by JamesNK** 2018-05-15 00:45 UTC
