### ISSUE TITLE
Typings File

### ISSUE THREAD

**Issue by RandyBuchholz** [aspnet/SignalR#1109] opened 2017-11-13 13:02 UTC
Could the team provide an alpha Typescript typings file for the min.js (at least the main one) in the repo during the dev process? We will need one in the end, and it would be good to start testing against that now.

**Comment by moozzyk** [comment] 2017-11-13 18:03
Looks like a duplicate of #951

**Closed by moozzyk** 2017-11-13 18:03 UTC

**Comment by RandyBuchholz** [comment] 2017-11-14 12:48
@moozzyk - sort of. What I'm thinking of is having something like an "official preview" of "official" typings, easy to find in the repo. Maybe in a folder at the root.
