### ISSUE TITLE
Socket Got Closed 

### ISSUE THREAD

**Issue by shahabganji** [aspnet/SignalR#64] opened 2016-12-07 11:30 UTC
After web socket connection started and Socket is open, I try to send a message to chat Hub but the connection get closed automatically and this is the full error message : 

```
info: Microsoft.AspNetCore.Sockets.WebSockets[0]
      Socket closed.
Microsoft.AspNetCore.Sockets.WebSockets:Information: Socket closed.
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[0]
      An unhandled exception has occurred while executing the request
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.SignalR.JsonNetInvocationAdapter.<>c__DisplayClass2_0.<ReadInvocationDescriptorAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.HubEndPoint`2.<DispatchMessagesAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.HubEndPoint`2.<OnConnectedAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.SignalR.HubEndPoint`2.<OnConnectedAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Sockets.HttpConnectionDispatcher.<DoPersistentConnection>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Sockets.HttpConnectionDispatcher.<ExecuteAsync>d__4`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware:Error: An unhandled exception has occurred while executing the request

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.SignalR.JsonNetInvocationAdapter.<>c__DisplayClass2_0.<ReadInvocationDescriptorAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.HubEndPoint`2.<DispatchMessagesAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.HubEndPoint`2.<OnConnectedAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.SignalR.HubEndPoint`2.<OnConnectedAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Sockets.HttpConnectionDispatcher.<DoPersistentConnection>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Sockets.HttpConnectionDispatcher.<ExecuteAsync>d__4`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
warn: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[0]
      The response has already started, the error page middleware will not be executed.
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware:Warning: The response has already started, the error page middleware will not be executed.
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HL0UF3B8F88B": An unhandled exception was thrown by the application.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.SignalR.JsonNetInvocationAdapter.<>c__DisplayClass2_0.<ReadInvocationDescriptorAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.HubEndPoint`2.<DispatchMessagesAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.HubEndPoint`2.<OnConnectedAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.SignalR.HubEndPoint`2.<OnConnectedAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Sockets.HttpConnectionDispatcher.<DoPersistentConnection>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Sockets.HttpConnectionDispatcher.<ExecuteAsync>d__4`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
Microsoft.AspNetCore.Server.Kestrel:Error: Connection id "0HL0UF3B8F88B": An unhandled exception was thrown by the application.

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.SignalR.JsonNetInvocationAdapter.<>c__DisplayClass2_0.<ReadInvocationDescriptorAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.HubEndPoint`2.<DispatchMessagesAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.HubEndPoint`2.<OnConnectedAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.SignalR.HubEndPoint`2.<OnConnectedAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Sockets.HttpConnectionDispatcher.<DoPersistentConnection>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Sockets.HttpConnectionDispatcher.<ExecuteAsync>d__4`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 7818.7469ms 101 
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request finished in 7818.7469ms 101 
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5000/  
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request starting HTTP/1.1 GET http://localhost:5000/  
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Executing action method signalR_test.Controllers.HomeController.Index (signalR_test) with arguments ((null)) - ModelState is Valid
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker:Information: Executing action method signalR_test.Controllers.HomeController.Index (signalR_test) with arguments ((null)) - ModelState is Valid
info: Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ViewResultExecutor[1]
 Executing ViewResult, running view at path /Views/Home/Index.cshtml.
Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ViewResultExecutor:Information: Executing ViewResult, running view at path /Views/Home/Index.cshtml.
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action signalR_test.Controllers.HomeController.Index (signalR_test) in 11.293ms
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker:Information: Executed action signalR_test.Controllers.HomeController.Index (signalR_test) in 11.293ms
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 17.8879ms 200 text/html; charset=utf-8
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request finished in 17.8879ms 200 text/html;
```

it also said that it cannot open or find these files : 
```System.Binary.dll```
```System.Text.Formatting.dll``` 
```System.Text.Primitives.dll``` 
```System.IO.Pipelines.Text.Primitives.dll```

and this is the outpu of ```dotnet restore``` command

```
C:\Users\...\Desktop\SignalR-dev\SignalR-dev\samples\ChatSample>dotnet resto
re
log  : Restoring packages for C:\Users\...\Desktop\SignalR-dev\SignalR-dev\s
amples\ChatSample\project.json...
log  : Restoring packages for tool 'BundlerMinifier.Core' in C:\Users\...\De
sktop\SignalR-dev\SignalR-dev\samples\ChatSample\project.json...
log  : Restoring packages for tool 'Microsoft.AspNetCore.Razor.Tools' in C:\User
s\...\Desktop\SignalR-dev\SignalR-dev\samples\ChatSample\project.json...
log  : Restoring packages for tool 'Microsoft.AspNetCore.Server.IISIntegration.T
ools' in C:\Users\...\Desktop\SignalR-dev\SignalR-dev\samples\ChatSample\pro
ject.json...
log  : Failed to download package from 'https://api.nuget.org/v3-flatcontainer/s
ystem.diagnostics.process/4.3.0-preview1-24530-04/system.diagnostics.process.4.3
.0-preview1-24530-04.nupkg'.
log  : An error occurred while sending the request.
log  :   The server returned an invalid or unrecognized response
log  : Failed to download package from 'https://api.nuget.org/v3-flatcontainer/s
ystem.diagnostics.process/4.3.0-preview1-24530-04/system.diagnostics.process.4.3
.0-preview1-24530-04.nupkg'.
log  : An error occurred while sending the request.
log  :   The server returned an invalid or unrecognized response
log  : Retrying 'FindPackagesByIdAsyncCore' for source 'https://www.postsharp.ne
t/nuget/packages/FindPackagesById()?id='System.Reflection.Emit.ILGeneration''.
log  : An error occurred while sending the request.
log  :   The server returned an invalid or unrecognized response
log  : Retrying 'FindPackagesByIdAsync' for source 'https://dotnetmyget.blob.cor
e.windows.net/artifacts/aspnetcore-ci-dev/nuget/v3/flatcontainer/system.security
.claims/index.json'.
log  : An error occurred while sending the request.
log  :   The server returned an invalid or unrecognized response
log  : Retrying 'FindPackagesByIdAsyncCore' for source 'https://www.postsharp.ne
t/nuget/packages/FindPackagesById()?id='System.Security.Claims''.
log  : An error occurred while sending the request.
log  :   The server returned an invalid or unrecognized response
log  : Retrying 'FindPackagesByIdAsyncCore' for source 'https://www.postsharp.ne
t/nuget/packages/FindPackagesById()?id='System.Security.Principal''.
log  : An error occurred while sending the request.
log  :   The server returned an invalid or unrecognized response
log  : Retrying 'FindPackagesByIdAsync' for source 'https://dotnetmyget.blob.cor
e.windows.net/artifacts/aspnetcore-ci-dev/nuget/v3/flatcontainer/system.security
.principal/index.json'.
log  : An error occurred while sending the request.
log  :   The server returned an invalid or unrecognized response
log  : Retrying 'FindPackagesByIdAsync' for source 'https://dotnetmyget.blob.cor
e.windows.net/artifacts/aspnetcore-ci-dev/nuget/v3/flatcontainer/system.security
.claims/index.json'.
log  : An error occurred while sending the request.
log  :   The server returned an invalid or unrecognized response
log  : Retrying 'FindPackagesByIdAsync' for source 'https://dotnetmyget.blob.cor
e.windows.net/artifacts/aspnetcore-ci-dev/nuget/v3/flatcontainer/system.security
.principal/index.json'.
log  : An error occurred while sending the request.
log  :   The server returned an invalid or unrecognized response
error: Failed to retrieve information from remote source 'https://dotnetmyget.bl
ob.core.windows.net/artifacts/aspnetcore-ci-dev/nuget/v3/flatcontainer/system.se
curity.claims/index.json'.
error: An error occurred while sending the request.
error:   The server returned an invalid or unrecognized response
error: Failed to retrieve information from remote source 'https://dotnetmyget.bl
ob.core.windows.net/artifacts/aspnetcore-ci-dev/nuget/v3/flatcontainer/system.se
curity.claims/index.json'.
error:   An error occurred while sending the request.
error:   The server returned an invalid or unrecognized response
error: Failed to retrieve information from remote source 'https://dotnetmyget.bl
ob.core.windows.net/artifacts/aspnetcore-ci-dev/nuget/v3/flatcontainer/system.se
curity.principal/index.json'.
error: An error occurred while sending the request.
error:   The server returned an invalid or unrecognized response
```

**Comment by davidfowl** [comment] 2016-12-07 15:56
@shahabganji Try not to file 2 issues in a single issue.

> After web socket connection started and Socket is open, I try to send a message to chat Hub but the connection get closed automatically and this is the full error message :

There are still big issues with this version of SignalR (it's early). Also this looks like a dupe of https://github.com/aspnet/SignalR/issues/62

**Comment by davidfowl** [comment] 2016-12-07 15:56
> it also said that it cannot open or find these files :

I'm not sure what you're running into. Maybe clear your nuget cache and try again.

**Comment by shahabganji** [comment] 2016-12-07 16:46
@davidfowl actually both of them are for the same issue, because it cannot load those assemblies it closes the socket.

**Comment by shahabganji** [comment] 2016-12-07 16:46
@davidfowl I will test your suggestion too .

**Comment by moozzyk** [comment] 2016-12-07 17:43
I think it might be this https://github.com/aspnet/SignalR/issues/62. I have not investigated but I think the issue might be that you are calling a hub method that does not exist on the server. If the code worked before it is related to the [change](https://github.com/aspnet/SignalR/commit/2b918b8fe29b07418e5bba34e0fc9f4939e96a5c) I made yesterday where the hub method name is no longer a fully qualified method name. So when you invoke a hub method from the client you now need to pass just the name of the method.

**Comment by shahabganji** [comment] 2016-12-10 08:47
@moozzyk Yeah, that was the problem comrade. It works now.

**Closed** 2016-12-10 09:00 UTC
