### ISSUE TITLE
Add ConnectionState to HubConnection

### ISSUE THREAD

**Issue by chrisahardie** [aspnet/SignalR#2161] opened 2018-04-29 18:07 UTC
There used to be a `ConnectionState` property on the `HubConnection` with the following values:

- Connecting
- Connected
- Reconnecting
- Disconnected

I have a use case for which it would be convenient. I am creating a SignalR client factory in Service Fabric along the lines of [this one](https://github.com/Azure-Samples/service-fabric-dotnet-data-streaming-websockets/blob/master/src/DataStreaming/PublicGateway/Comms/WsCommunicationClientFactory.cs#L17)

The factory identifies if the client is in a valid state, and in the WebSocket example [I'm riffing from](https://github.com/Azure-Samples/service-fabric-dotnet-data-streaming-websockets/blob/ca557c30a081da656ceafee1d68b5e5139050d2a/src/DataStreaming/PublicGateway/Comms/WsCommunicationClient.cs#L76), validation involves checking the status of the `ClientWebSocket` connection status:

```
        internal bool ValidateClient()
        {
            if (this.clientWebSocket.State != WebSocketState.Open && this.clientWebSocket.State != WebSocketState.Connecting)
            {
                this.clientWebSocket.Dispose();
                this.clientWebSocket = null;
                return false;
            }
```

It would be convenient if the the connection status of the `HubConnection` was exposed publicly so I wouldn't have to track it myself.

**Comment by davidfowl** [comment] 2018-04-29 18:08
Dupe of https://github.com/aspnet/SignalR/issues/2127

**Closed by davidfowl** 2018-04-29 18:08 UTC
