### ISSUE TITLE
Address package downgrade warnings

### ISSUE THREAD

**Issue by mikeharder** [aspnet/SignalR#428] opened 2017-04-29 05:47 UTC
Latest build of `UniverseCoherence (2.0.0-preview1)` contained package downgrade warnings in this repo:

http://aspnetci/viewLog.html?buildId=211993&buildTypeId=UniverseCoherence&tab=buildLog

```
Detected package downgrade: System.Net.NameResolution from 4.3.0 to 4.0.0  [C:\b\w\590aeb6bc9b87cb8\.r\SignalR\.build\KoreBuild.proj]
 SocketsSample (>= 1.0.0) -> Microsoft.AspNetCore.SignalR.Redis (>= 1.0.0-preview1-24766) -> StackExchange.Redis.StrongName (>= 1.1.605) -> System.Net.Sockets (>= 4.1.0) -> runtime.win.System.Net.Sockets (>= 4.3.0) -> System.Net.NameResolution (>= 4.3.0)  [C:\b\w\590aeb6bc9b87cb8\.r\SignalR\.build\KoreBuild.proj]
 SocketsSample (>= 1.0.0) -> Microsoft.AspNetCore.SignalR.Redis (>= 1.0.0-preview1-24766) -> StackExchange.Redis.StrongName (>= 1.1.605) -> System.Net.NameResolution (>= 4.0.0) [C:\b\w\590aeb6bc9b87cb8\.r\SignalR\.build\KoreBuild.proj]
Detected package downgrade: System.Net.Primitives from 4.3.0 to 4.0.11  [C:\b\w\590aeb6bc9b87cb8\.r\SignalR\.build\KoreBuild.proj]
 SocketsSample (>= 1.0.0) -> Microsoft.AspNetCore.SignalR.Redis (>= 1.0.0-preview1-24766) -> StackExchange.Redis.StrongName (>= 1.1.605) -> System.Net.Sockets (>= 4.1.0) -> runtime.win.System.Net.Sockets (>= 4.3.0) -> System.Net.Primitives (>= 4.3.0)  [C:\b\w\590aeb6bc9b87cb8\.r\SignalR\.build\KoreBuild.proj]
 SocketsSample (>= 1.0.0) -> Microsoft.AspNetCore.SignalR.Redis (>= 1.0.0-preview1-24766) -> StackExchange.Redis.StrongName (>= 1.1.605) -> System.Net.Sockets (>= 4.1.0) -> System.Net.Primitives (>= 4.0.11) [C:\b\w\590aeb6bc9b87cb8\.r\SignalR\.build\KoreBuild.proj]
Detected package downgrade: System.Net.NameResolution from 4.3.0 to 4.0.0  [C:\b\w\590aeb6bc9b87cb8\.r\SignalR\.build\KoreBuild.proj]
 SocketsSample (>= 1.0.0) -> Microsoft.AspNetCore.SignalR.Redis (>= 1.0.0-preview1-24766) -> StackExchange.Redis.StrongName (>= 1.1.605) -> System.Net.Sockets (>= 4.1.0) -> runtime.win.System.Net.Sockets (>= 4.3.0) -> System.Net.NameResolution (>= 4.3.0)  [C:\b\w\590aeb6bc9b87cb8\.r\SignalR\.build\KoreBuild.proj]
 SocketsSample (>= 1.0.0) -> Microsoft.AspNetCore.SignalR.Redis (>= 1.0.0-preview1-24766) -> StackExchange.Redis.StrongName (>= 1.1.605) -> System.Net.NameResolution (>= 4.0.0) [C:\b\w\590aeb6bc9b87cb8\.r\SignalR\.build\KoreBuild.proj]
Detected package downgrade: System.Net.Primitives from 4.3.0 to 4.0.11  [C:\b\w\590aeb6bc9b87cb8\.r\SignalR\.build\KoreBuild.proj]
 SocketsSample (>= 1.0.0) -> Microsoft.AspNetCore.SignalR.Redis (>= 1.0.0-preview1-24766) -> StackExchange.Redis.StrongName (>= 1.1.605) -> System.Net.Sockets (>= 4.1.0) -> runtime.win.System.Net.Sockets (>= 4.3.0) -> System.Net.Primitives (>= 4.3.0)  [C:\b\w\590aeb6bc9b87cb8\.r\SignalR\.build\KoreBuild.proj]
 SocketsSample (>= 1.0.0) -> Microsoft.AspNetCore.SignalR.Redis (>= 1.0.0-preview1-24766) -> StackExchange.Redis.StrongName (>= 1.1.605) -> System.Net.Sockets (>= 4.1.0) -> System.Net.Primitives (>= 4.0.11) [C:\b\w\590aeb6bc9b87cb8\.r\SignalR\.build\KoreBuild.proj]
```

**Comment by moozzyk** [comment] 2017-04-30 20:22
It is a dupe of https://github.com/aspnet/SignalR/issues/359.

**Closed** 2017-05-08 21:13 UTC
