### ISSUE TITLE
Method not Found Void Microsoft.AspNetCore.Sockets.Client.HttpConnection..ctor(System.Uri, Microsoft.AspNetCore.Sockets.TransportType, Microsoft.Extensions.Logging.ILoggerFactory, System.Net.Http.HttpMessageHandler)

### ISSUE THREAD

**Issue by PedroHFranco** [aspnet/SignalR#2507] opened 2018-06-18 14:25 UTC
Hello guys,

I'm gotting the folow error when i'm trying to connect with HubConnectionBuilder.

> Método não encontrado: 'Void Microsoft.AspNetCore.Sockets.Client.HttpConnection..ctor(System.Uri, Microsoft.AspNetCore.Sockets.TransportType, Microsoft.Extensions.Logging.ILoggerFactory, System.Net.Http.HttpMessageHandler)'.

StackTrace:   

> em Microsoft.AspNetCore.SignalR.Client.HubConnectionBuilderHttpExtensions.<>c__DisplayClass3_0.<WithUrl>b__0()
>    em Microsoft.AspNetCore.SignalR.Client.HubConnectionBuilder.Build()
>    em Sync.Framework.Core.Services.SignalR.Monitoring.MonitoringConnection.BuildAndConnectOnHub() na D:\Projetos\Sync\Sync.Framework\Sync.Framework.Core\Services\SignalR\Monitoring\MonitoringConnection.cs:linha 62

This is my code in my Client-Side:

```
//I have created a singleton class because of thaht my _hubConnection is create globaly
_hubConnection = new HubConnectionBuilder()
                    .WithUrl(url)
                    .WithMessagePackProtocol()
                    .WithTransport(Microsoft.AspNetCore.Sockets.TransportType.WebSockets)
                    .Build();

 _hubConnection.StartAsync().Wait();

```
I'm using these versions:
```
  <package id="Microsoft.AspNetCore.SignalR.Client" version="1.0.0-alpha2-final" targetFramework="net461" />
  <package id="Microsoft.AspNetCore.SignalR.Client.Core" version="1.0.0-alpha2-final" targetFramework="net461" />
  <package id="Microsoft.AspNetCore.SignalR.Common" version="1.0.0-alpha2-final" targetFramework="net461" />
```
Its a C# client.

My Server side have the Microsoft.AspNetCore.SignalR version 1.0.0-alpha2-final

```
public override Task OnConnectedAsync()
{
	var httpContext = Context.Connection.GetHttpContext();
	var token = httpContext.Request.Query["Token"];
	switch (token)
	{
		case "log4net":
			Groups.AddAsync(Context.ConnectionId, "log4net").Wait();
			break;
		case "autoupdate":
			token = httpContext.Request.Query["Conta"];
			UpdateConnectionIdAutoUpdate(token, Context.ConnectionId);
			Groups.AddAsync(Context.ConnectionId, "autoupdate").Wait();
			break;
		default:
			UpdateConnectionIdConta(token, Context.ConnectionId);
			break;
	}

	return base.OnConnectedAsync();
}
```
It's an Azure Web app.

I'm using Windows in both side.

Any idea how can i fix that ?

**Comment by davidfowl** [comment] 2018-06-18 14:46
Why are you still using the alpha packages? You should upgrade to .NET Core 2.1 and ASP.NET Core 2.1.

**Comment by anurse** [comment] 2018-06-18 14:54
Your packages are very out of date and no longer supported. The latest supported version is `1.0.0` (the official release). Please ensure your server is updated to the final build of ASP.NET Core 2.1 (`Microsoft.AspNetCore.App` version `2.1.0`) and update your client packages to `1.0.0` to see if the issue reproduces there. If so, we can investigate further.

I'm closing this for now as the issue is due to out of date packages. If you're still seeing the issue after updating, we can always re-open it. Feel free to comment further if you need assistance updating!

**Closed by anurse** 2018-06-18 14:54 UTC
