### ISSUE TITLE
Dispose subscription on client doesn't dispose writer on server

### ISSUE THREAD

**Issue by blubiszirp** [aspnet/SignalR#2782] opened 2018-08-10 14:38 UTC
I have an aspnetcore backend and an angular client (with Microsoft.AspNetCore.SignalR v1.0.2 and @aspnet/signalr 1.0.2)

On the server I use the [AsChannelReader example](https://github.com/aspnet/SignalR/blob/release/2.2/samples/SignalRSamples/ObservableExtensions.cs):
```
public static ChannelReader<T> AsChannelReader<T>(this IObservable<T> observable, CancellationToken ct, int? maxBufferSize = null)
{
    var channel = maxBufferSize != null ? Channel.CreateBounded<T>(maxBufferSize.Value) : Channel.CreateUnbounded<T>();

    var disposable = observable.Subscribe(
        value => { Console.WriteLine("writing: " + value); channel.Writer.TryWrite(value); },
        error => channel.Writer.TryComplete(error),
        () => {
            channel.Writer.TryComplete();
            Console.WriteLine("channel.Writer.TryComplete();");
        });

    var abortRegistration = ct.Register(() => {
        channel.Writer.Complete();
        Console.WriteLine("channel.Writer.Complete();");
    });

    channel.Reader.Completion.ContinueWith(task =>
    {
        Console.WriteLine("channel.Reader.Completion.ContinueWith");
        disposable.Dispose();
        abortRegistration.Dispose();
    });

    Console.WriteLine("Created a new ChannelReader");
    return channel.Reader;
}
```

On the client the data are received in this way:

`const subscription = this.connection.stream<T>(methodName, ...args).subscribe(observer);`

If I dispose the subscription, noting happens on the server (no console output), it is still writing data. But on the client there is an CancelInvocationMessageType (5) and a CompletionMessageType (3) in the WebSocket and I receive no more data:
![image](https://user-images.githubusercontent.com/11313424/43963339-53f2f4ba-9cba-11e8-9e30-ab7fbb47ea5c.png)

If I close the connection with this.connection.stop(), there is a "channel.Writer.Complete();" and a "channel.Reader.Completion.ContinueWith" but no "channel.Writer.TryComplete();"

How can I stop the server from writing data when I dispose the subscription on the client without closing/stopping the connection?

**Comment by JanEggers** [comment] 2018-08-12 12:02
further analysing I think I found the issue.

I think that we need access to this cancellation token or better the combined token:
https://github.com/aspnet/SignalR/blob/08ee88221744543b7751f0dea30d0c653d3b9f55/src/Microsoft.AspNetCore.SignalR.Core/Internal/DefaultHubDispatcher.cs#L395-L400


preferrable the token should be created before invoking the hub method and providing it there as argument

**Comment by JanEggers** [comment] 2018-08-12 13:29
I think I found the issue:

https://github.com/aspnet/SignalR/blob/08ee88221744543b7751f0dea30d0c653d3b9f55/src/Microsoft.AspNetCore.SignalR.Core/Internal/DefaultHubDispatcher.cs#L239

this method only disposes the async enumerator but does not trycomplete the writer

**Comment by BrennanConroy** [comment] 2018-08-13 04:43
Seems like a dupe of https://github.com/aspnet/SignalR/issues/2597

**Comment by JanEggers** [comment] 2018-08-13 05:47
I Agree that its a dupe but its not an enhancement but a critical bug

**Comment by anurse** [comment] 2018-08-13 16:49
Closing as we are tracking this issue already. Feel free to move commentary to that issue, if we need to update prioritization/tracking on that issue we can do that for sure.

**Closed by anurse** 2018-08-13 16:49 UTC
Labels: status: Investigate
