### ISSUE TITLE
npm package file naming

### ISSUE THREAD

**Issue by JonasMH** [aspnet/SignalR#987] opened 2017-10-04 18:51 UTC
When switching from the dev-repository version '1.0.0-alpha1-26997' to the npm-version '1.0.0-alpha1-final' the javascript bundles changed name, thereby breaking any references to the files. And given the naming of the file(s):
```
signalr-client-1.0.0-alpha1-final.js
signalr-clientES5-1.0.0-alpha1-final.js
signalr-msgpackprotocol-1.0.0-alpha1-final.js
```
It looks like it will keep breaking every time there's a change of version.

So a simple fix would be to call them
```
signalr-client.js
signalr-clientES5.js
signalr-msgpackprotocol.js
```
### Functional impact
Breaks references each time there's an update.

**Comment by moozzyk** [comment] 2017-10-04 19:03
Yes, each time there is a new version the code using the script might need to be updated (e.g. alpha2 will have some api changes and your [application may stop working](https://github.com/aspnet/SignalR/issues/974#issuecomment-333603644) since you will be using the new version implicitly). Also, not having the version makes it very hard to reproduce issues reported by users. I am closing this as by design.

**Closed by moozzyk** 2017-10-04 19:03 UTC
