### ISSUE TITLE
Don't error on the client when binding doesn't exist for method

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR#2315] opened 2018-05-18 09:05 UTC
Today we warn in both javascript and .NET Clients if the method doesn't exist (at the very least, there should be a way to turn this off). Even worse is that the .NET client both warns and then fails with errors if arguments aren't provided that the method expects (related to https://github.com/aspnet/SignalR/issues/2313 but on the client)

```
warn: Microsoft.AspNetCore.SignalR.Client.HubConnection[14]
      Failed to find handler for 'TestDateTimeUTC' method.
fail: Microsoft.AspNetCore.SignalR.Client.HubConnection[57]
      Failed to bind arguments received in invocation '(null)' of 'TestDateTimeUTC'.
System.IO.InvalidDataException: Invocation provides 1 argument(s) but target expects 0.
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.BindArguments(JsonTextReader reader, IReadOnlyList`1 paramTypes)
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.ParseMessage(Utf8BufferTextReader textReader, IInvocationBinder binder)
```

We shouldn't have any errors here at all.

**Comment by anurse** [comment] 2018-05-18 16:36
> at the very least, there should be a way to turn this off

When is it expected that the server would intentionally invoke a method that doesn't exist? I get wanting to turn the error off and just leave it as a warning, but I'm trying to understand the scenario where no logging at all is desirable.

**Comment by davidfowl** [comment] 2018-05-18 18:48
https://github.com/aspnet/SignalR-samples/blob/b681b634c2381362bbf43af0984bee05abc6effb/StockTickR/CsharpClient/Program.cs#L43-L56

Here I had to skip the thing.

**Comment by anurse** [comment] 2018-05-19 16:54
Gotcha. We should definitely log it though. Maybe just `Debug` is ok.

**Comment by anurse** [comment] 2018-05-19 17:02
Putting this in 2.2.0, seems small and easy.

**Comment by anurse** [comment] 2018-06-18 16:50
Dupe of #2313. They're not 100% the same, but I'm pretty sure the resolution will be the same.

**Closed by anurse** 2018-06-18 16:50 UTC
Labels: cost: XS, enhancement
