### ISSUE TITLE
Feature Request - Add Invoke method to IClientProxy which can wait for a response from the client.

### ISSUE THREAD

**Issue by lianying** [aspnet/SignalR#3045] opened 2018-10-02 03:27 UTC
Sometimes server side need wait for a response result from client invocation. I already tried to extend IClientProxy, but too many classes have to replace. DefaultHubDispatcher/HubConnectionContext... have many internal properties or classes.

**Comment by anurse** [comment] 2018-10-03 17:10
This is something we've talked about but it would be a significant work item. Also, it would *only* work when addressing a single client `Clients.Client(...)` since otherwise you'd have to wait for all clients to return data. I'm putting this in the backlog since I don't think we have an issue tracking this right now.

**Comment by lianying** [comment] 2018-10-04 06:15
Got it! Thanks for your reply! I’m trying to study this issue and I think it’s meaningful now.

**Comment by davidfowl** [comment] 2018-10-04 07:46
@anurse we do, this is basically a dupe of https://github.com/aspnet/SignalR/issues/903

**Closed by davidfowl** 2018-10-04 07:46 UTC
Labels: status: Needs Design, type: Enhancement

**Comment by anurse** [comment] 2018-10-04 16:47
Agreed, but the other issue was a little unclear on that point. Clarified it.
