### ISSUE TITLE
Flaky Test: After parsing a value an unexpected character was encountered

### ISSUE THREAD

**Issue by mikeharder** [aspnet/SignalR#1609] opened 2018-03-15 20:41 UTC
After cloning and running `build.cmd`, I hit the following test failure:

```
[xUnit.net 00:00:18.7359426]     Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests.CanStreamClientMethodFromServer(protocol: MessagePackHubProtocol { Name = "messagepack", SerializationContext = SerializationContext { CompatibilityOptions = SerializationCompatibilityOptions { ... }, DefaultCollectionTypes = DefaultConcreteTypeRepository { ... }, DefaultDateTimeConversionMethod = Timestamp, DictionarySerlaizationOptions = DictionarySerlaizationOptions { ... }, EnumSerializationMethod = ByName, ... }, TransferFormat = Binary }, transportType: LongPolling, path: "/hubT") [PASS]
[xUnit.net 00:00:18.7361747]       Output:
[xUnit.net 00:00:18.7362909]         | TestLifetime Information: Starting test CanStreamClientMethodFromServer_messagepack_LongPolling_hubT
[xUnit.net 00:00:18.7363355]         | Microsoft.AspNetCore.Sockets.Client.HttpConnection Debug: Connection state changed from Disconnected to Connecting.
[xUnit.net 00:00:18.7363745]         | Microsoft.AspNetCore.Sockets.Client.HttpConnection Debug: Starting connection.
[xUnit.net 00:00:18.7364169]         | Microsoft.AspNetCore.Sockets.Client.HttpConnection Debug: Establishing Connection at: http://127.0.0.1:50040/hubT.
[xUnit.net 00:00:18.7364597]         | Microsoft.AspNetCore.Sockets.Client.HttpConnection Debug: Skipping transport WebSockets because it was disabled by the client.
[xUnit.net 00:00:18.7364992]         | Microsoft.AspNetCore.Sockets.Client.HttpConnection Debug: Skipping transport ServerSentEvents because it was disabled by the client.
[xUnit.net 00:00:18.7365389]         | Microsoft.AspNetCore.Sockets.Client.HttpConnection Debug: Starting transport 'LongPolling' with Url: http://127.0.0.1:50040/hubT?id=9049e243-9cb2-4fe2-b491-787eb28b9734.
[xUnit.net 00:00:18.7365764]         | Microsoft.AspNetCore.Sockets.Client.LongPollingTransport Information: Starting transport. Transfer mode: Binary.
[xUnit.net 00:00:18.7366162]         | Microsoft.AspNetCore.Sockets.Client.LongPollingTransport Debug: Starting receive loop.
[xUnit.net 00:00:18.7366162]         | Microsoft.AspNetCore.Sockets.Client.LongPollingTransport Debug: Starting receive loop.
The active test run was aborted. Reason: After parsing a value an unexpected character was encountered: V. Path 'Payload.NewTestResults[4].DisplayName', line 1, position 42676.

Total tests: Unknown. Passed: 927. Failed: 0. Skipped: 5.
Test Run Aborted.
Test execution time: 38.3080 Seconds
C:\Users\mharder\.dotnet\buildtools\korebuild\2.1.0-preview2-15726\modules\vstest\module.targets(106,5): error : Test group UnitTests/net461 failed with exit code '1'. [C:\Users\mharder\.dotnet\buildtools\korebuild\2.1.0-preview2-15726\KoreBuild.proj]
```

I then ran `build.cmd` again and everything passed.

**Comment by anurse** [comment] 2018-03-15 21:33
This looks like an issue in the test runner because of this line:

```
The active test run was aborted. Reason: After parsing a value an unexpected character was encountered: V. Path 'Payload.NewTestResults[4].DisplayName', line 1, position 42676.
```

Not sure what, if anything we can do about it. If we can get a repro, we could report it to the VSTest team.

**Comment by anurse** [comment] 2018-03-16 21:10
This is caused by https://github.com/Microsoft/vstest/issues/1435, closing.

**Closed by anurse** 2018-03-16 21:10 UTC

**Comment by mikeharder** [comment] 2018-03-16 21:26
We should update all repos to Microsoft.NET.Test.Sdk 15.6.1 to address this.  I'll work with the engineering team to do this.
