### ISSUE TITLE
JavaFX(Intellij) project use Chat.java, it appears [Exception in thread "OkHttp Dispatcher" java.lang.NullPointerException]

### ISSUE THREAD

**Issue by akira32** [aspnet/SignalR#3251] opened 2018-11-02 07:13 UTC
I create a JavaFX(Intellij) in CentOS7 and write a pom.xml its content as below:

```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>jpademo</artifactId>
    <version>1.0</version>
    <packaging>jar</packaging>

    <dependencies>

        <dependency>
            <groupId>com.microsoft.signalr</groupId>
            <artifactId>signalr</artifactId>
            <version>1.0.0-preview3-35501</version>
        </dependency>

        <dependency>
            <groupId>io.reactivex.rxjava2</groupId>
            <artifactId>rxjava</artifactId>
            <version>2.2.2</version>
        </dependency>

        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-nop</artifactId>
            <version>1.7.25</version>
        </dependency>

    </dependencies>
</project>
```
I run the SignalRSamples use net461, the information as below:
I also run two ClientSample with hub parameter. And then I can see the two ClientSample connecct and send message each other.

```
warn: Microsoft.AspNetCore.Server.Kestrel[0]
      Overriding address(es) 'http://localhost:54035/'. Binding to endpoints defined in UseKestrel() instead.
Hosting environment: Development
Content root path: C:\tmp\SignalRJava\SignalR-release-2.2\samples\SignalRSamples
Now listening on: http://localhost:5000
Now listening on: http://0.0.0.0:9001
Application started. Press Ctrl+C to shut down.
info: Microsoft.AspNetCore.SignalR.HubConnectionContext[1]
      Completed connection handshake. Using HubProtocol 'json'.
info: Microsoft.AspNetCore.SignalR.HubConnectionContext[1]
      Completed connection handshake. Using HubProtocol 'json'.
```

But I put "SignalR/clients/java/signalr/src/test/java/com/microsoft/signalr/sample/Chat.java" into my JavaFX project and assign Chat main as default open class. Run the JavaFX project, the output as below:
I input the URL of the SignalR Chat as http://192.168.56.1:5000. I am sure that I can ping 196.168.56.1 from Linux.

**Enter the URL of the SignalR Chat you want to join
http://192.168.56.1:5000
Enter your name:AK**

But the output of Intellij appears **Exception in thread "OkHttp Dispatcher" java.lang.NullPointerException**. Does somebody know whether Java's Chat.java and SignalRSamples can connection each other? How to solve the problem of "OkHttp Dispatcher"?

The complete output message as below:
```
/usr/java/jdk1.8.0_191-amd64/bin/java -javaagent:/opt/idea-IU-182.4892.20/lib/idea_rt.jar=22675:/opt/idea-IU-182.4892.20/bin -Dfile.encoding=UTF-8 -classpath /usr/java/jdk1.8.0_191-amd64/jre/lib/charsets.jar:/usr/java/jdk1.8.0_191-amd64/jre/lib/deploy.jar:/usr/java/jdk1.8.0_191-amd64/jre/lib/ext/cldrdata.jar:/usr/java/jdk1.8.0_191-amd64/jre/lib/ext/dnsns.jar:/usr/java/jdk1.8.0_191-amd64/jre/lib/ext/jaccess.jar:/usr/java/jdk1.8.0_191-amd64/jre/lib/ext/jfxrt.jar:/usr/java/jdk1.8.0_191-amd64/jre/lib/ext/localedata.jar:/usr/java/jdk1.8.0_191-amd64/jre/lib/ext/nashorn.jar:/usr/java/jdk1.8.0_191-amd64/jre/lib/ext/sunec.jar:/usr/java/jdk1.8.0_191-amd64/jre/lib/ext/sunjce_provider.jar:/usr/java/jdk1.8.0_191-amd64/jre/lib/ext/sunpkcs11.jar:/usr/java/jdk1.8.0_191-amd64/jre/lib/ext/zipfs.jar:/usr/java/jdk1.8.0_191-amd64/jre/lib/javaws.jar:/usr/java/jdk1.8.0_191-amd64/jre/lib/jce.jar:/usr/java/jdk1.8.0_191-amd64/jre/lib/jfr.jar:/usr/java/jdk1.8.0_191-amd64/jre/lib/jfxswt.jar:/usr/java/jdk1.8.0_191-amd64/jre/lib/jsse.jar:/usr/java/jdk1.8.0_191-amd64/jre/lib/management-agent.jar:/usr/java/jdk1.8.0_191-amd64/jre/lib/plugin.jar:/usr/java/jdk1.8.0_191-amd64/jre/lib/resources.jar:/usr/java/jdk1.8.0_191-amd64/jre/lib/rt.jar:/home/myUser/IdeaProjects/SignalRClient6/target/classes:/home/myUser/.m2/repository/com/microsoft/signalr/signalr/1.0.0-preview3-35501/signalr-1.0.0-preview3-35501.jar:/home/myUser/.m2/repository/com/google/code/gson/gson/2.8.5/gson-2.8.5.jar:/home/myUser/.m2/repository/com/squareup/okhttp3/okhttp/3.11.0/okhttp-3.11.0.jar:/home/myUser/.m2/repository/com/squareup/okio/okio/1.14.0/okio-1.14.0.jar:/home/myUser/.m2/repository/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar:/home/myUser/.m2/repository/io/reactivex/rxjava2/rxjava/2.2.2/rxjava-2.2.2.jar:/home/myUser/.m2/repository/org/reactivestreams/reactive-streams/1.0.2/reactive-streams-1.0.2.jar:/home/myUser/.m2/repository/org/slf4j/slf4j-nop/1.7.25/slf4j-nop-1.7.25.jar sample.Chat

Enter the URL of the SignalR Chat you want to join
http://192.168.56.1:5000
Enter your name:AK

Exception in thread "OkHttp Dispatcher" java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1975)
	at com.microsoft.signalr.DefaultHttpClient$2.onFailure(DefaultHttpClient.java:108)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:161)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by BrennanConroy** [comment] 2018-11-02 15:39
When passing a URL you need to include the hub route. For example in the SignalRSamples you can pass in "http://localhost:5000/default".

I suggest you read our [docs](https://docs.microsoft.com/aspnet/core/tutorials/signalr?view=aspnetcore-2.1&tabs=visual-studio) and write your own app from scratch so you understand everything going on.

**Comment by akira32** [comment] 2018-11-03 11:40
I had solved my problem. I comment original source code and add Send and Receive Message parameters from two to one.
Thank you, @BrennanConroy . The key word is the URL of the SignalR(http://localhost:5000/default).
```
        hubConnection.on("Send", (message) -> {
            System.out.println(message);
        }, String.class);

        //hubConnection.on("Send", (name, message) -> {
        //    System.out.println(name + ": " + message);
        //}, String.class, String.class);


        String message = "";
        while (!message.equals("leave")) {
            // Scans the next token of the input as an int.
            message = reader.nextLine();
            //hubConnection.send("Send", enteredName, message);
            hubConnection.send("Send", message);
        }
```

**Comment by BrennanConroy** [comment] 2018-11-05 16:09
Glad you found the solution! Closing as it looks like the issue is resolved.

**Closed by BrennanConroy** 2018-11-05 16:09 UTC
