### ISSUE TITLE
How to ensure the application fails if it can't establish a connection to Redis?

### ISSUE THREAD

**Issue by josemaia** [aspnet/SignalR#2468] opened 2018-06-11 15:33 UTC
Hello,

I added Redis usage to my application, for backplane purposes. However, after passing an invalid connection string, nothing happened. Ideally, I would prefer it to crash outright, but it's not even getting logged with my default logging settings (Warning or higher for System/Microsoft DLLs), so it makes it really hard to use!

```
services.AddSignalR()
  .AddRedis(servicesEndpointsConfiguration.RedisConnectionString);
```

With this scenario, if I pass an invalid connection string (i.e. add the password in the wrong place, such as pass@server:port instead of server:port,password=pass=, it'll fail. I set my log to Debug to capture this, and the chunk below is the final message:

```
2018-06-11 16:12:16.811 +01:00 [Debug] [] password123@redis-fakeServer.example.com:1234 did not respond
2018-06-11 16:12:16.872 +01:00 [Debug] [] password123@redis-fakeServer.example.com:1234 failed to nominate (WaitingForActivation)
2018-06-11 16:12:16.877 +01:00 [Debug] [] No masters detected
2018-06-11 16:12:16.881 +01:00 [Debug] [] password123@redis-fakeServer.example.com:1234: Standalone v2.0.0, master; keep-alive: 00:01:00; int: Disconnected; sub: Disconnected; not in use: DidNotRespond
2018-06-11 16:12:16.886 +01:00 [Debug] [] password123@redis-fakeServer.example.com:1234: int ops=0, qu=2, qs=0, qc=0, wr=0, sync=2, async=2, socks=4; sub ops=0, qu=0, qs=0, qc=0, wr=0, socks=4
```

My question is:
- Is there a way to guarantee that, if a connection string is passed, we crash if the connection isn't possible to establish?

- If not, how else can I protect my customers? Manually 'ping' the connection somehow?

Thank you.

### Please include as much of the following as you can in your bug report

* Versions of Server-Side NuGet Packages: 1.0.0
* Are you using the C# client or the JavaScript client: n/a
* The Server you are using (Kestrel/HttpSysServer/IIS/IIS Express/Azure Web App/etc.): Kestrel
* The Operating System on the Server (Windows/Linux/macOS): Windows
* The Operating System on the Client (Windows/Linux/macOS): Windows

**Comment by anurse** [comment] 2018-06-11 16:42
Because of how StackExchange.Redis works, I think we don't properly detect this failure. StackExchange.Redis tries to reconnect and we don't properly handle the case where it simply fails to connect. We should at least try to log something, or ping the connection. You could work around this a little bit by adding your own startup logic to connect to the Redis server yourself using StackExchange.Redis directly in order to test if it's available. It's not a great solution, but it might help your immediate issue.

I'm putting this on our queue for this next iteration. We'll have to see where it can land (I think it will fit in a patch, but not sure exactly which one yet ;)). It will certainly be something we fix in 2.2.

**Comment by davidfowl** [comment] 2018-06-11 17:24
Makes me wonder if we should connect before constructing the HubLifetimeManager in the call to AddRedis itself.

**Comment by BrennanConroy** [comment] 2018-06-28 17:50
We have warning logs that say Redis isn't connected.

As far as early "crash" we could consider adding back a synchronous connect to the RedisHubLifetimeManager ctor and add an option to error if it doesn't connect.

Are you wanting to only error on first connect but keep reconnect on?

**Comment by josemaia** [comment] 2018-06-28 20:42
I could honestly work with either solution. I'd have to check with the team to know what they think (i.e. if redis isn't a requirement, it's no big deal that we don't connect to it).

**Comment by BrennanConroy** [comment] 2018-08-08 17:17
The previous version of SignalR does basically the same thing we do. Keep trying to connect and log when it fails. The log level was error then, ours is currently warning. But since SignalR won't really work if it's setup for Redis and doesn't have a connection then we could make this an error log.

**Comment by BrennanConroy** [comment] 2018-08-20 19:17
Simple example showing how you can hook the redis connection events

```c#
services.AddSignalR()
        .AddMessagePackProtocol()
        .AddRedis(o =>
        {
            o.ConnectionFactory = async writer =>
            {
                var config = new ConfigurationOptions
                {
                    AbortOnConnectFail = false
                };
                config.EndPoints.Add(IPAddress.Loopback, 0);
                config.SetDefaultPorts();
                var connection = await ConnectionMultiplexer.ConnectAsync(config, writer);
                connection.ConnectionFailed += (_, e) =>
                {
                    Console.WriteLine("Connection Redis failed.");
                };

                if (!connection.IsConnected)
                {
                    Console.WriteLine("Connection did not connect.");
                }

                return connection;
            };
        });
```

**Comment by BrennanConroy** [comment] 2018-08-22 17:36
Merged log level changes

**Closed by BrennanConroy** 2018-08-22 17:36 UTC
Labels: PRI: 2 - Preferred, cost: S, type: Bug

**Comment by cgyqu** [comment] 2018-08-28 15:34
@BrennanConroy,use ConnectionFactory ,redis will connect twice.Do you notice that?

**Comment by BrennanConroy** [comment] 2018-08-28 15:47
It shouldn't, could you explain what you're seeing?

**Comment by anurse** [comment] 2018-08-28 18:06
Note: If a custom `ConnectionFactory` is provided, we **should not** be calling `ConnectAsync` (see https://github.com/aspnet/SignalR/blob/release/2.2/src/Microsoft.AspNetCore.SignalR.Redis/RedisOptions.cs#L31) so if you're seeing something different @cgyqu, please let us know!

**Comment by cgyqu** [comment] 2018-08-29 02:34
I also looked at the source code.This is my code 
```C#
.AddRedis(option =>
 {
     option.ConnectionFactory = async writer =>
     {
         var connection = await RedisConnectionHelper.GetRedisConnection("livechat_cluster_signalR");
         connection.ConnectionFailed += (_, e) =>
         {
             LoggerHelper.Info("StartUp", "SignalR", "Redis", $"Connection Redis failed," + e.Exception.ToString());
         };

         if (!connection.IsConnected)
         {
             LoggerHelper.Info("StartUp", "SignalR", "Redis", $"Connection did not connect");
         }
         else
         {
             LoggerHelper.Info("StartUp", "SignalR", "Redis", $"Redis Connection  connect,connectStr:" + connection.Configuration);
         }
         return connection;
     };
 })
```
When Application started,two logs are logged;

> 2018-08-29 10:12:36.221 Info [StartUp][SignalR][Redis][][]Redis Connection  connect,connectStr:xxxxxx,abortConnect=False
> 2018-08-29 10:12:36.221 Info [StartUp][SignalR][Redis][][]Redis Connection  connect,connectStr:xxxxx4,abortConnect=False


So I debug the program and also find that the connection is called twice.
The console log also show this situation.

>signalr.service> info: Microsoft.AspNetCore.SignalR.Redis.RedisHubLifetimeManager[2]
>signalr.service>       Connected to Redis.
>signalr.service> info: Microsoft.AspNetCore.SignalR.Redis.RedisHubLifetimeManager[2]
>signalr.service>       Connected to Redis.
>signalr.service> Hosting environment: Development

**Comment by anurse** [comment] 2018-08-29 15:22
Do you have more than one hub in your application or is it just a single hub?

**Comment by cgyqu** [comment] 2018-08-30 10:51
By the way, when I was debugging, the first time redis connected at `AddRedis`, the second time was at `built.maphub <ChatHub>("/chat")`

**Comment by anurse** [comment] 2018-08-31 17:44
>     app.UseSignalR(builder =>
>     {
>         builder.MapHub<ChatHub>("/chat");
>         builder.MapHub<TestHub>("/test");
>     });

This is why there are two connections. We create a separate Redis connection for each Hub at the moment, since the Redis connection is managed by `RedisHubLifetimeManager<THub>` (where `THub` is your Hub type), so there are two instances in the DI container by design. I'm filing https://github.com/aspnet/SignalR/issues/2900 to consider changing that, though there are a bunch of things to review before we can do that.

**Comment by cgyqu** [comment] 2018-09-04 03:30
@anurse ,only one hub also connect twice.I don't have much time to look it up .It's up to you.

**code**
```
 app.UseSignalR(builder =>
 {
     builder.MapHub<ChatHub>("/chat");
     //builder.MapHub<TestHub>("/test");
 });
```
**log**
> info: Microsoft.AspNetCore.SignalR.Redis.RedisHubLifetimeManager[2]
>       Connected to Redis.
> info: Microsoft.AspNetCore.SignalR.Redis.RedisHubLifetimeManager[2]
>       Connected to Redis.
