### ISSUE TITLE
[Android&Java] on network change

### ISSUE THREAD

**Issue by xiazunyang** [aspnet/SignalR#3341] opened 2018-11-30 03:31 UTC
https://github.com/aspnet/SignalR/blob/master/clients/java/signalr/src/main/java/com/microsoft/signalr/OkHttpWebSocketWrapper.java#L98
should change to  ```onClose.invoke(0, t.getMessage());```
Otherwise NullPointerException will occur when the network state changes.

**Comment by BrennanConroy** [comment] 2018-11-30 03:41
Dupe of https://github.com/aspnet/SignalR/issues/3336
We've fixed it in the RTM version, which should be out before the end of the year

**Closed as completed by BrennanConroy** 2018-11-30 03:41 UTC
