### ISSUE TITLE
HubConneciton.On execute multiple times when callbackName and the method are exactly the same but HubConneciton.On defined several times

### ISSUE THREAD

**Issue by realwanpengli** [aspnet/SignalR#2695] opened 2018-07-30 08:28 UTC
### Please include as much of the following as you can in your bug report

* Versions of Server-Side NuGet Packages: 1.0.0-preview1-*
* Versions of Client-Side NuGet/NPM Packages: 1.0.1
* Are you using the C# client or the JavaScript client: C#
* The Server you are using (Kestrel/HttpSysServer/IIS/IIS Express/Azure Web App/etc.): Kestrel
* The Operating System on the Server (Windows/Linux/macOS): Windows/Linux/macOS
* The Operating System on the Client (Windows/Linux/macOS): Windows/Linux/macOS

When the HubConneciton.On(callbackName, method) defined m times, the callback will execute m times.
the callbackName and the method are exactly the same. Why not execute only 1 time.

**Comment by davidfowl** [comment] 2018-07-30 15:37
That’s correct, this is by design.

**Comment by BrennanConroy** [comment] 2018-07-30 20:56
Closing the issue as this is by design.

**Closed by BrennanConroy** 2018-07-30 20:56 UTC

**Comment by realwanpengli** [comment] 2018-07-31 02:08
@BrennanConroy Thanks.
