### ISSUE TITLE
Unable to npm run build because of minification

### ISSUE THREAD

**Issue by Pictar** [aspnet/SignalR#977] opened 2017-10-03 13:43 UTC
Hello,

I added this package to my web app in order to use web sockets with a back in asp net core. However, I can't run build without getting the following error :

> Failed to minify the code from this file:
> ./node_modules/@aspnet/signalr-client/dist/src/Loggers.js:6

Does anyone is familiar with this error ?

**Comment by davidfowl** [comment] 2017-10-03 14:35
@Pictar can you post your web app or a sample that reproduces the problem.

**Comment by Pictar** [comment] 2017-10-05 08:37
@davidfowl Sure, you can find it here [https://github.com/Pictar/PWA-Chat/tree/master/PWA-App](url)

**Comment by davidfowl** [comment] 2017-10-05 13:37
That link 404s for me

**Comment by moozzyk** [comment] 2017-10-06 17:34
@Pictar  - does it work if you use react 16.0.0-alpha.12? Here is an [issue](https://github.com/aspnet/SignalR/issues/957) I investigated which contains a link to a react native application that builds and runs successfully. It is however using react 16.0.0-alpha.12. I think the issue here is that UglifyJS only recently started to support ES6. Also, take a look at this issue: https://github.com/aspnet/SignalR/issues/983. It contains a workaround (using the ES5 version of the client) which I think could help without having to change versions.

**Comment by mikewoudenberg** [comment] 2017-10-18 14:53
I'm having the same issue whilest building an application using `create-react-app`. It also provides a helpful link describing what to do:
> react-scripts build

Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file:

        ./node_modules/@aspnet/signalr-client/dist/src/Loggers.js:6

Read more here: http://bit.ly/2tRViJ9 

The suggested steps to resolve this start with:

To resolve this:

Open an issue on the dependency's issue tracker and ask that the package be published pre-compiled (retaining ES6 Modules).

**Comment by moozzyk** [comment] 2017-10-20 19:38
It is a dupe of https://github.com/aspnet/SignalR/issues/977

**Closed by moozzyk** 2017-10-20 19:38 UTC

**Comment by pardahlman** [comment] 2018-02-18 08:24
@moozzyk I believe that you made a mistake when referencing to the Github issue as #977 is in fact this issue. So my question is: which ticket is this a dupe of? 😉

**Comment by moozzyk** [comment] 2018-02-19 04:35
It was a duplicate of a ticket where UglifyJS did not support ES6. My understanding is that with the latest changes to the npm package this is no longer an issue.

**Comment by pardahlman** [comment] 2018-02-19 06:39
You are correct, after digging around in the issues here I found what I was looking for. Thanks!
