### ISSUE TITLE
Msgpack: byte[] decoded as string

### ISSUE THREAD

**Issue by AndriySvyryd** [aspnet/SignalR#945] opened 2017-09-25 20:00 UTC
Hub:
```C#
public Task<byte[]> GetPayload()
    => Task.FromResult(new byte[] {0, 1, 2});
```

Client:
```TS
connection.invoke('GetPayload')
            .then((p: number[]) => console.log(typeof(p)))
```

Prints `string`, expected `object`

Version: alpha1

**Comment by moozzyk** [comment] 2017-09-26 14:36
Looks like the client received an empty string
![image](https://user-images.githubusercontent.com/1438884/30866188-6ce3c88c-a28d-11e7-9816-764386f45a8e.png)

**Comment by davidfowl** [comment] 2017-09-26 14:39
@moozzyk I put it in alpha2

**Comment by moozzyk** [comment] 2017-09-26 15:41
Either we need to use some setting or a bug in MsgPack-Cli. [Writing byte array](https://github.com/aspnet/SignalR/blob/2adf24d1c6bf080a473abe4593e2f649f9e015d8/src/Microsoft.AspNetCore.SignalR.Common/Internal/Protocol/MessagePackHubProtocol.cs#L195) using Packer results in a `fixstr` payload.

**Comment by moozzyk** [comment] 2017-09-26 16:28
msgpack-cli even has a [test](https://github.com/msgpack/msgpack-cli/blob/18c906f58aadfcaf2242a9e4d946a088f923f1df/test/MsgPack.UnitTest/PackerTest.PackObject.cs#L765) which verifies that `byte[]` is packed as `fixstr`. This seems wrong. I opened https://github.com/msgpack/msgpack-cli/issues/261

**Comment by yfakariya** [comment] 2017-09-28 15:13
As I answered [here](https://github.com/msgpack/msgpack-cli/issues/261#issuecomment-332860949), it is by design because of msgpack format spec. Although it is reasonable to treat `byte[]` as unsigned 8bit integer array, msgpack treats it as "binary" instead of array. As my opinion, the JavaScript library should handle this because general msgpack packer implementation should serialize `new byte[] {1, 2, 3}` as `fixstr` or `bin8` type.

**Comment by moozzyk** [comment] 2017-09-29 04:35
How would they know in JavaScript when a fixstr is supposed to be deserialized to a sting and when it is supposed to be deserialized to an array? They don't have a type they could use to make this decision. 

I tried setting PackerCompatibilityOptions to None but the Packer still serialized byte arrays `fixstr` and not `bin8`. See more details [here](https://github.com/msgpack/msgpack-cli/issues/261#issuecomment-333027868).

**Comment by yfakariya** [comment] 2017-09-29 13:37
You are right, sorry for my thoughtless opinion. [I answered how to enable the PackerCompatibilityOptions in your code pattern](https://github.com/msgpack/msgpack-cli/issues/261#issuecomment-333127365).

**Comment by moozzyk** [comment] 2017-09-29 23:21
Setting `PackerCompatibilityOptions` to `None` fixes sending byte[] from the server to the client but things don't work smoothly the other way around. msgpack5 sends `fixarray` for JS arrays [which gets rejected](https://github.com/msgpack/msgpack-cli/issues/261#issuecomment-333251852) by MsgPack-Cli if the target type is byte[]. Sending bin8 array from msgpack5 seems overly complicated. At the moment it will require wrapping the array in a node `Buffer` and trying to send `Uint8Array` (and I assume any typed array) is actually [broken](https://github.com/mcollina/msgpack5/issues/58). For testing, I exposed `Buffer` from the `MessagePackHubProtocol` and was able to send an `Uint8Array` in a way that MsgPack-Cli was able to deserialize it like this: `new signalRMsgPack.Buffer(new Uint8Array([1, 2, 3]))` but we are not going to expose `Buffer`.

@AndriySvyryd - I suggest you use `int[]` for now 😄 - it should work even with alpha1

**Comment by moozzyk** [comment] 2017-10-02 17:09
There is some additional work required in the third party libraries we depend on to make it work from the TS client to the server. Moving this out of alpha2.

**Closed** 2017-11-01 22:50 UTC
Labels: 2 - Working, bug
