### ISSUE TITLE
Exception when sending data from server to client: Failed writing message. System.ArgumentException: The output byte buffer is too small to contain the encoded data, encoding 'Unicode (UTF-8)' fallback 'System.Text.EncoderReplacementFallback'. Parameter name: bytes

### ISSUE THREAD

**Issue by yosigolan** [aspnet/SignalR#2187] opened 2018-05-02 14:34 UTC
Hey.
my system:
Server: on .net core 2.1 preview 2 running on windows using kestel (also tried on azure using app service - same result)
Client - Java script client version: "@aspnet/signalr": "^1.0.0-preview2-final"
Protocol: Json

Scenario: when sending data from the server to the client (using the command: await m_Client.SendAsync("setTripGeneralData",generalData)) in several cases (of data) the following exception is thrown:

```
2018-05-02 16:01:43.815 +03:00|0HLDG5GH9MK8I:00000010|Debug|9|Microsoft.AspNetCore.SignalR.HubConnectionContext.||Failed writing message.
System.ArgumentException: The output byte buffer is too small to contain the encoded data, encoding 'Unicode (UTF-8)' fallback 'System.Text.EncoderReplacementFallback'.
Parameter name: bytes
   at System.Text.Encoding.ThrowBytesOverflow()
   at System.Text.Encoding.ThrowBytesOverflow(EncoderNLS encoder, Boolean nothingEncoded)
   at System.Text.UTF8Encoding.GetBytes(Char* chars, Int32 charCount, Byte* bytes, Int32 byteCount, EncoderNLS baseEncoder)
   at System.Text.EncoderNLS.Convert(Char* chars, Int32 charCount, Byte* bytes, Int32 byteCount, Boolean flush, Int32& charsUsed, Int32& bytesUsed, Boolean& completed)
   at System.Text.Encoder.Convert(ReadOnlySpan`1 chars, Span`1 bytes, Boolean flush, Int32& charsUsed, Int32& bytesUsed, Boolean& completed)
   at Microsoft.AspNetCore.SignalR.Internal.Protocol.Utf8BufferTextWriter.WriteInternal(ReadOnlySpan`1 buffer)
   at Microsoft.AspNetCore.SignalR.Internal.Protocol.Utf8BufferTextWriter.Write(String value)
   at Newtonsoft.Json.Utilities.JavaScriptUtils.WriteEscapedJavaScriptString(TextWriter writer, String s, Char delimiter, Boolean appendDelimiters, Boolean[] charEscapeFlags, StringEscapeHandling stringEscapeHandling, IArrayPool`1 bufferPool, Char[]& writeBuffer)
   at Newtonsoft.Json.JsonTextWriter.WriteEscapedString(String value, Boolean quote)
   at Newtonsoft.Json.JsonTextWriter.WriteValue(String value)
   at Newtonsoft.Json.JsonWriter.WriteValue(JsonWriter writer, PrimitiveTypeCode typeCode, Object value)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializePrimitive(JsonWriter writer, Object value, JsonPrimitiveContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Serialize(JsonWriter jsonWriter, Object value)
   at Microsoft.AspNetCore.SignalR.Internal.Protocol.JsonHubProtocol.WriteArguments(Object[] arguments, JsonTextWriter writer)
   at Microsoft.AspNetCore.SignalR.Internal.Protocol.JsonHubProtocol.WriteInvocationMessage(InvocationMessage message, JsonTextWriter writer)
   at Microsoft.AspNetCore.SignalR.Internal.Protocol.JsonHubProtocol.WriteMessageCore(HubMessage message, IBufferWriter`1 stream)
   at Microsoft.AspNetCore.SignalR.Internal.Protocol.JsonHubProtocol.WriteMessage(HubMessage message, IBufferWriter`1 output)
   at Microsoft.AspNetCore.SignalR.Internal.Protocol.HubProtocolExtensions.WriteToArray(IHubProtocol hubProtocol, HubMessage message)
   at Microsoft.AspNetCore.SignalR.Internal.Protocol.HubMessage.WriteMessage(IHubProtocol protocol)
   at Microsoft.AspNetCore.SignalR.HubConnectionContext.WriteCore(HubMessage message)
```

this didn't happened with the alpha release of signalR core (and .net core 2) with the same data cases.
although the exception implies that the problem is with the size of the data, the data size is not big and in other cases i am sending bigger data amounts with success. i tried investigating the data to pin the difference but i couldn't found nothing sensuous. after saying that, i did tried sending parts of the problematic data and succeeded. only when sending all the problematic data together (its just a list of objects) i am receiving the exception, so maybe it does related to size - i don't know.
i couldn't find a way to enlarge the buffer so i cant test it.
i know that the json.net version was updated in this release of .net core, maybe its related?

any clew anybody?

**Comment by anurse** [comment] 2018-05-02 16:09
@JamesNK @davidfowl This looks like an issue in the UTF8 encoder. `Encoder.Convert` throws if it can't encode a single character.

@yosigolan Do your payloads include non-ASCII characters? I think that's where our bug lies, so I just want to confirm that you're encoding characters outside the ASCII set. We support non-ASCII strings, but I think I see a bug in how we handle them that may be causing this :)

**Comment by JamesNK** [comment] 2018-05-02 16:54
Hmmm. From the stack trace:
```
at System.Text.Encoder.Convert(ReadOnlySpan1 chars, Span1 bytes, Boolean flush, Int32& charsUsed, Int32& bytesUsed, Boolean& completed)
```
Is called here:
https://github.com/aspnet/SignalR/blob/dev/src/Common/Utf8BufferTextWriter.cs#L165

But the `Encoder` should be managing the buffer that text gets written to for us.

**Comment by anurse** [comment] 2018-05-02 22:26
Approved by @muratg

**Comment by yosigolan** [comment] 2018-05-03 05:49
Hey Everyone.
Thanks for the quick handle.
according the above i tried adding one more item at the start of my list and then it works. so @JamesNK i think your direction of "Maybe we get this error if the buffer only has 1 byte left." is correct and the problem the the structure of the data that creates this special case (1 byte left).
as a workaround i will catch the exception and when it happens i will try adding another item at the start of the list and send it again.
@anurse , will your solution be part of the next release? any timelines?

Thanks Yosi

**Comment by yosigolan** [comment] 2018-05-03 06:26
oops. the exception is not bubbling up... so i cant catch it. so i don't have a workaround...
any ideas?

Thanks

**Comment by davidfowl** [comment] 2018-05-03 06:28
> oops. the exception is not bubbling up... so i cant catch it. so i don't have a workaround... any ideas?

Where are you trying to catch the exception? Can you show the code?

**Comment by yosigolan** [comment] 2018-05-03 06:30
try
            {
                Task task = m_Client.SendAsync("setSitesData", sitesData, tripSelectedSitesList, lasViewedSiteIdString);               
                task.Wait();
                //await m_Client.SendAsync("setSitesData", sitesData, tripSelectedSitesList, lasViewedSiteIdString);
            }
            catch (Exception e)
            {
                List<Site> newSites = new List<Site>();
                newSites.Add(sitesData[0]);
                newSites.AddRange(sitesData);
                await m_Client.SendAsync("setSitesData", newSites, tripSelectedSitesList, lasViewedSiteIdString);
            }

i also tried with await, the exception is not thrown.

**Comment by davidfowl** [comment] 2018-05-03 06:36
We actually swallow the exception and log https://github.com/aspnet/SignalR/blob/1bba0fde87a9a2f1a835c6d2173421c089ed7c4e/src/Microsoft.AspNetCore.SignalR.Core/HubConnectionContext.cs#L157 so there's no way for you to catch it.

It's also happening on the server side. What does the code look like on the server side?

**Comment by yosigolan** [comment] 2018-05-03 06:37
what do you mean on the server side? the code i attached is the server side.

**Comment by davidfowl** [comment] 2018-05-03 06:41
> what do you mean on the server side? the code i attached is the server side.

What is m_Client?

**Comment by yosigolan** [comment] 2018-05-03 06:43
its just the name i give to my proxy on the server side:
```
private IClientProxy m_Client;

        public TripPlanSystemViewConnector(IHubContext<HubTripPlanSystem> tripPlanHubContext, string connectionId)
        {
            m_TripPlanHubContext = tripPlanHubContext;
            m_ConnectionId = connectionId;
            m_Client = m_TripPlanHubContext.Clients.Client(m_ConnectionId);                        
        }
```

**Comment by davidfowl** [comment] 2018-05-03 06:47
Ah I see, this logic isn't even inside of a hub. Yea, I'm not sure there's a way to work around this. It's a genuine bug. You could try using a build from myget once we have the fix in here (https://github.com/aspnet/SignalR/pull/2190). But it's going to be broken in the next release (rc1) and fixed in the RTM release (which ships with the rest of ASP.NET Core 2.1)

**Comment by yosigolan** [comment] 2018-05-03 06:51
I understand thanks. i assume you cant give me no estimated dates.
I will send the data twice for now until it will be fixed (in two different ways and hope that one of them wont fall in the problematic scenario).
by the way, i saw you in the asp.net community stand-up the other day, it was great.

Yosi

**Comment by yosigolan** [comment] 2018-05-03 12:11
@davidfowl hey.
How can i get the fix from my get? from which feed? is it merged already?

Thanks

**Comment by anurse** [comment] 2018-05-03 16:11
The PR hasn't been merged yet. Once it's merged, it'll be about a day or so before it's confirmed to be available on the feed. I'll try to remember to ping this thread but I may forget. The fastest way to get the fix once it is merged will be the `aspnetcore-dev` feed: https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json (as always, remember that those builds are completely unsupported and should not be used in production environments).

**Closed** 2018-05-04 02:10 UTC
Labels: 2 - Working, SHP: Approved, bug

**Comment by yosigolan** [comment] 2018-05-04 19:57
Hey @anurse 
I see the PR was merged today, thank you very much. can i assume it will be on the dev branch (under myget) on Sunday?

Thanks Yosi

**Comment by anurse** [comment] 2018-05-04 20:19
Note: the `aspnetcore-dev` feed now has builds for the version **after** 2.1, so I'd suggest you avoid using those builds.

The latest builds on [`dotnet-core`](https://dotnet.myget.org/gallery/dotnet-core) have the fix. As @davidfowl pointed out, this fix missed the deadline to be included in the upcoming RC release, so it won't be officially released until the final RTM release.

**Comment by davidfowl** [comment] 2018-05-05 22:00
You also might be able to work around it by using message pack instead of JSON

**Comment by guylando** [comment] 2018-05-05 22:10
@davidfowl I saw above you mentioned that you swallow exception in SendAsync and instead write
Log.FailedWritingMessage(_logger, ex); 

why do you do that? What if the calling code wants to know if sending the messages failed or not and handle this?

**Comment by davidfowl** [comment] 2018-05-05 23:10
yes I don’t think we should have swallowed this specific exception but you can’t rely on this throwing to indicate that the message didn’t reach the client. If you scale out for example and use redis, it can throw on the other machine and the task you get back from invoking the method would be successfully even though it failed on the other side.

Regardless I think it we over optimized this by catching too many exceptions. We can look at untangling it post 1.0.0

**Comment by davidfowl** [comment] 2018-05-06 05:02
There's one more ugly workaround but it's so ugly I don't want to suggest it. Using the RTM packages from the ci feed would be better.

**Comment by yosigolan** [comment] 2018-05-06 06:43
Thanks @anurse .
thanks @davidfowl . what is the address of the myget of the ci feed? is it the same as the dev?

**Comment by davidfowl** [comment] 2018-05-06 07:04
Yes. https://dotnet.myget.org/feed/aspnetcore-dev/package/nuget/Microsoft.AspNetCore.SignalR/1.0.0-rtm-30733 (that's the latest build).

**Comment by yosigolan** [comment] 2018-05-06 07:16
Thanks. i am trying to configure it and test the fix.

**Comment by yosigolan** [comment] 2018-05-06 08:49
when i add the signalr latest build package like this:  
```<PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.0.0-rtm-30733" />```
i receive many build errors:
```
C:\GitRepos\Backend\AppsWebService\AppsWebService\AppsWebService.csproj : error NU1102: Unable to find package System.Threading.Channels with version (>= 4.5.0-rtm-26502-02)
C:\GitRepos\Backend\AppsWebService\AppsWebService\AppsWebService.csproj : error NU1102:   - Found 13 version(s) in aspnetcoredev [ Nearest version: 4.5.0-preview2-26308-02 ]
C:\GitRepos\Backend\AppsWebService\AppsWebService\AppsWebService.csproj : error NU1102:   - Found 2 version(s) in nuget.org [ Nearest version: 4.5.0-preview2-26406-04 ]
C:\GitRepos\Backend\AppsWebService\AppsWebService\AppsWebService.csproj : error NU1102:   - Found 0 version(s) in Microsoft Visual Studio Offline Packages
C:\GitRepos\Backend\AppsWebService\AppsWebService\AppsWebService.csproj : error NU1102: Unable to find package System.Buffers with version (>= 4.5.0-rtm-26502-02)
C:\GitRepos\Backend\AppsWebService\AppsWebService\AppsWebService.csproj : error NU1102:   - Found 34 version(s) in aspnetcoredev [ Nearest version: 4.5.0-preview2-26308-02 ]
C:\GitRepos\Backend\AppsWebService\AppsWebService\AppsWebService.csproj : error NU1102:   - Found 10 version(s) in nuget.org [ Nearest version: 4.5.0-preview2-26406-04 ]
C:\GitRepos\Backend\AppsWebService\AppsWebService\AppsWebService.csproj : error NU1102:   - Found 1 version(s) in Microsoft Visual Studio Offline Packages [ Nearest version: 4.0.0 ]
C:\GitRepos\Backend\AppsWebService\AppsWebService\AppsWebService.csproj : error NU1102: Unable to find package System.Net.WebSockets.WebSocketProtocol with version (>= 4.5.0-rtm-26502-02)
C:\GitRepos\Backend\AppsWebService\AppsWebService\AppsWebService.csproj : error NU1102:   - Found 4 version(s) in aspnetcoredev [ Nearest version: 4.5.0-preview2-26308-02 ]
C:\GitRepos\Backend\AppsWebService\AppsWebService\AppsWebService.csproj : error NU1102:   - Found 2 version(s) in nuget.org [ Nearest version: 4.5.0-preview2-26406-04 ]
C:\GitRepos\Backend\AppsWebService\AppsWebService\AppsWebService.csproj : error NU1102:   - Found 0 version(s) in Microsoft Visual Studio Offline Packages
C:\GitRepos\Backend\AppsWebService\AppsWebService\AppsWebService.csproj : error NU1102: Unable to find package System.IO.Pipelines with version (>= 4.5.0-rtm-26502-02)
C:\GitRepos\Backend\AppsWebService\AppsWebService\AppsWebService.csproj : error NU1102:   - Found 32 version(s) in aspnetcoredev [ Nearest version: 4.5.0-preview2-26308-02 ]
C:\GitRepos\Backend\AppsWebService\AppsWebService\AppsWebService.csproj : error NU1102:   - Found 4 version(s) in nuget.org [ Nearest version: 4.5.0-preview2-26406-04 ]
C:\GitRepos\Backend\AppsWebService\AppsWebService\AppsWebService.csproj : error NU1102:   - Found 0 version(s) in Microsoft Visual Studio Offline Packages
C:\GitRepos\Backend\AppsWebService\AppsWebService\AppsWebService.csproj : error NU1102: Unable to find package System.Text.Encodings.Web with version (>= 4.5.0-rtm-26502-02)
C:\GitRepos\Backend\AppsWebService\AppsWebService\AppsWebService.csproj : error NU1102:   - Found 34 version(s) in aspnetcoredev [ Nearest version: 4.5.0-preview2-26308-02 ]
C:\GitRepos\Backend\AppsWebService\AppsWebService\AppsWebService.csproj : error NU1102:   - Found 13 version(s) in nuget.org [ Nearest version: 4.5.0-preview2-26406-04 ]
C:\GitRepos\Backend\AppsWebService\AppsWebService\AppsWebService.csproj : error NU1102:   - Found 0 version(s) in Microsoft Visual Studio Offline Packages
C:\GitRepos\Backend\AppsWebService\AppsWebService\AppsWebService.csproj : error NU1102: Unable to find package System.Memory with version (>= 4.5.0-rtm-26502-02)
C:\GitRepos\Backend\AppsWebService\AppsWebService\AppsWebService.csproj : error NU1102:   - Found 38 version(s) in aspnetcoredev [ Nearest version: 4.5.0-preview2-26308-02 ]
C:\GitRepos\Backend\AppsWebService\AppsWebService\AppsWebService.csproj : error NU1102:   - Found 4 version(s) in nuget.org [ Nearest version: 4.5.0-preview2-26406-04 ]
C:\GitRepos\Backend\AppsWebService\AppsWebService\AppsWebService.csproj : error NU1102:   - Found 0 version(s) in Microsoft Visual Studio Offline Packages
C:\GitRepos\Backend\AppsWebService\AppsWebService\AppsWebService.csproj : error NU1102: Unable to find package System.Runtime.CompilerServices.Unsafe with version (>= 4.5.0-rtm-26502-02)
C:\GitRepos\Backend\AppsWebService\AppsWebService\AppsWebService.csproj : error NU1102:   - Found 40 version(s) in aspnetcoredev [ Nearest version: 4.5.0-preview2-26308-02 ]
C:\GitRepos\Backend\AppsWebService\AppsWebService\AppsWebService.csproj : error NU1102:   - Found 9 version(s) in nuget.org [ Nearest version: 4.5.0-preview2-26406-04 ]
C:\GitRepos\Backend\AppsWebService\AppsWebService\AppsWebService.csproj : error NU1102:   - Found 0 version(s) in Microsoft Visual Studio Offline Packages
C:\GitRepos\Backend\AppsWebService\AppsWebService\AppsWebService.csproj : error NU1107: Version conflict detected for Microsoft.AspNetCore.Authentication.Abstractions. Reference the package directly from the project to resolve this issue.
C:\GitRepos\Backend\AppsWebService\AppsWebService\AppsWebService.csproj : error NU1107:  AppsWebService -> Microsoft.AspNetCore.SignalR 1.0.0-rtm-30733 -> Microsoft.AspNetCore.Http.Connections 1.0.0-rtm-30733 -> Microsoft.AspNetCore.Authorization.Policy 2.1.0-rtm-30733 -> Microsoft.AspNetCore.Authentication.Abstractions (>= 2.1.0-rtm-30733)
C:\GitRepos\Backend\AppsWebService\AppsWebService\AppsWebService.csproj : error NU1107:  AppsWebService -> Microsoft.AspNetCore.App 2.1.0-preview2-final -> Microsoft.AspNetCore.Authentication.Abstractions (= 2.1.0-preview2-final).

The build failed. Please fix the build errors and run again.
```
i also tried adding the entire framework package latest build and i receive the same errors.

does someone knows why?

**Comment by guylando** [comment] 2018-05-06 11:13
Is this exception also related to this issue:

`
dbug: Microsoft.AspNetCore.SignalR.HubConnectionContext[6]
      Failed writing message.
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.ThrowHelper.ThrowIndexOutOfRangeException()
   at Microsoft.AspNetCore.SignalR.Internal.Protocol.Utf8BufferTextWriter.Write(Char value)
   at Newtonsoft.Json.JsonTextWriter.WritePropertyName(String name, Boolean escape)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Microsoft.AspNetCore.SignalR.Internal.Protocol.JsonHubProtocol.WriteArguments(Object[] arguments, JsonTextWriter writer)
   at Microsoft.AspNetCore.SignalR.Internal.Protocol.JsonHubProtocol.WriteMessageCore(HubMessage message, IBufferWriter`1 stream)
   at Microsoft.AspNetCore.SignalR.Internal.Protocol.JsonHubProtocol.WriteMessage(HubMessage message, IBufferWriter`1 output)
   at Microsoft.AspNetCore.SignalR.Internal.Protocol.HubProtocolExtensions.WriteToArray(IHubProtocol hubProtocol, HubMessage message)
   at Microsoft.AspNetCore.SignalR.Internal.Protocol.HubMessage.WriteMessage(IHubProtocol protocol)
   at Microsoft.AspNetCore.SignalR.HubConnectionContext.WriteCore(HubMessage message)
`

**Comment by yosigolan** [comment] 2018-05-06 19:34
hey @guylando 
how did you manged to build the project with rtm-30733? when i try even with new empty project i get many build errors saying i am missing .net packages of version 4.5.0.
what are the steps you did?
Thanks

**Comment by guylando** [comment] 2018-05-06 19:36
you need to close visual studio and change the csproj files using notepad++ and then run dotnet restore from elevated cmd

**Comment by yosigolan** [comment] 2018-05-06 19:41
@guylando thank you. i will try it

**Comment by davidfowl** [comment] 2018-05-06 20:26
You don't need to do any of that. You need to add the dotnet-core feed and you also need to update everything else to use the rtm package of the same version. If you show your csproj, I can help.

**Comment by guylando** [comment] 2018-05-06 21:26
When installing one library using visual studio package manager it fails and reverts. What I ment is to change ALL packages versions to compatible new version by changing csproj with visual studio closed (if not closed then visual studio attempts to restore in the middle..) and then using cmd dotnet restore is much faster to see if there are any problems than using visual studio (at least for my 30+ projects solution)

**Comment by yosigolan** [comment] 2018-05-07 07:35
@davidfowl ok i got it, i added the dotnet-core feed in addition to the aspnetcore-dev feed and now it works.
Thanks

**Comment by yosigolan** [comment] 2018-05-07 07:38
now i get this:
```
It was not possible to find any compatible framework version
The specified framework 'Microsoft.AspNetCore.App', version '2.1.0-rtm-30733' was not found.
  - Check application dependencies and target a framework version installed at:
      C:\Program Files\dotnet\
  - Installing .NET Core prerequisites might help resolve this problem:
      http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
  - The .NET Core framework and SDK can be installed from:
      https://aka.ms/dotnet-download
  - The following versions are installed:
      2.1.0-preview2-final at [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
```
what am i doing wrong?

**Comment by davidfowl** [comment] 2018-05-07 08:12
Try setting this in your csproj:

```xml
<MicrosoftNETPlatformLibrary>Microsoft.NETCore.App</MicrosoftNETPlatformLibrary>
```

**Comment by yosigolan** [comment] 2018-05-07 08:17
same result...
i added it under the ```<PropertyGroup>``` is that what you meant?
maybe i need to install the 30733 sdk?

**Comment by guylando** [comment] 2018-05-07 09:56
I dont have any special sdk. You probably did not configure the right stream in your nugget config. Show your solution nugget config.

**Comment by yosigolan** [comment] 2018-05-07 10:02
here it is:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="NuGet" value="https://api.nuget.org/v3/index.json" />
    <add key="aspnetcore-dev" value="https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json" />
	<add key="netcore-dev" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />
  </packageSources>
</configuration>
```
can you show your csproj file?

**Comment by yosigolan** [comment] 2018-05-07 10:27
no... same error. did you used the entire app package ``` <PackageReference Include="Microsoft.AspNetCore.App" Version="2.1.0-rtm-30733" />``` or took specific packages?

**Comment by guylando** [comment] 2018-05-07 10:37
specific packages.
check in the myget gallery if the package you want exist with that version.

**Comment by yosigolan** [comment] 2018-05-07 10:39
i want the signalr off-course :-) which packages did you added to get it?

**Comment by guylando** [comment] 2018-05-07 10:41
I meant check which versions of Microsoft.AspNetCore.App exist in the gallery of the stream

**Comment by yosigolan** [comment] 2018-05-08 08:39
Hey @anurse , @davidfowl 
finally with the release of rc1 i succeeded to use the new bits with your fix. however the exception is still thrown...
```
System.ArgumentException: The output byte buffer is too small to contain the encoded data, encoding 'Unicode (UTF-8)' fallback 'System.Text.EncoderReplacementFallback'.
Parameter name: bytes
   at System.Text.Encoding.ThrowBytesOverflow()
   at System.Text.Encoding.ThrowBytesOverflow(EncoderNLS encoder, Boolean nothingEncoded)
   at System.Text.UTF8Encoding.GetBytes(Char* chars, Int32 charCount, Byte* bytes, Int32 byteCount, EncoderNLS baseEncoder)
   at System.Text.EncoderNLS.Convert(Char* chars, Int32 charCount, Byte* bytes, Int32 byteCount, Boolean flush, Int32& charsUsed, Int32& bytesUsed, Boolean& completed)
   at Microsoft.AspNetCore.Internal.Utf8BufferTextWriter.WriteInternal(ReadOnlySpan`1 buffer)
   at Microsoft.AspNetCore.Internal.Utf8BufferTextWriter.Write(Char[] buffer, Int32 index, Int32 count)
   at Newtonsoft.Json.Utilities.JavaScriptUtils.WriteEscapedJavaScriptString(TextWriter writer, String s, Char delimiter, Boolean appendDelimiters, Boolean[] charEscapeFlags, StringEscapeHandling stringEscapeHandling, IArrayPool`1 bufferPool, Char[]& writeBuffer)
   at Newtonsoft.Json.JsonTextWriter.WriteEscapedString(String value, Boolean quote)
   at Newtonsoft.Json.JsonTextWriter.WriteValue(String value)
   at Newtonsoft.Json.JsonWriter.WriteValue(JsonWriter writer, PrimitiveTypeCode typeCode, Object value)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializePrimitive(JsonWriter writer, Object value, JsonPrimitiveContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Serialize(JsonWriter jsonWriter, Object value)
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.WriteArguments(Object[] arguments, JsonTextWriter writer)
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.WriteInvocationMessage(InvocationMessage message, JsonTextWriter writer)
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.WriteMessageCore(HubMessage message, IBufferWriter`1 stream)
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.WriteMessage(HubMessage message, IBufferWriter`1 output)
   at Microsoft.AspNetCore.SignalR.HubConnectionContext.WriteCore(HubMessage message)
```

It looks a bit different now (the stack trace) but it still happens especially when i use data with other languages than English (Hebrew for example).
In addition, things are now even worth since when the exception is thrown in the server, another exception is thrown in the client:
```
SyntaxError: Unexpected token t in JSON at position 19781
    at JSON.parse (<anonymous>)
    at JsonHubProtocol.parseMessages (webpack-internal:///./node_modules/@aspnet/signalr/dist/esm/JsonHubProtocol.js:32:38)
    at HubConnection.processIncomingData (webpack-internal:///./node_modules/@aspnet/signalr/dist/esm/HubConnection.js:237:42)
    at WebSocketTransport.HubConnection.connection.onreceive (webpack-internal:///./node_modules/@aspnet/signalr/dist/esm/HubConnection.js:57:68)
    at WebSocket.webSocket.onmessage [as __zone_symbol__ON_PROPERTYmessage] (webpack-internal:///./node_modules/@aspnet/signalr/dist/esm/WebSocketTransport.js:88:47)
    at WebSocket.wrapFn (webpack-internal:///./node_modules/zone.js/dist/zone.js:1166:39)
    at ZoneDelegate.invokeTask (webpack-internal:///./node_modules/zone.js/dist/zone.js:421:31)
    at Object.onInvokeTask (webpack-internal:///./node_modules/@angular/core/esm5/core.js:4956:33)
    at ZoneDelegate.invokeTask (webpack-internal:///./node_modules/zone.js/dist/zone.js:420:36)
    at Zone.runTask (webpack-internal:///./node_modules/zone.js/dist/zone.js:188:47)
  defaultErrorLogger	
  ErrorHandler.handleError	
  next	
  schedulerFn	
  SafeSubscriber.__tryOrUnsub	
  SafeSubscriber.next	
  Subscriber._next	
  Subscriber.next	
  Subject.next	
  EventEmitter.emit	
  (anonymous function)	
  ZoneDelegate.invoke	
  Zone.run	
  NgZone.runOutsideAngular	
  onHandleError	
  ZoneDelegate.handleError	
  Zone.runTask	
  ZoneTask.invokeTask	
  invokeTask	
  globalZoneAwareCallback	
```
This exception kills the signalr in the client side...
Before your fix there was no exception in the client, only the message never arrived.

I am attaching a file with the data i am trying to pass on the wire. you can try pass it as string, in my system the exception also happens when doing so.
[data.txt](https://github.com/aspnet/SignalR/files/1983003/data.txt)

I am using the the build 2.1.0-rtm-30740 with the metapackage Microsoft.AspNetCore.App. to overcome the execution problem (see above), i duplicated the rc1 run-time folder into a folder with this build name (under C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App). 
Since this is kind of a workaround please confirm that this is not what caused the issue on my system.

Yosi

**Comment by yosigolan** [comment] 2018-05-08 08:53
I just made a test with build 2.1.0-rtm-30733 and in this build the exception i mentioned in the client is not thrown (the exception of the server still does with the new stack trace).

**Comment by anurse** [comment] 2018-05-08 16:38
> to overcome the execution problem (see above), i duplicated the rc1 run-time folder into a folder with this build name (under C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App)

This means you are **not** using the RTM bits, you have replaced the RTM bits with RC1 bits. The framework assemblies in the `C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App` folder are the bits work at runtime.

**Comment by anurse** [comment] 2018-05-08 16:40
You can find the RTM nightly builds here: https://github.com/dotnet/versions/tree/master/build-info/dotnet/product/cli/release/2.1

Installing the SDK installer from that page should give you the `2.1.0-rtm-30740` build of `Microsoft.AspNetCore.App`

**Comment by yosigolan** [comment] 2018-05-09 08:11
Thanks @anurse , exactly what i was missing. it works great now!
