### ISSUE TITLE
asp.net-core-signalr can't stay connected for more than a minute or so

### ISSUE THREAD

**Issue by stephenweaver** [aspnet/SignalR#2150] opened 2018-04-26 14:11 UTC
Just upgraded our app service from .net 4.6 to .net core. Part of that migration was to upgrade to the new .net core version of SignalR. Everything was working fine while running locally, but when it was published to an azure app service, the connection doesn't stay connected for more than a minute (usually less than 30 seconds). The error that I'm seeing in the console logs is:

Error: Connection disconnected with error 'Error: Websocket closed with status code: 1006 ()'.

Has anyone else experienced this before? I ran across this post, but it has very little feedback. Not sure if it has the same root cause or not.

### Please include as much of the following as you can in your bug report

* Versions of Server-Side NuGet Packages: **1.0.0-preview2-final**
* Versions of Client-Side NuGet/NPM Packages:  **@aspnet/signalr: 1.0.0-preview2-final**
* Are you using the C# client or the JavaScript client: **javascript client**
* The Server you are using (Kestrel/HttpSysServer/IIS/IIS Express/Azure Web App/etc.): **Azure App Service**
* The Operating System on the Server (Windows/Linux/macOS): **I'm assuming windows** 
* The Operating System on the Client (Windows/Linux/macOS): **Running the site on a mac and pc.** 
* The Browser on the client, if using the JavaScript client (IE/Chrome/Edge/Firefox/etc.): **Happening on both Chrome and Firefox (only browsers i tested)**
* If possible, please collect Network Traces and attach them (please do not post them inline, use a service like [Gist](https://gist.github.com) to upload them and link them in the issue)
   * For either client you can use a tool such as [Fiddler](https://www.telerik.com/fiddler) for this
   * Many browsers allow you to capture Network Traces from their Dev Tools. See sample instructions for Chrome: https://support.zendesk.com/hc/en-us/articles/204410413-Generating-a-HAR-file-for-troubleshooting
* If possible, please collect logs from the client: **Added trace logs and there was nothing there other than 1006 error.**
* If possible, please collect logs from the server: **Nothing notable that i could find in the logs**

When in doubt, feel free to file the issue, we're happy to help answer questions. We also suggest using the `asp.net-core-signalr` tag on StackOverflow to ask questions:
**Also posted this question there with that tag.**

**Comment by davidfowl** [comment] 2018-04-26 14:46
Can you capture the network trace as described above?

**Comment by stephenweaver** [comment] 2018-04-26 15:53
Here is the .har file: https://gist.github.com/stephenweaver/678ed096ff9bd83f47203827f8efbd7b

**Comment by stephenweaver** [comment] 2018-04-26 19:47
Thanks, @anurse! Just sent an email.

**Comment by stephenweaver** [comment] 2018-04-27 13:39
To the best of my knowledge these are the relevant logs.

Server log: 
```
2018-04-26 20:32:36.934 +00:00 [Debug] Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport: Waiting for the application to finish sending data.
2018-04-26 20:32:36.934 +00:00 [Debug] Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport: Socket closed.
2018-04-26 20:32:37.069 +00:00 [Error] Microsoft.AspNetCore.SignalR.HubConnectionHandler: Error when processing requests.
System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake. ---> Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Unexpected end of request content.
   at Microsoft.AspNetCore.Server.Kestrel.Internal.System.IO.Pipelines.PipeCompletion.ThrowFailed()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.System.IO.Pipelines.Pipe.GetResult(ReadResult& result)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.System.IO.Pipelines.Pipe.Microsoft.AspNetCore.Server.Kestrel.Internal.System.IO.Pipelines.IReadableBufferAwaiter.GetResult()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.System.IO.Pipelines.ReadableBufferAwaitable.GetResult()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.MessageBody.<ReadAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.FrameRequestStream.<ReadAsyncInternal>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.WebSockets.ManagedWebSocket.<EnsureBufferContainsAsync>d__71.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.WebSockets.ManagedWebSocket.<ReceiveAsyncPrivate>d__61`2.MoveNext()
   at System.Net.WebSockets.ManagedWebSocket.<ReceiveAsyncPrivate>d__61`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport.<StartReceiving>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at System.IO.Pipelines.Pipe.DefaultPipeReader.GetResult(Int16 token)
   at Microsoft.AspNetCore.SignalR.HubConnectionHandler`1.<DispatchMessagesAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.HubConnectionHandler`1.<RunHubAsync>d__11.MoveNext()
2018-04-26 20:32:37.172 +00:00 [Debug] Microsoft.AspNetCore.SignalR.HubConnectionContext: Failed writing message.
System.InvalidOperationException: Writing is not allowed after writer was completed.
   at System.IO.Pipelines.ThrowHelper.ThrowInvalidOperationException_NoWritingAllowed()
   at System.IO.Pipelines.Pipe.GetMemory(Int32 sizeHint)
   at System.IO.Pipelines.Pipe.DefaultPipeWriter.GetSpan(Int32 sizeHint)
   at System.Buffers.BuffersExtensions.Write[T](IBufferWriter`1 writer, ReadOnlySpan`1 value)
   at Microsoft.AspNetCore.SignalR.HubConnectionContext.WriteCore(HubMessage message)
2018-04-26 20:32:37.193 +00:00 [Debug] Microsoft.AspNetCore.Http.Connections.HttpConnectionManager: Removing connection enTVWnnRufLx4kHW9GWgbw from the list of connections.
```

Fiddler Client Log
```
09:32:41:3167 [WebSocket #18] Read from Server failed... Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.
09:32:41:3167 [WebSocket #18] Read from Client failed... Object reference not set to an instance of an object.
```

**Comment by rushi216** [comment] 2018-05-30 11:58
I had the same issue, but when I opened my site in https (Signalr via wss) it worked fine

**Comment by codecadwallader** [comment] 2018-06-01 11:16
@rushi216 Interesting, thanks for adding that detail.  I work with Stephen (OP) and we are using https/wss and still encounter the issue.  We have only been able to reproduce it at scale and in Azure, and our working theory was that it was the Azure load balancer breaking the connections.  We switched from having multiple hubs to a single hub and that helped mitigate (but not resolve) the issue which helped support that conclusion.  We're looking forward to testing the upcoming (ASP).NET Core 2.1 with its new socket implementation as it rolls out into Azure to see if that helps further.

**Comment by anurse** [comment] 2018-06-01 16:10
> We switched from having multiple hubs to a single hub and that helped mitigate (but not resolve) the issue

Hrm, this is very interesting. Browsers do have low concurrent connection limits that can affect the number of outstanding HTTP requests you can have, which would affect Long Polling or Server-Sent Events connections. You're generally limited to about 6 concurrent connections to the same domain. However, WebSockets have different limits that are usually much higher (30 per domain in Chrome, for example).

I do wonder if you're seeing a concurrent connection limit somewhere in between. Azure App Service has historically had problems with high numbers of concurrent connections (but we're talking in the 1000s). This was one of many motivating factors for the [Azure SignalR Service](https://azure.microsoft.com/en-us/blog/azure-signalr-service-a-fully-managed-service-to-add-real-time-functionality/) since that service mitigates concurrent connection issues because the clients connect directly to the service, not to your application servers.

**Comment by anurse** [comment] 2018-06-10 22:20
This issue has gone quiet for a bit but I want to make sure it doesn't get lost in the backlog. @stephenweaver @codecadwallader is there something that still needs to be investigated on our end here? If I remember correctly the issue appeared to be caused by a proxy terminating the connection, were you able to get any more information out of Azure support? The fact that reducing the number of hubs fixed your issue does point the finger towards some kind of concurrent connection count issue. Does the issue only occur under load or does it occur when there is only a small number of clients as well?

**Comment by codecadwallader** [comment] 2018-06-11 11:20
@anurse Thanks for being thorough and following up on it, I really appreciate that.  We did switch to ASP.NET Core v2.1 last week as planned and unfortunately it seemed to only make the issue occur more frequently.  The issue definitely does appear to be load related as we're unable to reproduce it locally, and it's harder to reproduce in Azure staging environments where the load is significantly less.

We did go through Azure support for a couple weeks but did not make any meaningful progress with them.  We asked repeatedly to get access to someone on the load balancer team or someone with access to load balancer logs but they kept insisting it had to be an application issue or SignalR issue.  We let the ticket close since we were at a dead-end with that engineer, but have considered opening a new case.  If there's any way we could get you or someone from your team tagged into that case, that would be extremely helpful.  Perhaps I am using the wrong lingo/terminology and that is making the support path more difficult.

**Comment by anurse** [comment] 2018-06-11 15:24
> The issue definitely does appear to be load related as we're unable to reproduce it locally

Do you know how many concurrent connections you have when you are under load and the issue occurs? I believe you can get information like this from Application Insights (just looking for concurrent HTTP connections is sufficient), or you can estimate based on the number of concurrent users multiplied by the number of Hubs on each page (since each individual Hub is a separate connection). Azure App Service has some pretty severe concurrent connection limits and when you hit them, connections are terminated abruptly like this.

App Service is generally not a suitable infrastructure to host services with high numbers of concurrent connections for that reason. If you're hitting those limits you'd either need to move to Azure VMs/Azure Kubernetes **or** provision an Azure SignalR Service instance, since that takes the concurrent connection load off of your app servers and moves it to the Service (which is designed for many concurrent connections). The quickest way to identify if that will solve your issue would be to provision an Azure SignalR Service, set it up, and see if the issue goes away. If that resolves the issue, you can either keep the service or look at migrating to Azure VMs or Azure Kubernetes which does not have the concurrent connection limitation.

**Comment by stephenweaver** [comment] 2018-06-12 17:20
@anurse Over the past 7 days, we've had a pretty constant 400 to 500 connections. You mentioned above (on June 1st) that historically there have been issues when we get into the 1000s. Before we try setting up a SignlaR Service, do you think that we should be having these issues with the few hundred connections that we have? As a reminder, we only started seeing this issue after we migrated to .Net Core. Prior to the upgrade, we had a similar average number of connections. 

![image](https://user-images.githubusercontent.com/5230027/41305894-52171816-6e42-11e8-871a-8ec07bed16e9.png)

**Comment by anurse** [comment] 2018-06-12 19:12
How did you end up collecting that concurrent connection count? I don't think I'd expect 400-500 connections to cause this problem, but I don't have specifics on the limits. 

> we only started seeing this issue after we migrated to .Net Core

One of the key differences in ASP.NET Core SignalR is that each Hub requires a separate connection, whereas in ASP.NET SignalR all Hub traffic shared a single connection. That's what makes me suspect concurrent connection issues on the front-end. We've got test scenarios with much higher connection counts that don't encounter these issues, so it seems like there must be something in the environment causing problems.

Regardless of what is causing the concurrent connection counts, moving to the SignalR Service _should_ relieve this issue since it is the one handling the concurrent connections. Having said that, I don't want to just suggest you patch over the issue using a different service, so I'd like to try and continue getting to the bottom of this :).

**Comment by stephenweaver** [comment] 2018-06-12 20:39
@anurse I found a metric in Application Insights called connections. It's a little bit unclear exactly what connections it's measuring, but it would make sense that this metric would include signalr connections. Based off the user data that we collect, we're seeing about 1800 unique users per day. So it does does reasonable that we're averaging 400 to 500 active connections.

**Comment by los93sol** [comment] 2018-06-17 03:07
I was able to repro a similar scenario in a very small docker environment just placing an Nginx proxy container in front of the web app.  Just throwing it out there since it’s quick to setup and reliably repro almost identical behavior so thought it might help.

**Comment by davidfowl** [comment] 2018-06-17 03:15
@los93sol in the past when people have complained about that behavior with nginx it’s because they haven’t set up the proxy time out appropriately. Search for nginx and websockets.

**Comment by los93sol** [comment] 2018-06-17 03:20
@davidfowl Thanks for the point on that one!

**Comment by stephenweaver** [comment] 2018-06-19 22:27
Thanks, @anurse.  Today spent some time getting up and running with the Azure SignalR Service, but ran into what I think is this issue: https://github.com/Azure/azure-signalr/issues/124. (I don't want to mix the threads, just wanted send an update on the progress.)

**Comment by anurse** [comment] 2018-06-20 19:47
@stephenweaver What tier are you running on Azure Web Apps (S1, S2, S3, etc...) and how many instances?

**Comment by codecadwallader** [comment] 2018-06-21 11:06
@anurse it's S3 with the maximum 10 instances.

**Comment by anurse** [comment] 2018-07-05 21:13
After some further investigation it looks like there are pretty severe concurrent connection limits on Azure App Service. I'm going to close this issue now as I don't think there's a lot we can do here.

If you're still seeing issues with the Azure SignalR Service, feel free to tag me in issues. And of course, if there are other issues with the SignalR library blocking you, feel free to file new bugs.

**Closed by anurse** 2018-07-05 21:13 UTC
Labels: investigate

**Comment by stephenweaver** [comment] 2018-07-06 13:10
Thanks @anurse, we ended up just ripping SignalR out of our app completely.  I appreciate your help investigating.

Is there an issue that I can follow on the concurrent connection limits on Azure App Service? I can see that being a problem for us in other areas.

**Comment by davidfowl** [comment] 2018-07-06 16:13
> Thanks @anurse, we ended up just ripping SignalR out of our app completely. I appreciate your help investigating.

😢 Thanks for the patience! Out of curiosity did you just drop websockets completely?

> Is there an issue that I can follow on the concurrent connection limits on Azure App Service? I can see that potentially being a problem for us in other areas.

https://docs.microsoft.com/en-us/azure/azure-subscription-service-limits#app-service-limits

**Comment by codecadwallader** [comment] 2018-07-06 18:06
@davidfowl Yes, we did go away from WebSockets altogether and replace it with HTTP/2 calls only which the client is responsible for fully driving.  Another argument in favor of the switch was that it's a lot easier to track HTTP with Application Insights as well as other tools (e.g. Postman).

> https://docs.microsoft.com/en-us/azure/azure-subscription-service-limits#app-service-limits

Thanks for the link.  We have standard instances which indicate unlimited "Web Sockets per instance".  Is that the metric/connection limit being referred to but for a lower tier?

We do really appreciate the support that was given, wish you guys the best of luck.
