### ISSUE TITLE
Options not being sent to HttpClient

### ISSUE THREAD

**Issue by AustinFelipe** [aspnet/SignalR#1059] opened 2017-10-26 20:25 UTC
Hey guys, looking at the code I found this method not sending ```this.options``` as a second parameter, which prevents to send some useful information at the http header, am I wrong?

https://github.com/aspnet/SignalR/blob/eec6b4f2f598a72eeed7de9f309d2a241a81fe2e/client-ts/Microsoft.AspNetCore.SignalR.Client.TS/HttpConnection.ts#L62

It should be something like 
``` javascript
let negotiatePayload = yield this.httpClient.options(this.url, this.options);
```

Or getting just the header section
``` javascript
let negotiatePayload = yield this.httpClient.options(this.url, this.options.header);
```

Does it make any sense?

**Comment by moozzyk** [comment] 2017-10-26 21:19
This is a duplicate of #680. I also don't think this as useful as it looks like - for instance when selecting the WebSockets transport HttpClient won't be used at all because the OPTIONS request is not sent.

**Comment by AustinFelipe** [comment] 2017-10-27 13:53
Got it. Is there any options for send cookies through WebSocket method?

**Comment by moozzyk** [comment] 2017-10-30 17:41
I don't think it is possible. Again, this is a limitation of the API.

**Comment by moozzyk** [comment] 2017-11-01 17:20
Closing as a duplication of #680.

**Closed by moozzyk** 2017-11-01 17:20 UTC
