### ISSUE TITLE
Flaky Test: ServerSentEventsTransportTests.SSETransportStopsSendAndReceiveLoopsWhenTransportStopped

### ISSUE THREAD

**Issue by jkotalik** [aspnet/SignalR#928] opened 2017-09-22 01:37 UTC
Stack trace:

```
Failed   Microsoft.AspNetCore.SignalR.Client.Tests.ServerSentEventsTransportTests.SSETransportStopsSendAndReceiveLoopsWhenTransportStopped
Error Message:
 System.TimeoutException : Operation in SSETransportStopsSendAndReceiveLoopsWhenTransportStopped timed out at /Users/travis/build/aspnet/SignalR/test/Microsoft.AspNetCore.SignalR.Client.Tests/ServerSentEventsTransportTests.cs:117
Stack Trace:
   at Microsoft.AspNetCore.SignalR.Tests.Common.TaskExtensions.<OrTimeout>d__2.MoveNext() in /Users/travis/build/aspnet/SignalR/test/Common/TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.Client.Tests.ServerSentEventsTransportTests.<SSETransportStopsSendAndReceiveLoopsWhenTransportStopped>d__1.MoveNext() in /Users/travis/build/aspnet/SignalR/test/Microsoft.AspNetCore.SignalR.Client.Tests/ServerSentEventsTransportTests.cs:line 117
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by moozzyk** [comment] 2017-09-22 03:32
Looks like a dupe of #526. There is a [PR](https://github.com/aspnet/SignalR/pull/694) out for this. @BrennanConroy - did we need a new runtime for this?

**Comment by BrennanConroy** [comment] 2017-09-22 03:59
Yeah, new runtime and new corefxlab
________________________________

**Comment by moozzyk** [comment] 2017-09-22 04:06
Closing as a duplicate then. We will merge the PR while we required dependencies.

**Closed by moozzyk** 2017-09-22 04:06 UTC

**Comment by jkotalik** [comment] 2017-09-22 04:46
Sorry, didn't see the other PR. 😄

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by moozzyk** [comment] 2017-09-22 05:24
No worries.
