### ISSUE TITLE
New Version of Xamarin Android cause System.Memory problem.

### ISSUE THREAD

**Issue by patsadow2** [aspnet/SignalR#2208] opened 2018-05-06 05:13 UTC
Is there anyone in Microsoft who will fix it ? 🥇

**Comment by davidfowl** [comment] 2018-05-06 05:33
Closing as duplicate of https://github.com/aspnet/SignalR/issues/1886. The issues should be fixed in VS 15.7

**Closed by davidfowl** 2018-05-06 05:33 UTC

**Comment by patsadow2** [comment] 2018-05-06 16:12
![image](https://user-images.githubusercontent.com/19226186/39675279-0bae008e-5159-11e8-8efd-caa5bfbfb76f.png)
 Still the same story, new Xamarin.Form project.

**Comment by AwsomeCode** [comment] 2018-05-06 16:29
@patsadow2 Current preview of vs 15.7 has Mono version 5.10 and this fix requires 5.12 so you have to wait until that released.

**Comment by patsadow2** [comment] 2018-05-21 17:26
Any news ? When the newest version is comming up ?
