### ISSUE TITLE
Use MessagePackProtocol to Send Class, But is null

### ISSUE THREAD

**Issue by Hamielkuo** [aspnet/SignalR#1646] opened 2018-03-19 11:21 UTC
I send some message with class ,but server Receive is empty, 
null =>
![image](https://user-images.githubusercontent.com/4577265/37592754-a460af2c-2baa-11e8-8168-a4912704b395.png)

![image](https://user-images.githubusercontent.com/4577265/37592778-baaeb1de-2baa-11e8-999b-cee100a7dac3.png)

My program is as follows, have any problem?

client Site Code:
![image](https://user-images.githubusercontent.com/4577265/37592709-7d856ba4-2baa-11e8-8374-b0fafcd19dc5.png)

server side code:
![image](https://user-images.githubusercontent.com/4577265/37592606-287edc1c-2baa-11e8-9d27-60c80cb1cd54.png)

hub:
![image](https://user-images.githubusercontent.com/4577265/37592617-3496d018-2baa-11e8-93b3-a7b93bc69464.png)

Class:
![image](https://user-images.githubusercontent.com/4577265/37592626-3acd801c-2baa-11e8-921f-10ea0af56aa6.png)

**Comment by damienbod** [comment] 2018-03-19 15:03
Here's an example:

https://damienbod.com/2018/03/19/using-message-pack-with-asp-net-core-signalr/

**Comment by damienbod** [comment] 2018-03-19 17:25
@Hamielkuo  The LowerCamel config on the server causes the null problem. Use the default option an it should return something.

**Comment by anurse** [comment] 2018-03-19 17:46
Unfortunately, it seems the MessagePack "key transformers" are uni-directional, they only apply to outbound serialization not to inbound deserialization. We're going to be doing some work to evaluate this as we review our MsgPack support (see #1524).

**Comment by anurse** [comment] 2018-03-19 19:25
This is something we're tracking in #1524 so I'm going to close this as a duplicate of that. Feel free to continue commenting and we can review when we work on #1524. @damienbod 's workaround should work for now.

**Closed by anurse** 2018-03-19 19:25 UTC

**Comment by Hamielkuo** [comment] 2018-03-20 00:37
@damienbod , Thank you help ,  your plan solved my problem ^^

**Comment by Hamielkuo** [comment] 2018-03-20 00:38
@anurse  ok, thank you ^^
