### ISSUE TITLE
Client sends data to server, but does not receive

### ISSUE THREAD

**Issue by alexiordan** [aspnet/SignalR#2573] opened 2018-06-30 21:45 UTC
- AspNetCore.SignalR v. 1.0.0
- .NetClient
- 4G internet connection on Windows 10 IoT Core (10.0.17134.112)
- Server has the same version of SignalR - hosted on Azure

Cannot provide many details since I don't have any relevant logs nor I was debugging.

The server did not get called OnDisconnectAsync for that connection, however the client did not receive data. 
On the other hand, the server did receive data sent by the client.

Needless to say that during this period the client responded to pings and I also accesed other services on it (WEB interface for management).

Did anyone ever encountered such a behavior?

A restart of the process, resolved the issue.

**Comment by anurse** [comment] 2018-07-02 15:53
Without [logs/traces](https://github.com/aspnet/SignalR/wiki/Diagnostics-Guide), there isn't much we can suggest here. If you are able to reproduce the issue while logging is enabled, we could help more. I presume the connection was functioning at some point and then messages simply stopped being received?

**Comment by alexiordan** [comment] 2018-07-02 17:33
Andrew, ufortunately I have no logs. 
I see the link to the Diagnostics-Guide and I'll follow it.
I know it was a long shot but wanted to know if someone else hit a simillar issue. Maybe also having a reason.

I'll follow the guide for diagnostics and if happens again, hopefully I'll be back with more info.

**Comment by BrennanConroy** [comment] 2018-07-02 17:41
If you published the app multiple times and your browser was running a cached version of the client that didn't have the correct callbacks setup that could explain why it was partially working.

**Comment by anurse** [comment] 2018-07-02 20:38
> I'll follow the guide for diagnostics and if happens again, hopefully I'll be back with more info.

Yeah, if you're able to gather any more information that would help. I'd definitely suggest getting some infrastructure set up to collect diagnostics for next time. I'm going to close this for now since there isn't really a lot we can do here with information, but feel free to comment further if you get more info and we can always look at re-opening the issue! Let us know if we can help you get the diagnostics running!

@BrennanConroy this is an IoT device using the .NET client so I don't think browser caching is the issue 😛

**Comment by alexiordan** [comment] 2018-07-02 20:44
Of course, thanks!

**Closed** 2018-07-02 20:44 UTC
Labels: investigate

**Comment by alexiordan** [comment] 2018-08-02 16:54
Happened again. 2 clients where somehow desynchronized from the server, whilst other 2 were OK.
I was publishing several times (3-4 times in a minute), and that could the cause.

Now I have logs. 

By taking a look at the Raw logs I can see when each client made the connections.I can see that those that are OK made some requests to connect while the others did not.
 
They all run the same code, and connection attempts are typically at the same time when publishing, except final publishings... (when error occured)

From SignalR logs it seems the server does not log when it sends messages, but only when receives.
Clients log when receive data. 

Desynchronized clients did not receive requests, while the OK ones received it.

What logs would be useful to you?

**Comment by anurse** [comment] 2018-08-02 18:11
> I was publishing several times (3-4 times in a minute), and that could the cause.

To be clear, the data loss occurs while you are publishing new versions of the **server** application? Publishing your application will cause it to restart and break all existing connections.

> I can see that those that are OK made some requests to connect while the others did not.

I don't fully understand what you're saying here. So some clients reconnect successfully after a publish but other clients do not? And the ones that do not, seem to be desynchronized (not receiving messages from the server)

**Comment by alexiordan** [comment] 2018-08-02 18:28
1. I detected the data loss after the final publish. I did not test between 1st and the 2nd, 2nd and 3rd etc. 

2. Yes, you got it right.

> So some clients reconnect successfully after a publish but other clients do not? And the ones that do not, seem to be desynchronized (not receiving messages from the server)

Desynchornized means that server receives data from them, but clients do not  get data from server.

And one more thing, the ones that do not reconnect are not failing to reconnect, they don't even try to reconnect.

**Comment by anurse** [comment] 2018-08-02 18:37
> the ones that do not reconnect are not failing to reconnect, they don't even try to reconnect.

This indicates that the problem isn't that they are failing to reconnect, it's that they believe they are still connected. If those clients were properly disconnected, then the reconnect would likely proceed.

Can you provide Trace-level logs from one of the clients that does not properly reconnect? Specifically around the time of the pubish that causes the desynchronization. It would also help to have server logs to from immediately before and after the publish.

The app is hosted in Azure Web Apps correct? What tools are you using to pubish (Azure CLI, Visual Studio, etc.) and what are the commands you are using to execute the publish? Are you using deployment slots?

**Comment by alexiordan** [comment] 2018-08-02 19:38
I've sent you log files via e-mail.
I publish from Visual Studio 15.7.5

- Publish method: Web Deploy

- Configuration: Release - x64

- Target Framework: netcoreapp2.1

- Deployment Mode: Self-Contained

- Target Runtime: win-x64

- Remove additional files at destination is UNCHECKED.

No, I don't use deployment slots.
