### ISSUE TITLE
Java Client: Add another method for specifying timeout for HubConnection

### ISSUE THREAD

**Issue by ezamelczykespeo** [aspnet/SignalR#3238] opened 2018-10-31 11:15 UTC
For now the only way to add handshakeResponseTimeout is to invoke method `HubConnectionBuilder#withHandshakeResponseTimeout(Duration)`. This is very limiting for Android developers since class `Duration` isn't available below api 26 of Android SDK.

Proposed solution would be to add overridden method `withHandshakeResponseTimeout(long, TimeUnit)`.

**Comment by BrennanConroy** [comment] 2018-10-31 15:39
Dupe of https://github.com/aspnet/SignalR/issues/3141

We've done some work to get the API level down since preview3. Take a look at https://github.com/aspnet/Docs/pull/9342

**Closed by BrennanConroy** 2018-10-31 15:39 UTC
