### ISSUE TITLE
Error during WebSocket handshake: Incorrect 'Sec-WebSocket-Accept' header value

### ISSUE THREAD

**Issue by tranphuongyd** [aspnet/SignalR#1585] opened 2018-03-13 15:09 UTC
I'm using the SignalR in .Net Core project (Microsoft.AspNetCore.SignalR -Version 1.0.0-alpha2-final).
It's work very well from 1 week ago. BUT today it's get the error: **WebSocket connection to 'mydomain' failed: Error during WebSocket handshake: Incorrect 'Sec-WebSocket-Accept' header value.**
![image](https://user-images.githubusercontent.com/7795756/37350209-c3fe3358-270a-11e8-971b-8b0e6d9e7745.png)

The browser is Chrome version 65.0.3325.146
With Fire Fox get another error like: 
**Firefox can’t establish a connection to the server at ws:MyDomain**

Can someone help me resolve it.
Thanks!

**Comment by anurse** [comment] 2018-03-13 17:26
Could you use the Network tab of your browser dev tools to capture the network traffic going on so we can take a look at what's happening? In Chrome, you can just right click anywhere in the Network tab's list of requests and choose 'Save as HAR with Content' and then upload that file and link it here (please don't paste it inline, it's very large, you can use a [gist](https://gist.github.com/) to host the content if you need to).

**Comment by tranphuongyd** [comment] 2018-03-14 14:40
Thanks @anurse ,
Please see in the attachment. 
[52.224.165.236.zip](https://github.com/aspnet/SignalR/files/1811569/52.224.165.236.zip)

**Comment by tranphuongyd** [comment] 2018-03-14 14:53
Hi @anurse ,
Just resolved it by install Websockets on IIS. Go to the Server Manager > Manage > Add Roles and Features > Web Server > Application Development > Websockets.

Many thanks!

**Comment by anurse** [comment] 2018-03-14 15:25
Ah, yes, I forgot to ask if you were running behind IIS, which does require installing the WebSockets feature. Glad it's resolved! Closing this issue now.

**Closed by anurse** 2018-03-14 15:25 UTC

**Comment by Polyterative** [comment] 2018-09-03 14:54
@tranphuongyd Fixed the problem, many thanks.
To anyone here having issues with Angular 6's change detection, SignalR's fallback might be the issue. 
Fixed my problems (messed up change detection/angular material events/rxjs  not working without additional action) after activating web sockets

**Comment by jjxtra** [comment] 2018-09-19 00:13
IIS appears to be changing the Sec-WebSocket-Key header value for some strange reason. Have confirmed this by logging the header to file. It is not the same one as the client sends. Any ideas?

**Comment by anurse** [comment] 2018-09-19 03:37
This is expected. Are you seeing an issue? When you are using ANCM, there are two separate WebSocket connections at play:

```
Browser <---> IIS ASP.NET Core Module <---> ASP.NET Core App
```

IIS is forwarding frames back and forth but these are separate WebSocket connections so the `Sec-WebSocket-Key` header will not be the same for these two connections.

**Comment by jjxtra** [comment] 2018-09-19 05:27
@anurse Unfortunately it looks like there is something fishy going on. I logged an issue: https://github.com/aspnet/Home/issues/3539

**Comment by anurse** [comment] 2018-09-19 18:06
Ok, it looks like this is an IIS issue. Looks like that issue has found it's way to the right place.

**Comment by klucero84** [comment] 2018-09-26 20:04
Hi I'm using signalr in an angular app and i'm getting this error in chrome. 
The handshake is working in edge so I'm sure it's not the IIS settings. 
This can be reproduced. 

https://chess-dev.kennethlucero.com
log in in edge with 
email: test_0@kennethlucero.com 
password: password 
and use the demo log-in on chrome. 
enter the same game in both browsers ex: https://chess-dev.kennethlucero.com/game/2/play
the edge browser joins the signal r group correctly but the chrome browser says: 
"Error during WebSocket handshake: Incorrect 'Sec-WebSocket-Accept' header value"

**Comment by gatapia** [comment] 2018-12-13 23:22
I'm getting this error now.  Angular 7 + .Net Core 2.1 + Microsoft.AspNetCore.SignalR 1.04.

This error does not happen when using the `dotnet run` server but when deploying to IIS (Windows 10 and Windows Server 2008 R2).

I'm assuming that its because win 10 IIS and Win Srv 2008 IIS (7.5) do not have WebSockets.  But isnt SignalR supposed to be smart enough to detect this and fallback?
