### ISSUE TITLE
Unable to compile an UWP app that use Microsoft.AspNetCore.SignalR.Client by .Net Native toolchain.

### ISSUE THREAD

**Issue by Lukespacewalker** [aspnet/SignalR#423] opened 2017-04-27 06:08 UTC
I have tried to use Microsoft.AspNetCore.SignalR.Client 1.0.0-preview2-24681 with a simple UWP app that just try to connect to SignalR Server running the Microsoft.AspNetCore.SignalR 1.0.0-preview2-24681 on ASP.NET Core.

The application is successfully compile by DEBUG mode but when I switch to RELEASE mode the compiler has encounter the error

**Internal compiler error: Object reference not set to an instance of an object.**	
	
Output of MSBuild

`.nuget\packages\microsoft.net.native.compiler\1.6.2\tools\Microsoft.NetNative.targets(691,5): error : Internal compiler error: Object reference not set to an instance of an object.`

The code of my UWP app. It uses Windows Creator Update SDK
```
    public sealed partial class MainPage : Page
    {
        public MainPage()
        {
            this.InitializeComponent();
            init();
        }

        private void init()
        {
            HubConnection connection = new HubConnection(new Uri("http://127.0.0.1:50164/message"));
            connection.StartAsync();
        }
    }
```

**Comment by moozzyk** [comment] 2017-04-27 17:25
On one side it resembles this: https://github.com/SignalR/SignalR/issues/3529. On the other hand, since we are targeting netstandard this should just work - might be a bug in tooling.

@Lukespacewalker - do you have any other version of VS installed or just VS2017?

**Comment by moozzyk** [comment] 2017-04-27 18:11
Thanks - we will need to look into it.

**Comment by moozzyk** [comment] 2017-05-16 22:35
I was able to repro this. The interesting thing is the warning before the internal compiler error which might be the culprit:
 
_...System.Threading.Tasks.Channels.dll" does not have a NeutralResourcesLanguageAttribute on it. To be used in an app package, portable libraries must define a NeutralResourcesLanguageAttribute ..._
```

1>------ Build started: Project: SignalRTest, Configuration: Release x86 ------
1>  SignalRTest -> C:\Users\pawelka\documents\visual studio 2017\Projects\SignalRTest\SignalRTest\bin\x86\Release\SignalRTest.exe
1>C:\Users\pawelka\.nuget\packages\System.Threading.Tasks.Channels\0.1.0-e170516-2\lib\netstandard1.3\System.Threading.Tasks.Channels.dll : warning MSB3817: The assembly "C:\Users\pawelka\.nuget\packages\System.Threading.Tasks.Channels\0.1.0-e170516-2\lib\netstandard1.3\System.Threading.Tasks.Channels.dll" does not have a NeutralResourcesLanguageAttribute on it. To be used in an app package, portable libraries must define a NeutralResourcesLanguageAttribute on their main assembly (ie, the one containing code, not a satellite assembly).
1>  Starting .NET Native compilation
1>  Processing application code
1>C:\Program Files (x86)\MSBuild\15.0\.Net\.NetNative\15.0.24211\x86\ilc\IlcInternals.targets(936,5): error : Internal compiler error: Object reference not set to an instance of an object.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

**Comment by moozzyk** [comment] 2017-05-16 22:53
https://github.com/dotnet/corefxlab/issues/1548

**Comment by muratg** [comment] 2017-06-12 19:34
This is external. Keeping this open to track https://github.com/dotnet/corefxlab/issues/1548.

**Comment by muratg** [comment] 2017-06-14 23:56
@moozzyk CoreFX issue is fixed. We can close this one once we verify the issue is gone.

**Comment by muratg** [comment] 2017-06-16 19:06
SignalR C# client is now .NETStandard2.0 which UWP doesn't currently support (it should be supported in a few months).   We'll verify this once UWP has the support.

**Comment by vulvulune** [comment] 2017-10-17 19:48
I've created a new UWP Project (target 10.0.16299.0), and just add the package **Microsoft.AspNetCore.SignalR.Common**.

And I have the error when I compile a release build:
`C:\Users\XXX\.nuget\packages\microsoft.net.native.compiler\2.0.0\tools\Microsoft.NetNative.targets(726,5): error : Internal compiler error: Object reference not set to an instance of an object.`

**Comment by moozzyk** [comment] 2017-10-18 16:25
Now, that UWP supports netstandard 2.0 we can look into this.

**Comment by vulvulune** [comment] 2017-10-19 09:34
It does not seem to be an issue in SignalR, but in the System.Buffers.Primitives package.

If I create a black UWP Project and just add the package **System.Buffers.Primitives**, I have the same issue.

This package is required because it is a dependency of System.Binary.

**Comment by moozzyk** [comment] 2017-10-19 15:18
@vulvulune - can you file a bug in the https://github.com/dotnet/corefxlab repo and link to this issue?

**Comment by muratg** [comment] 2017-11-30 21:04
No repro

**Closed by muratg** 2017-11-30 21:04 UTC
Labels: 1 - Ready, bug
