### ISSUE TITLE
Make RedisChannels prefix configurable

### ISSUE THREAD

**Issue by Vhab** [aspnet/SignalR#2947] opened 2018-09-12 12:46 UTC
Currently multiple independent SignalR Core scaleout deployments can't co-exist on the same Redis instance. (eg. deployments for multiple different customers using shared resources)
The old SignalR allowed this use-case by providing a unique eventKey in its scaleout configuration.

It would be nice to be able to configure a additional prefix for SignalR Core to use when generating redis key names.
It's currently hardcoded to use `typeof(THub).FullName` in `RedisHubLifetimeManager`.

**Comment by BrennanConroy** [comment] 2018-09-12 15:35
Dupe of https://github.com/aspnet/SignalR/issues/2671

**Closed by BrennanConroy** 2018-09-12 15:35 UTC
Labels: resolved: Duplicate
