### ISSUE TITLE
JsonSerializer exceptions not throwed

### ISSUE THREAD

**Issue by aleha84** [aspnet/SignalR#2576] opened 2018-07-02 10:13 UTC
Environment:
    .net core 2.1.1
    ASP.NET Core SignalR JavaScript Client version 1.0.0
    Kestrel server
    OS: Windows 10 Corporate
    Browser: chrome 65.0.3325.181

Steps to reproduce:

1. Take sample code from here: https://github.com/aspnet/Docs/tree/master/aspnetcore/tutorials/signalr/sample
2. Modify ChatHub.cs (add new classes and modyfy SendMessage code):
```
public class Test1
    {
        public Test2 Prop { get; set; }
    }

    public class Test2
    {
        public Test1 Prop { get; set; }
    }

public async Task SendMessage(string user, string message)
        {
            var t1 = new Test1();
            var t2 = new Test2();
            t2.Prop = t1;
            t1.Prop = t2; // creating reference loop
            await Clients.All.SendAsync("ReceiveMessage", user,message,  t1);
        }
```
3. Run app. Send message from page. In debug SendMessage invoked and `await Clients.All.SendAsync` called. But the client code does not receive anything.

No exception is thrown either in the backend or on the client

Workaround is to add in Startup.cs this code, but if you know about the problem: 
```
services.AddSignalR()
                .AddJsonProtocol(options =>
            {
                options.PayloadSerializerSettings.ReferenceLoopHandling = ReferenceLoopHandling.Ignore;
                options.PayloadSerializerSettings.PreserveReferencesHandling = PreserveReferencesHandling.None;
            });
```

**Comment by anurse** [comment] 2018-07-02 16:13
Are there any server logs indicating the problem? Could you collect detailed logs as described in the [Diagnostics Guide](https://github.com/aspnet/SignalR/wiki/Diagnostics-Guide) so we can see where the exception might be being dropped? In the meantime, we can look at the sample and see if we can reproduce the issue.

**Comment by anurse** [comment] 2018-07-02 16:18
I do know that a serialization error generally can't be sent to the client since we don't know that we'll be able to actually serialize the error properly if we weren't able to serialize the message. Also, since the message was partially serialized and SignalR writes directly to the output buffer to avoid further buffering/allocation, we don't know how much of the message has already been sent to the client so we terminate the connection.

The exception should definitely be logged by the server though, so I'm surprised you aren't seeing anything there.

**Comment by BrennanConroy** [comment] 2018-07-02 16:22
We actually don't abort the connection currently :(
https://github.com/aspnet/SignalR/issues/2257

**Comment by aleha84** [comment] 2018-07-04 08:55
By adding these 

lines to LogLevel property i saw Newtonsoft exception.
```
"Microsoft.AspNetCore.SignalR": "Debug",
"Microsoft.AspNetCore.Http.Connections": "Debug"
```
Here is logs:
[clientlogsUTF.txt](https://github.com/aspnet/SignalR/files/2162484/clientlogsUTF.txt)
[localhost.txt](https://github.com/aspnet/SignalR/files/2162486/localhost.txt)
[serverlogs.txt](https://github.com/aspnet/SignalR/files/2162460/serverlogs.txt)

**Comment by anurse** [comment] 2018-07-05 17:22
We're going to up the level of the message to Error and properly abort the connection as part of #2257 . Closing this issue now, since we're handling this in the other one.

**Closed by anurse** 2018-07-05 17:22 UTC
Labels: investigate
