### ISSUE TITLE
SSE handshake error when using IIS

### ISSUE THREAD

**Issue by FTWinston** [aspnet/SignalR#2954] opened 2018-09-13 11:16 UTC
* Using Microsoft.AspNetCore.SignalR 1.0.1 on .NET Core 2.1, with @aspnet/signalr 1.0.3.
* Javascript client, running in Chrome v68 & v69 on Windows 10.
* Hosting in IIS 8 on Windows Server 2012 R2

Using windows authentication and SSE, everything works fine when I run through IIS Express. But when I deploy a production build to IIS, I get this:
`Connection disconnected with error 'Error: Server returned handshake error: Handshake was canceled.'.`

My diagnostic logs are here: [server log](https://github.com/aspnet/SignalR/files/2379025/server.log.txt) & [client log](https://github.com/aspnet/SignalR/files/2379026/client.log.txt)

And here's my web.config - have I just missed setting something up here?

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
    </handlers>
    <aspNetCore processPath="dotnet" arguments=".\TestApp.dll" stdoutLogEnabled="true" stdoutLogFile=".\logs\stdout" requestTimeout="00:10:00" />
    <security>
      <authentication>
        <windowsAuthentication enabled="true" />
      </authentication>
    </security>
  </system.webServer>
</configuration>
```

I tried adding this, to no avail: `<urlCompression doDynamicCompression="false"/>`

Many thanks, and apologies if this is me just having missed something obvious.

**Comment by FTWinston** [comment] 2018-09-13 11:34
I should also clarify that this error happens after the 15 second timeout, not immediately.

**Comment by anurse** [comment] 2018-09-13 17:52
Hmm, from the server logs, it looks like the handshake send isn't arriving at the server until very late, causing the timeout. Would you be able to collect and attach a [Fiddler](https://www.telerik.com/fiddler) trace?

**Comment by FTWinston** [comment] 2018-09-14 15:58
@anurse Well I've tried, but when I have fiddler running, the connection works fine! When I close fiddler and try again, it fails. The connection fails if I close fiddler while it's active, but I guess that part isn't too surprising.

So unfortunately all I can offer is a trace of it working OK... [fiddler - success](https://github.com/aspnet/SignalR/files/2384016/success-fiddler.txt)

**Comment by BrennanConroy** [comment] 2018-09-24 19:18
Tried it out, SSE works correctly with Windows Auth enabled.

**Comment by BrennanConroy** [comment] 2018-09-26 19:48
@FTWinston Do you have an app that reproduces this?

Also, have you tried disabling Windows Auth in IIS and connecting with SSE?

**Comment by anurse** [comment] 2018-10-05 17:27
I'm going to close this just because we're still looking to find a repro for this. Please feel free to comment and reopen if you get a repro!

**Closed by anurse** 2018-10-05 17:27 UTC
Labels: status: More Info
