### ISSUE TITLE
Changing date format while sending data to server

### ISSUE THREAD

**Issue by sasquad92** [aspnet/SignalR#1346] opened 2018-01-25 14:41 UTC
I have problem with sending date from my client-side (react with @aspnet/signalr-client) to backend (dotnet 2.1.4).
I am invoking my connection with data:
`{
   boardid: 1,
   enddate: "2018-01-02T23:00:00.000Z",
   text: "some text",
   title: "some title"
}`

and what I get in my backend is `enddate "01/02/2018 23:00:00"`.
i have a lot of problems with this. Is there any possibility to force signalR to NOT format date like that?

**Comment by davidfowl** [comment] 2018-01-25 15:41
SignalR doesn't do anything special with dates. It's just calling JSON.stringify on the client.

**Comment by imsam67** [comment] 2018-01-25 17:36
Not sure if they're related but I had an interesting issue concerning date/time as well. I had a helper function that converted a UTC value to a particular time zone using their .NET ID's. This helper method worked perfectly fine everywhere in my ASP.NET Core 2.0 app except in the SignalR hub.

The other interesting parallel between your case and mine is that my frontend is also ReactJs. I really don't know what this means. I'm just pointing it out which may help us focus what may be the cause of potential date/time issues.

In my case, I simply changed my approach and started using UTC offset and the problem went away but I didn't really solve the issue. I just changed my approach so the symptoms disappeared. Here's the issue I'd posted: https://github.com/aspnet/SignalR/issues/1296

**Comment by sasquad92** [comment] 2018-01-25 21:47
@imsam67 I also have this problem only with signalR. Part of my app is working with webapi and there is everything fine.
Tomorrow I will check few options related to Json.stringify but I think that when I am sending my date as string (I used moment().toISOString()) everything should be all right. But it's not.

**Comment by anurse** [comment] 2018-01-25 22:53
Can you clarify exactly what JavaScript you are sending (i.e. [`Date`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date) or `String` containing the date?) and what the type on the server that you're trying to map it to is? (`DateTime` I presume).

**Comment by sasquad92** [comment] 2018-01-26 06:49
Sure. I'm sending `string` with date (I'm using `moment().toISOString();` and it's produce string (https://momentjs.com/docs/#/displaying/as-iso-string/)). On the server side I'm trying to map this to `string` field (`public virtual string ENDDATE { get; set; }`).
I'm doing the same with webapi and it's working properly.

**Comment by anurse** [comment] 2018-01-26 16:47
Ok, that is interesting, that the date format would be being changed even though all the types are string. We can look in to this and see if we can track it down. Thanks for the report!

**Comment by MateuszBogdan** [comment] 2018-03-26 14:46
I have that same problem but other way around. I decided to send date encoded as ISO string and I am using .NET Core console application client. Sending date in ISO format ie. 2018-03-26T14:34:00Z results on server side to be formatted like 03/26/2018 14:34:00. Both Dto objects are encoded as strings.
I don't know if culture of my specific machine is relevant but it is PL-pl.

**Comment by HaoK** [comment] 2018-03-30 22:45
@MateuszBogdan and @sasquad92 just to make sure I'm seeing the issue you guys are describing correctly:

When you try something like: `connection.invoke('SendDate', '2018-03-26T14:34:00Z')` sending an ISO string, on the server:

```
        public async Task SendDate(string date)
        {
            await Clients.All.SendAsync("Send", Context.User.Identity.Name, date);
        }
```

This results in the date to being converted to: '03/26/2018 14:34:00'

**Comment by HaoK** [comment] 2018-03-31 00:04
The call to JArray.ToObject is what's converting the string here: https://github.com/aspnet/SignalR/blob/dev/src/Microsoft.AspNetCore.SignalR.Common/Internal/Protocol/JsonHubProtocol.cs#L638

**Comment by HaoK** [comment] 2018-03-31 00:54
The root issue seems to be with Json.NET and working around its well known pain around DateTime munging: https://github.com/JamesNK/Newtonsoft.Json/issues/862

**Comment by HaoK** [comment] 2018-03-31 00:57
@davidfowl @anurse do we want to try to add hacks to fix json.net's crappy behavior?  Or just leave this as a external quirk that comes with the json payload?

**Comment by davidfowl** [comment] 2018-03-31 03:55
@JamesNK do you have any suggestions?

**Comment by davidfowl** [comment] 2018-03-31 04:00
I rather not work around JSON.NET defaults. Seems like it’s easy to work around by settings DateTimehandling

**Comment by anurse** [comment] 2018-03-31 17:00
Should we consider setting a different default for `DateTimeHandling`? Now's the time for that (before an RTM) ;)

**Comment by HaoK** [comment] 2018-03-31 19:00
From my admittedly fairly limited poking around on this bug, it looked like there are only two cases:

When the hub method is: `Method(string date)` it seems very counterintuitive that you don't get exactly what string you send from the client.

When the hub method is `Method(DateTime[Offset] date)` its reasonable to use the `DateTimeHandling` only in this case, and I think its probably best to just switch to None as the default probably...

**Comment by HaoK** [comment] 2018-03-31 19:02
There's an additional quirk where the order of the arguments passed in affects the code path too,  like if target is before args, vs after, it calls slightly different code paths for binding arguments, I fixed one of the paths that uses `ToObject` but a slightly different fix would be needed for the other path that goes thru the JsonSerializer

**Comment by davidfowl** [comment] 2018-03-31 19:04
> There's an additional quirk where the order of the arguments passed in affects the code path too, like if target is before args, vs after, it calls slightly different code paths for binding arguments, I fixed one of the paths that uses ToObject but a slightly different fix would be needed for the other path that goes thru the JsonSerializer

Yep, that's for performance reasons.

**Comment by JamesNK** [comment] 2018-03-31 21:10
> When the hub method is: Method(string date) it seems very counterintuitive that you don't get exactly what string you send from the client.
> 
> When the hub method is Method(DateTime[Offset] date) its reasonable to use the DateTimeHandling in this case, but I think its probably best to just switch to None as the default...

`DateTimeHandling.None` will fix both of those issues, and deserializing `DateTime`/`DateTimeOffset` will continue to work fine because the deserializer will handle the conversion instead of the `JsonReader`.

**Comment by JamesNK** [comment] 2018-03-31 21:11
I'll fix this along with some tests.

**Closed** 2018-04-01 00:26 UTC
Labels: 3 - Done

**Comment by HaoK** [comment] 2018-04-01 01:02
Its good you did since I'm on vacation next week :)
