### ISSUE TITLE
Return stream method error to client

### ISSUE THREAD

**Issue by Roonerelli** [aspnet/SignalR#1597] opened 2018-03-14 15:05 UTC
It seems that the following issue doesn't appear to be fixed in preview1
https://github.com/aspnet/SignalR/pull/1331

e.g if I have a hub method that returns the following:

```
public IObservable<MyClass> LiveStream()
        {
            return Observable.Create(
                async (IObserver<MyClass> observer) =>
                {
                    for (int i = 0; i < 100; i++)
                    {
                        if (i == 5)
                        {
                            observer.OnError(new Exception("Test.")); 
                        }
                        observer.OnNext(new MyClass("id", i) );
                        await Task.Delay(1000);
                    }
                })
```
Then the exception message isn't propagated to the client/browser

If I return the error as follows, it is

```
Subject<MyClass> rateChanged = new Subject<MyClass>();
rateChanged.OnError(new Exception("Test."));
return rateChanged.AsObservable();
```
But errors that occur after the stream has started should be handled correctly and it seems they arent
This came about when writing a fake to emulate various errors
Any ideas what is wrong? is it a known issue?

**Comment by anurse** [comment] 2018-03-14 15:53
Can you show the client code that isn't producing the exception message you expect?

**Comment by Roonerelli** [comment] 2018-03-14 16:07
sure , I'm just subscribing to the stream and logging the messages and errors:

```

var transport = signalR.TransportType.WebSockets;

    var bearerToken = getToken();
    var connection = new signalR.HubConnection(location.protocol + `//${document.location.host}/streaming?token=` + bearerToken,
        { transport: transport });
connection.stream("LiveStream", negotiation).subscribe({
            next: onStreamReceived,
            error: function(err) {
                console.log(err);
            },
            complete: function() {
                console.log("finished streaming");
            }
        });

```
The error method is called. It's just in the first case it's a general error. In the second case the exception message is propagated

(I removed the negotiation from the method on the Hub, to simplify the example I originally posted. Which is why the client code is sending a negotiation but the hub method doesnt have a parameter to recieve it). sorry for the confusion

**Comment by anurse** [comment] 2018-04-04 18:02
I'm not able to repro this in the branch for the upcoming preview2 release. In both cases, I get an error message saying: "Error: An error occurred on the server while streaming results. Exception: Test." which includes the exception message.

See below

![image](https://user-images.githubusercontent.com/7574/38325206-2ef0cc32-37f7-11e8-8fe7-bb7447e5bfb8.png)

And see the code 
* Server Hub: https://github.com/aspnet/SignalR/blob/anurse/1597-streaming/samples/SignalRSamples/Hubs/Streaming.cs
* Client code: https://github.com/aspnet/SignalR/blob/anurse/1597-streaming/samples/SignalRSamples/wwwroot/streaming.html

Note that in recent builds you have to set `EnableDetailedErrors` on `HubOptions` to `true` in [`.AddSignalR`](https://github.com/aspnet/SignalR/blob/76c45211bc206d80af4ed1bf3d82ba9aa9a52efd/samples/SignalRSamples/Startup.cs#L22-L29). Though this wasn't the case with the build you were testing with.

It's possible this was resolved by some earlier work related to streaming, so please try the nightly builds or preview 2 (when it is release) and let us know if you're still seeing the issue. I'm closing this for now, feel free to comment further with any questions. If the issue is still reproing for you with the latest builds, we can re-open and investigate further!

**Closed by anurse** 2018-04-04 18:02 UTC
Labels: 2 - Working, cost: M, investigate

**Comment by Roonerelli** [comment] 2018-04-16 15:40
Hi @anurse , thanks for the reply. I can confirm that the error is now propagated to the client in the new version.

However, it is appended onto the general error message. Is that the intention?

e.g.

{"type":3,"invocationId":"1","error":"An error occurred on the server while streaming results. Exception: QuoteDenied"}

In the example above, I threw an exception with a message of "QuoteDenied". Which appears after the default error message. I can work with that but curious if that is how it was designed?

**Comment by anurse** [comment] 2018-04-16 15:51
Yes, that is the intention.
