### ISSUE TITLE
How to send messages to a specific user from a Controller or Repository?

### ISSUE THREAD

**Issue by itsfelipesan** [aspnet/SignalR#155] opened 2017-01-25 20:15 UTC
I'm trying to get the current User from the Context outside a controller in my **Web API**. I'm using the OpenIddict to authenticate users, so the authorization is made by tokens.

I have registered the HttpContextAcessor as a singleton in my Startup.cs:

`services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();`

After that, I inject the HttpContexrAcessor in my hub, like this:

```
public class NotificationHub : Hub
    {
        private IHttpContextAccessor _contextAccessor;
        private HttpContext _context { get { return _contextAccessor.HttpContext; } }

        public NotificationHub(IHttpContextAccessor contextAccessor)
        {
            _contextAccessor = contextAccessor;
        }

        public async Task JoinGroup()
        {
            Groups.Add(Context.ConnectionId, $"notification_{_context.User.Identity.Name}");
        }

        public void Send(JsonResult notification)
        {
                Clients.Client(Context.ConnectionId).sendNotification(notification);
        }
    }
```

The problem is that _context.User.Identity.Name is always null.

I could send the message direct to the client from the Controller, using the ConnectionID, something like that:

`_connectionManager.GetHubContext<NotificationHub>().Clients.Client(CONNECTIONID).send(Json(notification));`

But It seems that thare is no way to get the ConnectionID from a Controller or a repository.

What could I do?

**Comment by davidfowl** [comment] 2017-01-25 20:17
The current user is available in via Context.User, you don't need the `IHttpContextAccessor`

**Comment by itsfelipesan** [comment] 2017-01-25 20:18
@davidfowl The problem is that the Context.User attributes, like the username, is null inside the hub. I don't know if it a problem because I'm using a Web API with token authorization.

**Comment by davidfowl** [comment] 2017-01-25 20:26
Sounds like another problem then. Either way, SignalR is under pretty heavy development right now. From your code sample above, it looks like you're using the older package that is no longer being developed. https://github.com/aspnet/SignalR-Server#aspnet-signalr-server

**Comment by itsfelipesan** [comment] 2017-01-25 20:29
That's the only package which appears to me: "Gray.Microsoft.AspNetCore.SignalR.Server": "0.2.0-alpha1"

**Comment by davidfowl** [comment] 2017-01-25 20:31
Sure, we haven't shipped anything yet and we definitely wouldn't ship something called Gray.Microsoft.*.

**Comment by itsfelipesan** [comment] 2017-01-25 20:33
![signal](https://cloud.githubusercontent.com/assets/16308565/22308072/a0bb491c-e32c-11e6-8307-0584cf243e0e.png)

When trying to use the package like the SinglaR server repo, no versions are displayed.

My complete package.json:

```
{
  "dependencies": {
    "Microsoft.AspNetCore.Mvc": "1.1.0-preview1-final",
    "Microsoft.AspNetCore.Antiforgery": "1.1.0-preview1-final",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.1.0-preview1-final",
    "Microsoft.AspNetCore.Server.Kestrel": "1.1.0-preview1-final",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.1.0-preview1-final",
    "Microsoft.Extensions.Configuration.FileExtensions": "1.1.0-preview1-final",
    "Microsoft.Extensions.Configuration.Json": "1.1.0-preview1-final",
    "Microsoft.Extensions.Logging": "1.1.0-preview1-final",
    "Microsoft.Extensions.Logging.Console": "1.1.0-preview1-final",
    "Microsoft.Extensions.Logging.Debug": "1.1.0-preview1-final",
    "Microsoft.AspNetCore.Hosting": "1.1.0-preview1-final",
    "Microsoft.EntityFrameworkCore": "1.1.0-preview1-final",
    "Microsoft.EntityFrameworkCore.Design": "1.1.0-preview1-final",
    "Microsoft.EntityFrameworkCore.Relational": "1.1.0-preview1-final",
    "Microsoft.AspNetCore.Diagnostics": "1.1.0-preview1-final",
    "AspNet.Security.OAuth.Validation": "1.0.0-alpha3-0188",
    "Microsoft.AspNetCore.Authentication.JwtBearer": "1.1.0-preview1-final",
    "OpenIddict": "1.0.0-*",
    "OpenIddict.EntityFrameworkCore": "1.0.0-*",
    "OpenIddict.Mvc": "1.0.0-*",
    "Microsoft.AspNetCore.StaticFiles": "1.1.0-preview1-final",
    "Dreampper.Domain": "1.0.0-*",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.1.0-preview1-final",
    "Dreampper.Crosscutting": "1.0.0-*",
    "Gray.Microsoft.AspNetCore.SignalR.Server": "0.2.0-alpha1",
    "Microsoft.AspNetCore.WebSockets": "1.0.0",
    "Microsoft.Azure.DocumentDB.Core": "1.0.0",
    "Microsoft.AspNetCore.SignalR.Server": 
  },

  "tools": {
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": {
      "version": "1.0.0-preview2-final",
      "imports": "portable-net45+win8+dnxcore50"
    },
    "Microsoft.EntityFrameworkCore.Tools.DotNet": "1.0.0-preview3-final"
  },

  "frameworks": {
    "netcoreapp1.1": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.1.0-preview1-001100-00"
        }
      },
      "imports": [
        "dotnet5.6",
        "dnxcore50",
        "portable-net45+win8"
      ]
    }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "runtimeOptions": {
    "gcServer": true
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "Views",
      "appsettings.json",
      "web.config"
    ]
  },

  "scripts": {
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  },

  "prepublish": [ "npm install", "jspm install -y", "gulp bundle" ]
}

```

**Comment by davidfowl** [comment] 2017-01-25 20:35
Right, we haven't shipped anything yet. If you want to use the latest SignalR you need to use myget and all of the latest packages. You can't use it with 1.1 of ASP.NET Core.

**Comment by dreampper** [comment] 2017-01-25 23:28
So why the samples of the repo use the .NET Core 1.1? https://github.com/aspnet/SignalR/blob/dev/samples/ChatSample/project.json

**Comment by davidfowl** [comment] 2017-01-25 23:37
Temporary placeholder, see the package version of Microsoft.NETCore.App https://github.com/aspnet/SignalR/blob/dev/samples/ChatSample/project.json#L5

**Comment by dreampper** [comment] 2017-01-25 23:49
What about the conflict between TASK in System.Treading and System.Runtime when using the myget for SignalR and OpenIddict?

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="NuGet" value="https://api.nuget.org/v3/index.json" />
    <add key="aspnet-contrib" value="https://www.myget.org/F/aspnet-contrib/api/v3/index.json" />
    <add key="AspNetCore" value="https://dotnet.myget.org/F/aspnetcore-ci-dev/api/v3/index.json" />
  </packageSources>
</configuration>
```

**Comment by davidfowl** [comment] 2017-01-25 23:53
That's because you need to use a newer version of the SDK. https://github.com/aspnet/SignalR/blob/dev/global.json#L7. Things are a little bleeding edge right now. This version of the SDK doesn't officially ship, we're just using it during the transition from project.json -> msbuild.

**Comment by dreampper** [comment] 2017-01-26 00:03
Weird... We are already using that SDK version.

**Comment by davidfowl** [comment] 2017-01-26 00:04
How so? Where did you get it?

**Comment by dreampper** [comment] 2017-01-26 00:05
https://dotnetcli.blob.core.windows.net/dotnet/preview/Installers/1.0.0-preview2-1-003180/dotnet-dev-win-x64.1.0.0-preview2-1-003180.exe

**Comment by davidfowl** [comment] 2017-01-26 00:07
Did you verify that you are using it?

**Comment by dreampper** [comment] 2017-01-26 00:09
At least that's what is in our global.json.

So, there is a prediction of when some stable version of signalR will be released? The problem is that we need the SignalR in the project until the Microsoft Imagine Cup 2017 or to get another way to deal with it.

**Comment by moozzyk** [comment] 2017-01-26 00:17
@dreampper - `git clean -xdf` and run `build.cmd` it will install the runtime you need restore packages etc.

**Comment by dreampper** [comment] 2017-01-26 03:08
@moozzyk I did, but It's not work.

**Comment by moozzyk** [comment] 2017-01-26 03:19
Show exactly what you have, what you tried and what doesn't work. build.cmd/build.sh did not work? If it did not, how it did not work? Your project.json contains this:   "Gray.Microsoft.AspNetCore.SignalR.Server": "0.2.0-alpha1", which pulls some outdated packages. Remove this - new SignalR does not depend on this and you don't need it. Start from a minimal project and make it work or report. With a big project you don't know what is breaking.

**Comment by itsfelipesan** [comment] 2017-01-26 11:51
I'll create a new project and try to simulate what I want, after that I post the repo here.

**Comment by itsfelipesan** [comment] 2017-01-26 14:16
Ok @moozzyk, I have created a new SignalR POC project. I'm just using the OpenIddict with a Web API. I follow your steps and I'm still getting the same errors.

1) I have changed the NuGet.config:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="NuGet" value="https://api.nuget.org/v3/index.json" />
    <add key="aspnet-contrib" value="https://www.myget.org/F/aspnet-contrib/api/v3/index.json" />
    <add key="AspNetCore" value="https://dotnet.myget.org/F/aspnetcore-ci-dev/api/v3/index.json" />
  </packageSources>
</configuration>
```

2) I have added the necessary packages:

```
"dependencies": {
    "Microsoft.AspNetCore.Mvc": "1.1.0",
    "Microsoft.AspNetCore.Routing": "1.1.0",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.1.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.1.0",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.1.0",
    "Microsoft.Extensions.Configuration.FileExtensions": "1.1.0",
    "Microsoft.Extensions.Configuration.Json": "1.1.0",
    "Microsoft.Extensions.Logging": "1.1.0",
    "Microsoft.Extensions.Logging.Console": "1.1.0",
    "Microsoft.Extensions.Logging.Debug": "1.1.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.1.0",
    "Microsoft.AspNetCore.Identity": "1.1.0",
    "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.1.0",
    "AspNet.Security.OAuth.Validation": "1.0.0-alpha2-final",
    "OpenIddict": "1.0.0-*",
    "OpenIddict.EntityFrameworkCore": "1.0.0-*",
    "OpenIddict.Mvc": "1.0.0-*",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.1.0-preview1-final",
    "Microsoft.EntityFrameworkCore.Design": "1.1.0",
    "jQuery": "3.1.1",
    "Microsoft.AspNetCore.StaticFiles": "1.1.0",
    "Microsoft.AspNetCore.SignalR": "1.0.0-*"
  }
```

3) I have run the build.cmd

![cmd](https://cloud.githubusercontent.com/assets/16308565/22334233/1a3e28a6-e3c1-11e6-8745-53dcfa005e2a.png)

After those steps, the code is still getting errors.

![vs](https://cloud.githubusercontent.com/assets/16308565/22334284/506733e6-e3c1-11e6-80d3-8314876819de.png)

**Comment by moozzyk** [comment] 2017-01-27 19:02
Because these screenshots are not actionable and the application still seems to be using a lot of extraneous packages which may get in the way I created a project where I added SignalR Core to an application created from VS templates. Here is the project: https://github.com/moozzyk/SignalRCoreTest/tree/master. Take a look at commits - each commit is a conversion step. Note after packages/runtime were updated to 1.2.0 I had to run the application using `C:\Users\##USERNAME##\AppData\Local\Microsoft\dotnet\dotnet.exe run` because this is where `build.cmd` from SignalR repo installs the required runtime to.

**Closed by moozzyk** 2017-01-27 19:02 UTC

**Comment by jordanwallwork** [comment] 2017-03-29 14:04
@davidfowl sorry I know this is kinda old now, but what's the state of affairs now when trying to run SignalR on an ASP.NET Core 1.1 app (targetting net462)? I've been looking into it but am getting confused with the different versions of everything
