### ISSUE TITLE
Method not found: 'System.Threading.Tasks.Task Microsoft.AspNetCore.SignalR.IClientProxy.InvokeAsync

### ISSUE THREAD

**Issue by jatarga** [aspnet/SignalR#2286] opened 2018-05-16 18:13 UTC
* Versions of Server-Side NuGet Packages:

```
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.0.0-rc1-final" />
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.8" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.0.0" />
    <PackageReference Include="MySql.Data.Core" Version="7.0.4-IR-191" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="2.0.1" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.0" />
    <DotNetCliToolReference Include="Microsoft.Extensions.SecretManager.Tools" Version="2.0.0" />
  </ItemGroup>
```

* Versions of Client-Side NuGet/NPM Packages: 
`"@aspnet/signalr": "^1.0.0-rc1-update1"`

* Are you using the C# client or the JavaScript client: **Javascript**
* The Server you are using (Kestrel/HttpSysServer/IIS/IIS Express/Azure Web App/etc.):  **Kestrel**
* The Operating System on the Server (Windows/Linux/macOS): **Linux**
* The Operating System on the Client (Windows/Linux/macOS): **Linux**
* The Browser on the client, if using the JavaScript client (IE/Chrome/Edge/Firefox/etc.): **Chrome**

Browser successfully establishes connection with server, but I can't broadcast any event.

```
Information: Normalizing '/MarketsHub' to 'http://127.0.0.1:5001/MarketsHub'.
vendor.e21e67466668a8385014.js:54 Information: WebSocket connected to ws://127.0.0.1:5001/MarketsHub?id=Zz4CqvyqjhFHPHpvaGSqmQ
```

When I try to broadcast I get following exception:

```
Method not found: 'System.Threading.Tasks.Task Microsoft.AspNetCore.SignalR.IClientProxy.InvokeAsync(System.String, System.Object[])'.
   at App.MarketsHubWrapper.BroadcastNewEvent(String arg, Object order)

```

**Comment by jatarga** [comment] 2018-05-16 18:55
```
public void BroadcastNewEvent(string arg, object order)
{
    _hub.Clients.All.InvokeAsync("OnNewOrder", order);
}
```

**Comment by anurse** [comment] 2018-05-16 19:07
That is very weird. I think something isn't quite matching up between the version you're compiling against and the version you're running on. Would you be able to create a simple project that reproduces the error and publish it somewhere so we can see the code?

**Comment by jatarga** [comment] 2018-05-16 19:09
Sure, I will try to reproduce the project, maybe I even find my mistake if I had any.

Thanks.

**Comment by anurse** [comment] 2018-05-25 21:30
Any update on this @jatarga ? I'm going to close this issue as it's been 9 days since we heard from you, but feel free to comment when you are able to reproduce the issue! We can always re-open the bug!

**Closed by anurse** 2018-05-25 21:30 UTC
Labels: investigate, more-info

**Comment by jatarga** [comment] 2018-05-26 10:32
I see a commit related to my problem:

https://github.com/aspnet/SignalR/commit/d38764a8f0a9cc189e84c28113a5a7aa5b5535d7

**Comment by davidfowl** [comment] 2018-05-26 13:47
Yes that change is 4 months old. If you’re still hitting this problem you’re app is likely in a state where it’s using sole super old dll. Make a new application referencing the latest rc1 bits and it’ll likely work.

**Comment by jatarga** [comment] 2018-05-26 13:53
It turns out in this multi-project solution, there are two references to the _Microsoft.AspNetCore.SignalR_. We updated all of them to "1.0.0-rc1-final" and updated npm version "@aspnet/signalr" to 1.0.0-rc1-final. Solved.
