### ISSUE TITLE
Aurelia CLI compilation failled with signalr-client

### ISSUE THREAD

**Issue by aguacongas** [aspnet/SignalR#671] opened 2017-07-19 16:53 UTC
I try to use the use `signalr-client` with [aurelia](http://aurelia.io) in this [chat sample project](https://github.com/aguacongas/chatle.aurelia)  
But I cannot build the project using aurelia cli with `au build`: 

```
{ uid: 8,
  name: 'writeBundles',
  branch: false,
  error:
   { Error: ENOENT: no such file or directory, open 'C:\Projects\Perso\chatle.aurelia\src\signalr-client.js'
       at Error (native)
       at Object.fs.openSync (fs.js:641:18)
       at Object.fs.readFileSync (fs.js:509:33)
       at Object.exports.readFileSync (C:\Projects\Perso\chatle.aurelia\node_modules\aurelia-cli\lib\file-system
.js:49:13)
       at fileRead (C:\Projects\Perso\chatle.aurelia\node_modules\aurelia-cli\lib\build\bundled-source.js:83:31)
       at Object.context.fileRead (C:\Projects\Perso\chatle.aurelia\node_modules\aurelia-cli\lib\build\amodro-tr
ace\lib\loader\Loader.js:176:18)
       at Object.context.load (C:\Projects\Perso\chatle.aurelia\node_modules\aurelia-cli\lib\build\amodro-trace\
lib\loader\Loader.js:357:30)
       at Object.load (eval at <anonymous> (C:\Projects\Perso\chatle.aurelia\node_modules\aurelia-cli\lib\build\
amodro-trace\lib\loader\Loader.js:14:9), <anonymous>:832:29)
       at Object.fetch (eval at <anonymous> (C:\Projects\Perso\chatle.aurelia\node_modules\aurelia-cli\lib\build
\amodro-trace\lib\loader\Loader.js:14:9), <anonymous>:822:66)
       at Object.check (eval at <anonymous> (C:\Projects\Perso\chatle.aurelia\node_modules\aurelia-cli\lib\build
\amodro-trace\lib\loader\Loader.js:14:9), <anonymous>:854:30)
     errno: -4058,
     code: 'ENOENT',
     syscall: 'open',
     path: 'C:\\Projects\\Perso\\chatle.aurelia\\src\\signalr-client.js',
     moduleTree: [ 'services/chat.service' ],
     fileName: 'C:/Projects/Perso/chatle.aurelia/src/services/chat.service.js' },
  duration: [ 1, 397265249 ],
  time: 1500482168580 }
{ uid: 0,
  name: '<series>',
  branch: true,
  error:
   { Error: ENOENT: no such file or directory, open 'C:\Projects\Perso\chatle.aurelia\src\signalr-client.js'
       at Error (native)
       at Object.fs.openSync (fs.js:641:18)
       at Object.fs.readFileSync (fs.js:509:33)
       at Object.exports.readFileSync (C:\Projects\Perso\chatle.aurelia\node_modules\aurelia-cli\lib\file-system
.js:49:13)
       at fileRead (C:\Projects\Perso\chatle.aurelia\node_modules\aurelia-cli\lib\build\bundled-source.js:83:31)
       at Object.context.fileRead (C:\Projects\Perso\chatle.aurelia\node_modules\aurelia-cli\lib\build\amodro-tr
ace\lib\loader\Loader.js:176:18)
       at Object.context.load (C:\Projects\Perso\chatle.aurelia\node_modules\aurelia-cli\lib\build\amodro-trace\
lib\loader\Loader.js:357:30)
       at Object.load (eval at <anonymous> (C:\Projects\Perso\chatle.aurelia\node_modules\aurelia-cli\lib\build\
amodro-trace\lib\loader\Loader.js:14:9), <anonymous>:832:29)
       at Object.fetch (eval at <anonymous> (C:\Projects\Perso\chatle.aurelia\node_modules\aurelia-cli\lib\build
\amodro-trace\lib\loader\Loader.js:14:9), <anonymous>:822:66)
       at Object.check (eval at <anonymous> (C:\Projects\Perso\chatle.aurelia\node_modules\aurelia-cli\lib\build
\amodro-trace\lib\loader\Loader.js:14:9), <anonymous>:854:30)
     errno: -4058,
     code: 'ENOENT',
     syscall: 'open',
     path: 'C:\\Projects\\Perso\\chatle.aurelia\\src\\signalr-client.js',
     moduleTree: [ 'services/chat.service' ],
     fileName: 'C:/Projects/Perso/chatle.aurelia/src/services/chat.service.js' },
  duration: [ 4, 236701131 ],
  time: 1500482168585 }
{ Error: ENOENT: no such file or directory, open 'C:\Projects\Perso\chatle.aurelia\src\signalr-client.js'
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.readFileSync (fs.js:509:33)
    at Object.exports.readFileSync (C:\Projects\Perso\chatle.aurelia\node_modules\aurelia-cli\lib\file-system.js
:49:13)
    at fileRead (C:\Projects\Perso\chatle.aurelia\node_modules\aurelia-cli\lib\build\bundled-source.js:83:31)
    at Object.context.fileRead (C:\Projects\Perso\chatle.aurelia\node_modules\aurelia-cli\lib\build\amodro-trace
\lib\loader\Loader.js:176:18)
    at Object.context.load (C:\Projects\Perso\chatle.aurelia\node_modules\aurelia-cli\lib\build\amodro-trace\lib
\loader\Loader.js:357:30)
    at Object.load (eval at <anonymous> (C:\Projects\Perso\chatle.aurelia\node_modules\aurelia-cli\lib\build\amo
dro-trace\lib\loader\Loader.js:14:9), <anonymous>:832:29)
    at Object.fetch (eval at <anonymous> (C:\Projects\Perso\chatle.aurelia\node_modules\aurelia-cli\lib\build\am
odro-trace\lib\loader\Loader.js:14:9), <anonymous>:822:66)
    at Object.check (eval at <anonymous> (C:\Projects\Perso\chatle.aurelia\node_modules\aurelia-cli\lib\build\am
odro-trace\lib\loader\Loader.js:14:9), <anonymous>:854:30)
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Projects\\Perso\\chatle.aurelia\\src\\signalr-client.js',
  moduleTree: [ 'services/chat.service' ],
  fileName: 'C:/Projects/Perso/chatle.aurelia/src/services/chat.service.js' }
```

To workaround I copy the signalr-client.js to the location the compiler try to find it but I think the package is not well defined

**Comment by moozzyk** [comment] 2017-07-19 17:01
Can you show how you tried to include the signalr client?

**Comment by aguacongas** [comment] 2017-07-19 17:06
https://github.com/aguacongas/chatle.aurelia/blob/develop/src/services/chat.service.ts

**Comment by moozzyk** [comment] 2017-07-19 17:16
Thanks - I did not realize you were using Typescript. I hit this as well some time ago but have not tackled it yet.

**Comment by moozzyk** [comment] 2017-08-21 23:00
Can you try with the latest version of the signalr-client (at least 0.1.0-alpha1-26727) ?

I did try and got this:
```
PS C:\temp\aurelia-test\chatle.aurelia> .\node_modules\.bin\aurelia.cmd build
Starting 'readProjectConfiguration'...
Unable to load package metadata (package.json) of text:
Error: packageRoot property not defined for the "text" package. It is recommended to define the packageRoot for packages outside the node_modules folder, so tha
t the files end up inthe correct bundle
Finished 'readProjectConfiguration'
Starting 'processMarkup'...
Starting 'processCSS'...
Starting 'configureEnvironment'...
Finished 'processCSS'
Finished 'configureEnvironment'
Starting 'buildTypeScript'...
gulp-typescript: ts(tsProject) has been deprecated - use .pipe(tsProject()) instead
  As of gulp-typescript 3.0, .pipe(ts(tsProject)) should be written as .pipe(tsProject()).
  More information: http://dev.ivogabe.com/gulp-typescript-3/
Finished 'processMarkup'
Finished 'buildTypeScript'
Starting 'writeBundles'...
Tracing app...
Tracing main...
Tracing components/contact-list...
Tracing components/contact...
Tracing components/conversation-component...
Tracing components/conversation-list...
Tracing components/conversation-preview...
Tracing components/user-name...
Tracing model/changePassword...
Tracing model/manage-logins...
Tracing model/provider...
Tracing model/serviceError...
Tracing pages/account...
Tracing pages/confirm...
Tracing pages/home...
Tracing pages/login...
Tracing resources/index...
Tracing app...
Tracing css/site...
Tracing components/contact-list...
Tracing css/site.min...
Tracing components/contact...
Tracing components/conversation-component...
Tracing components/conversation-list...
Tracing components/conversation-preview...
Tracing components/user-name...
Tracing pages/account...
Tracing pages/confirm...
Tracing pages/home...
Tracing pages/login...
Tracing aurelia-bootstrapper...
Tracing aurelia-history-browser...
Tracing aurelia-loader-default...
Tracing aurelia-pal-browser...
Tracing aurelia-templating-binding...
Tracing aurelia-fetch-client...
Tracing text...
Tracing aurelia-templating-resources...
Tracing aurelia-templating-router...
Tracing aurelia-testing...
Writing app-bundle.js...
Writing vendor-bundle.js...
Finished 'writeBundles'
PS C:\temp\aurelia-test\chatle.aurelia> ls
```
I don't know aurelia so am not sure if this means the issue is fixed.

**Comment by moozzyk** [comment] 2017-08-22 18:49
I think this should be fixed. Feel free to reopen or file a new issue if it still does not work.

**Closed by moozzyk** 2017-08-22 18:49 UTC
