### ISSUE TITLE
Frequent 404 error when connecting websocket to Azure SignalR from Safari 11.1 and some mobile browsers

### ISSUE THREAD

**Issue by WesleySSmith** [aspnet/SignalR#3126] opened 2018-10-13 00:06 UTC
* Versions of Server-Side NuGet Packages:
1.0.0
* Versions of Client-Side NuGet/NPM Packages:
1.0.3 and 1.0.4
* Are you using the C# client or the JavaScript client:
JavaScript
* The Server you are using (Kestrel/HttpSysServer/IIS/IIS Express/Azure Web App/etc.): 
Azure Web App along with Azure SignalR service
* The Operating System on the Server (Windows/Linux/macOS):
Azure
* The Operating System on the Client (Windows/Linux/macOS):
MacOS
* The Browser on the client, if using the JavaScript client (IE/Chrome/Edge/Firefox/etc.):
Safari 11.1

I have a Azure SignalR resource using a paid plan. I also have a Azure App Service website that is a ASP.NET Core application that uses this SignalR resource.  On my Windows Chrome or Windows Edge browsers, I can visit my website and SignalR works as expected.  But on Safari 11.1.2 for Mac, as well as some mobile browsers, SignalR does not work as expected.

1) The browser makes an OPTIONS call to my /negotiate page

2) The browser POSTs to the /negotiate page on my website, and I see the response come back like this, as expected.

`{'url':'https://testsignalrservice3.service.signalr.net/client/?hub=signalrhub&asrs.op=%2FSignalRHub','accessToken':'XXX','availableTransports':[]}`

3) The browser makes an OPTIONS call to the Azure service

4) The browser makes a POST to the https://testsignalrservice3.service.signalr.net/client/negotiate?hub=signalrhub&asrs.op=%2FSignalRHub  resource of Azure SignalR, and the response is as expected:

`{'connectionId':'XAram2iUlvfeF0pPjDECyw','availableTransports':[{'transport':'WebSockets','transferFormats':['Text','Binary']},{'transport':'ServerSentEvents','transferFormats':['Text']},{'transport':'LongPolling','transferFormats':['Text','Binary']}]}`

5) The browser try to establish the web socket connection to:

wss://testsignalrservice3.service.signalr.net/client/?hub=signalrhub&asrs.op=%2FSignalRHub&id=XAram2iUlvfeF0pPjDECyw&access_token=XXX

However, Azure SignalR's response to this is a 404.  

I have found that if I reload the page over and over, the websocket connects maybe once every 5 times, so there's some element of a race condition or chance involved.

One  possible clue that I've found when comparing the network traces between the working (Chrome) and failing (Safari) cases:  when Safari makes the websocket connection (#5 above) , it **doesn't** pass the SIGNALRROUTE cookie that the negotiate call returned (in step #4) , whereas I notice that Chrome on Windows **does** pass that cookie.  

My theory is that without that cookie, the Azure SignalR service doesn't properly handle the request and returns a 404.

Attaching console traces and fiddler .saz traces of the working (chrome) and failing (safari) cases.

[WorkingSignalR connect.saz.txt](https://github.com/aspnet/SignalR/files/2474878/WorkingSignalR.connect.saz.txt)
[Failed console.txt](https://github.com/aspnet/SignalR/files/2474879/Failed.console.txt)
[FailedSignalR connect.saz.txt](https://github.com/aspnet/SignalR/files/2474880/FailedSignalR.connect.saz.txt)
[Working console.txt](https://github.com/aspnet/SignalR/files/2474881/Working.console.txt)

**Comment by anurse** [comment] 2018-10-13 17:03
> when Safari makes the websocket connection (#5 above) , it **doesn't** pass the SIGNALRROUTE cookie that the negotiate call returned

Yep, this would cause exactly this issue. Does it work if you [enable third-party cookies](https://superuser.com/questions/1292504/how-to-allow-third-party-cookies-in-safari-11-0-3-13604-5-6) in Safari? I realize that's not really an appropriate workaround, just gathering data :).

Also, does it work if you [force the connection to use a different transport](https://docs.microsoft.com/en-us/aspnet/core/signalr/configuration?view=aspnetcore-2.1#configure-allowed-transports)? I think Long Polling may not have this problem (again, not a great workaround, but helps us identify the issue).

cc @chenkennt @davidfowl for Azure SignalR. I think there's an issue with sending third-party cookies (i.e. cookies set on a different domain from the page) in Safari when using WebSockets.

**Comment by davidfowl** [comment] 2018-10-13 18:45
I wonder if we can do stickyness  based on the connection id in the query string...

**Comment by mikaelm12** [comment] 2018-10-15 17:00
> t. I assume that even without the cookie, some percentage of the requests are randomly routed correctly on the Azure side and therefore work, but as soon as one is routed incorrectly, the 404 results.

Yeah, without the cookie to ensure you're being routed back to the correct container you essentially have a 1/N, chance of having a successful request, where N is the number of containers.

**Comment by anurse** [comment] 2018-10-16 17:29
Closing this issue in this repo as the problem is due to browser limitations we can't avoid. The Azure SignalR SDK is looking in to ways to mitigate this issue.

**Closed by anurse** 2018-10-16 17:29 UTC

**Comment by juniwang** [comment] 2018-12-12 02:13
FYI, it is already fixed in the SDK 1.0.4, that we do not depend on Cookies for sticky sessions anymore.
