### ISSUE TITLE
Flaky test CanStopAndStartConnection

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR#1672] opened 2018-03-21 03:37 UTC
```
[xUnit.net 00:00:10.1556603]     Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests.CanStopAndStartConnection(protocol: JsonHubProtocol { Name = "json", PayloadSerializer = JsonSerializer { Binder = (throws InvalidOperationException), CheckAdditionalContent = False, ConstructorHandling = Default, Context = System.Runtime.Serialization.StreamingContext, ContractResolver = CamelCasePropertyNamesContractResolver { ... }, ... }, TransferFormat = Text }, transportType: WebSockets, path: "/hubT") [FAIL]
Failed   Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests.CanStopAndStartConnection(protocol: JsonHubProtocol { Name = "json", PayloadSerializer = JsonSerializer { Binder = (throws InvalidOperationException), CheckAdditionalContent = False, ConstructorHandling = Default, Context = System.Runtime.Serialization.StreamingContext, ContractResolver = CamelCasePropertyNamesContractResolver { ... }, ... }, TransferFormat = Text }, transportType: WebSockets, path: "/hubT")
Error Message:
 System.OperationCanceledException : The operation was canceled.
Stack Trace:
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
```

Not sure why this got cancelled

**Comment by anurse** [comment] 2018-03-21 03:38
Nice stack trace there :)

**Comment by BrennanConroy** [comment] 2018-03-21 04:05
Let me help
```
[xUnit.net 00:00:10.1556603]     Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests.CanStopAndStartConnection(protocol: JsonHubProtocol { Name = "json", PayloadSerializer = JsonSerializer { Binder = (throws InvalidOperationException), CheckAdditionalContent = False, ConstructorHandling = Default, Context = System.Runtime.Serialization.StreamingContext, ContractResolver = CamelCasePropertyNamesContractResolver { ... }, ... }, TransferFormat = Text }, transportType: WebSockets, path: "/hubT") [FAIL]
Failed   Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests.CanStopAndStartConnection(protocol: JsonHubProtocol { Name = "json", PayloadSerializer = JsonSerializer { Binder = (throws InvalidOperationException), CheckAdditionalContent = False, ConstructorHandling = Default, Context = System.Runtime.Serialization.StreamingContext, ContractResolver = CamelCasePropertyNamesContractResolver { ... }, ... }, TransferFormat = Text }, transportType: WebSockets, path: "/hubT")
Error Message:
 System.OperationCanceledException : The operation was canceled.
Stack Trace:
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Microsoft.AspNetCore.Sockets.Client.HttpConnection.SendAsyncCore(Byte[] data, CancellationToken cancellationToken) in /_/src/Microsoft.AspNetCore.Sockets.Client.Http/HttpConnection.cs:line 527
   at Microsoft.AspNetCore.Sockets.Client.HttpConnection.SendAsync(Byte[] data, CancellationToken cancellationToken) in /_/src/Microsoft.AspNetCore.Sockets.Client.Http/HttpConnection.cs:line 510
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncCore() in /_/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs:line 125
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsync() in /_/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs:line 79
   at System.Threading.Tasks.TaskExtensions.OrTimeout(Task task, TimeSpan timeout, String memberName, String filePath, Nullable`1 lineNumber) in /_/test/Microsoft.AspNetCore.SignalR.Tests.Utils/TaskExtensions.cs:line 35
   at Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests.CanStopAndStartConnection(IHubProtocol protocol, TransportType transportType, String path) in /_/test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/HubConnectionTests.cs:line 122
   at Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests.CanStopAndStartConnection(IHubProtocol protocol, TransportType transportType, String path) in /_/test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/HubConnectionTests.cs:line 132
--- End of stack trace from previous location where exception was thrown ---
Standard Output Messages:
 | TestLifetime Information: Starting test CanStopAndStartConnection_json_WebSockets_hubT
 | Microsoft.AspNetCore.Sockets.Client.HttpConnection Debug: Connection state changed from Disconnected to Connecting.
 | Microsoft.AspNetCore.Sockets.Client.HttpConnection Debug: Starting connection.
 | Microsoft.AspNetCore.Sockets.Client.HttpConnection Debug: Starting transport 'WebSockets' with Url: http://127.0.0.1:46607/hubT.
 | Microsoft.AspNetCore.Sockets.Client.WebSocketsTransport Information: Starting transport. Transfer mode: Text.
 | Microsoft.AspNetCore.Sockets.Client.HttpConnection Debug: Connection state changed from Connecting to Connected.
 | Microsoft.AspNetCore.Sockets.Client.HttpConnection Trace: Beginning receive loop.
 | Microsoft.AspNetCore.SignalR.Client.HubConnection Information: Using HubProtocol 'json'.
 | Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Sending Hub Handshake.
 | Microsoft.AspNetCore.Sockets.Client.HttpConnection Debug: Sending message.
 | Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: Resetting keep-alive timer, received a message from the server.
 | Microsoft.AspNetCore.Sockets.Client.WebSocketsTransport Debug: Received message from application. Payload size: 20.
 | Microsoft.AspNetCore.Sockets.Client.WebSocketsTransport Debug: Message received. Type: Text, size: 3, EndOfMessage: True.
 | Microsoft.AspNetCore.Sockets.Client.HttpConnection Debug: Scheduling raising Received event.
 | Microsoft.AspNetCore.Sockets.Client.HttpConnection Debug: Raising Received event.
 | Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: Resetting keep-alive timer, received a message from the server.
 | Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Received 3 bytes. Parsing message(s).
 | Microsoft.AspNetCore.SignalR.Client.InvocationRequest.NonStreaming Trace: Invocation 1 created.
 | Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: Preparing blocking invocation '1' of 'Echo', with return type 'System.String' and 1 argument(s).
 | Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Registering Invocation ID '1' for tracking.
 | Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: Issuing Invocation '1': System.String Echo(System.String).
 | Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Sending Invocation '1'.
 | Microsoft.AspNetCore.Sockets.Client.HttpConnection Debug: Sending message.
 | Microsoft.AspNetCore.Sockets.Client.WebSocketsTransport Debug: Received message from application. Payload size: 70.
 | Microsoft.AspNetCore.Sockets.Client.WebSocketsTransport Debug: Message received. Type: Text, size: 49, EndOfMessage: True.
 | Microsoft.AspNetCore.Sockets.Client.HttpConnection Debug: Scheduling raising Received event.
 | Microsoft.AspNetCore.Sockets.Client.HttpConnection Debug: Raising Received event.
 | Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: Resetting keep-alive timer, received a message from the server.
 | Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Received 49 bytes. Parsing message(s).
 | Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Received 1 message(s).
 | Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: Received Completion for Invocation 1.
 | Microsoft.AspNetCore.SignalR.Client.InvocationRequest.NonStreaming Trace: Invocation 1 marked as completed.
 | Microsoft.AspNetCore.SignalR.Client.InvocationRequest.NonStreaming Trace: Invocation 1 disposed.
 | Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Finished processing 1 message(s).
 | Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Sending Invocation '1' completed.
 | Microsoft.AspNetCore.Sockets.Client.HttpConnection Information: Stopping client.
 | Microsoft.AspNetCore.Sockets.Client.WebSocketsTransport Information: Transport is stopping.
 | Microsoft.AspNetCore.Sockets.Client.WebSocketsTransport Debug: Send loop stopped.
 | Microsoft.AspNetCore.Sockets.Client.WebSocketsTransport Debug: Receive loop canceled.
 | Microsoft.AspNetCore.Sockets.Client.WebSocketsTransport Debug: Receive loop stopped.
 | Microsoft.AspNetCore.Sockets.Client.HttpConnection Trace: Ending receive loop.
 | Microsoft.AspNetCore.Sockets.Client.HttpConnection Debug: Ensuring all outstanding messages are processed.
 | Microsoft.AspNetCore.Sockets.Client.HttpConnection Debug: Draining event queue.
 | Microsoft.AspNetCore.Sockets.Client.HttpConnection Debug: Completing Closed task.
 | Microsoft.AspNetCore.Sockets.Client.HttpConnection Debug: Connection state changed from Connected to Disconnected.
 | Microsoft.AspNetCore.Sockets.Client.HttpConnection Debug: Connection state changed from Disconnected to Connecting.
 | Microsoft.AspNetCore.Sockets.Client.HttpConnection Debug: Starting connection.
 | Microsoft.AspNetCore.Sockets.Client.HttpConnection Debug: Starting transport 'WebSockets' with Url: http://127.0.0.1:46607/hubT.
 | Microsoft.AspNetCore.Sockets.Client.WebSocketsTransport Information: Starting transport. Transfer mode: Text.
 | Microsoft.AspNetCore.Sockets.Client.HttpConnection Debug: Connection state changed from Connecting to Connected.
 | Microsoft.AspNetCore.Sockets.Client.HttpConnection Trace: Beginning receive loop.
 | Microsoft.AspNetCore.SignalR.Client.HubConnection Information: Using HubProtocol 'json'.
 | Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Sending Hub Handshake.
 | Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: Shutting down connection.
 | Microsoft.AspNetCore.Sockets.Client.HttpConnection Debug: Sending message.
 | Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests Error: Exception from test
 |    at System.Threading.CancellationToken.ThrowOperationCanceledException()
 |    at Microsoft.AspNetCore.Sockets.Client.HttpConnection.SendAsyncCore(Byte[] data, CancellationToken cancellationToken) in /_/src/Microsoft.AspNetCore.Sockets.Client.Http/HttpConnection.cs:line 527
 |    at Microsoft.AspNetCore.Sockets.Client.HttpConnection.SendAsync(Byte[] data, CancellationToken cancellationToken) in /_/src/Microsoft.AspNetCore.Sockets.Client.Http/HttpConnection.cs:line 510
 |    at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncCore() in /_/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs:line 125
 |    at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsync() in /_/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs:line 79
 |    at System.Threading.Tasks.TaskExtensions.OrTimeout(Task task, TimeSpan timeout, String memberName, String filePath, Nullable`1 lineNumber) in /_/test/Microsoft.AspNetCore.SignalR.Tests.Utils/TaskExtensions.cs:line 35
 |    at Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests.CanStopAndStartConnection(IHubProtocol protocol, TransportType transportType, String path) in /_/test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/HubConnectionTests.cs:line 122
 | Microsoft.AspNetCore.Sockets.Client.HttpConnection Information: Stopping client.
 | Microsoft.AspNetCore.Sockets.Client.WebSocketsTransport Information: Transport is stopping.
 | Microsoft.AspNetCore.Sockets.Client.WebSocketsTransport Debug: Send loop stopped.
 | Microsoft.AspNetCore.Sockets.Client.WebSocketsTransport Debug: Receive loop canceled.
 | Microsoft.AspNetCore.Sockets.Client.WebSocketsTransport Debug: Receive loop stopped.
 | Microsoft.AspNetCore.Sockets.Client.HttpConnection Trace: Ending receive loop.
 | Microsoft.AspNetCore.Sockets.Client.HttpConnection Debug: Ensuring all outstanding messages are processed.
 | Microsoft.AspNetCore.Sockets.Client.HttpConnection Debug: Draining event queue.
 | Microsoft.AspNetCore.Sockets.Client.HttpConnection Debug: Completing Closed task.
 | Microsoft.AspNetCore.Sockets.Client.HttpConnection Debug: Connection state changed from Connected to Disconnected.
 | Microsoft.AspNetCore.Sockets.Client.HttpConnection Debug: Connection state changed from Disconnected to Disposed.
 | Microsoft.AspNetCore.Sockets.Client.HttpConnection Information: Disposing client.
 | TestLifetime Information: Finished test CanStopAndStartConnection_json_WebSockets_hubT in 0.0252088s
```

**Comment by anurse** [comment] 2018-03-22 19:22
Duplicate of #1586

**Closed by anurse** 2018-03-22 19:22 UTC
Labels: cost: M
