### ISSUE TITLE
Not working with IE11 + Angular

### ISSUE THREAD

**Issue by DannyBoyNg** [aspnet/SignalR#1379] opened 2018-01-31 15:52 UTC
I'm using Angular5/AngularCli1.6.6 on the front-end and AspNetCore 2.0 on the back-end.

Version @aspnet/signalr-client from NPM: 1.0.0-alpha2-final
Version Microsoft.AspNetCore.SignalR from NUGET: 1.0.0-alpha2-final

My Angular app works fine in Chrome, Firefox, Edge, but when I try IE11, nothing works. My app doesn't even load. The console says: SCRIPT1002: Syntax error.

When I remove @aspnet/signalr-client from my app, everything works again in IE11. 

I need IE11 support. Please help.

**Comment by acjh** [comment] 2018-01-31 16:20
Duplicate of #1358

**Comment by BrennanConroy** [comment] 2018-01-31 16:26
Thanks @acjh

**Closed by BrennanConroy** 2018-01-31 16:26 UTC
