### ISSUE TITLE
JSON Serialization is different between DefaultHubLifetimeManager and RedisHubLifetimeManager

### ISSUE THREAD

**Issue by joshlrogers** [aspnet/SignalR#1550] opened 2018-03-07 01:54 UTC
The JSON serializer in the RedisHubLifetimeManager doesn't camelCase the properties of a serialized object where the JSONHubProtocol does if using the DefaultHubLifetimeManager.  This results in breaking changes based on the default settings between the two hubs when doing initial implementation using DefaultHubLifetimeManager then switching to Redis.

**Comment by anurse** [comment] 2018-03-07 02:40
The JSON serializer in the RedisHubLifetimeManager is only used for transmitting payloads between servers over Redis. What is the actual error you are seeing when switching? Is the payload going to the client itself actually broken? Can you provide a simplified repro?

**Comment by joshlrogers** [comment] 2018-03-07 02:53
I see that in the code, but it is not respecting the Serializer settings set in the JSONHubProtocol to use camelcase.

I am working on trying to create a small repo, but I can tell you that I've implemented what is essentially the chat sample and when I replace this line in Startup.cs:

`services.AddSingleton(typeof(HubLifetimeManager<>), typeof(DefaultPresenceHubLifetimeManager<>));`

with this line

`services.AddSingleton(typeof(HubLifetimeManager<>), typeof(RedisPresenceHublifetimeManager<>));`

I start to encounter issues.  I have an object called ChannelEvent:

```
public class ChannelEvent : DomainEvent
    {     
        /// <summary>
        /// The name of the channel the event is associated with
        /// </summary>
        public override string ChannelName { get; }

        public object Data { get; set; }

        public ChannelEvent(string channelName)
        {
            ChannelName = channelName;
        }
    }
```
When using DefaultPresenceHubLifetimeManager the above object is serialized as such:
```
{
   name: '',
   channelName: '',
   data: {},
}
```
However when using the ReditPresenceHubLifetimeManager the above object is serialized as such:
```
{
   Name: '',
   ChannelName: '',
   Data: {},
}
```

So, when handling the event on the JS side, e.name == 'Foo' never works because e.name is undefined rather e.Name == 'Foo' now.

The [Redit|Default]PresenceHubLifetimeManager are both pretty much a copy and paste from the Chat sample.  FYI.

**Comment by anurse** [comment] 2018-03-07 03:05
Yeah, getting a repro would really help identify the issue. The presence lifetime managers are not officially supported, but I don't see any reason why they should cause this to happen so we'd need to dig a little further and see how you're configuring things and what your Hub code looks like.

**Comment by BrennanConroy** [comment] 2018-03-07 15:07
https://github.com/aspnet/SignalR/tree/release/2.1

**Comment by joshlrogers** [comment] 2018-03-07 16:37
I have been able to reproduce the issue, please use the repository:
https://github.com/joshlrogers/SignalR_Serialization_Bug

In doing this I found the issue lies with sending a Group message only.  So when using DefaultHubLifetimeManager this is the frame example:
![image](https://user-images.githubusercontent.com/6315573/37104673-eaab3ed2-21f2-11e8-95dc-f93fec49aa8c.png)

However when using the RedisHubLifetimeManager this is the fame example:
![image](https://user-images.githubusercontent.com/6315573/37104763-24a02f4e-21f3-11e8-89fe-f563a1297653.png)

Please notice the casing difference with the type Group and type All property names compared to the DefaultHubLifetimeManager.

This is the corresponding C# code:
```
public async Task Send(string message)
{
    await Clients.Group(ChannelName).SendAsync("Send", new { Type="Group", User= Context.User.Identity.Name, Message=message});
    await Clients.Client(Context.ConnectionId).SendAsync("Send", new { Type="User", User= Context.User.Identity.Name, Message=message});
    await Clients.All.SendAsync("Send", new { Type="All", User= Context.User.Identity.Name, Message=message});            
}
```

**Comment by anurse** [comment] 2018-03-07 19:14
I'll take a look at your repro and see what I can find. Thanks @joshlrogers !

**Comment by anurse** [comment] 2018-03-13 22:30
I've been able to repro this. Looking at it now

**Comment by anurse** [comment] 2018-03-13 23:35
The problem is that when we send the payload through Redis and deserialize it (even the origin server gets the payload from Redis) it's deserialized as a `Dictionary<string, JToken>`. It looks like the JSON.NET contract resolver logic doesn't kick in by default there.

@joshlrogers can you try the following workaround? In your `ConfigureServices`, after `.AddSignalR`, add `.AddJsonProtocol` and configure the serializer settings like so:

```csharp
services.AddSignalR()
    .AddJsonProtocol(options => options.PayloadSerializerSettings.ContractResolver = new DefaultContractResolver()
    {
        NamingStrategy = new CamelCaseNamingStrategy()
        {
            ProcessDictionaryKeys = true
        }
    })
```

We're going to look at making our default serialization settings set this by default.

**Comment by joshlrogers** [comment] 2018-03-15 15:57
@anurse I have made the request change and I still see a difference in the casing of the property names in my primary project.  I'll attempt to do in my repro and see if it exists there as well.

**Comment by anurse** [comment] 2018-03-15 16:17
Yeah, I actually saw the same behavior trying to make the real change. We're still investigating this one. Disabling camel-casing entirely using the same extension point (`.AddJsonProtocol`) should give you some consistency (though I realize it's not ideal)

**Comment by jsheetzati** [comment] 2018-03-26 19:20
@anurse Any thoughts when preview2 will be released? We are sending deeply nested structures from .NET -> JS through SignalR. We cannot realistically disable camel-casing without a ton of refactor in our client.

**Comment by davidfowl** [comment] 2018-03-31 08:14
Closing this in favor of https://github.com/aspnet/SignalR/issues/1800

**Closed by davidfowl** 2018-03-31 08:14 UTC
Labels: 1 - Ready, bug, cost: L
