### ISSUE TITLE
Route prefix for Hubs

### ISSUE THREAD

**Issue by msmolka** [aspnet/SignalR#1408] opened 2018-02-05 09:43 UTC
I wonder if it would be benefit, to have some Route prefix when configuring Hubs?
Currently as far as I know I need to provide full path for each route.
I think it would be useful to have prefix that would allow simplify versioning similar to web api.
e.g. `/signalr/v1/`

**Comment by anurse** [comment] 2018-02-05 16:36
Since SignalR is a middleware, you can always use [`.Map`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.mapextensions.map?view=aspnetcore-2.0#Microsoft_AspNetCore_Builder_MapExtensions_Map_Microsoft_AspNetCore_Builder_IApplicationBuilder_Microsoft_AspNetCore_Http_PathString_System_Action_Microsoft_AspNetCore_Builder_IApplicationBuilder__) to run SignalR under a specific prefix. We're also discussing adding attribute-based routing similar to MVC controllers (see #146)

**Comment by anurse** [comment] 2018-02-07 20:06
Closing this as a dupe of #146 since we are tracking this there.

**Closed by anurse** 2018-02-07 20:06 UTC
