### ISSUE TITLE
UWP 504 

### ISSUE THREAD

**Issue by hannespreishuber** [aspnet/SignalR#3145] opened 2018-10-17 05:23 UTC
building a prototype
.net core 2.1 MVC -index.html using the chat code sample
SignalR 1.04
start with iisexpress
seem to work (the message encoding doenst)

UWP 16299 min Signalr 1.04
 connection = new HubConnectionBuilder()
 .WithUrl("http://localhost:44350/myhub")
 .Build();
…..
connection.StartAsync();

Exception (nonsense text)
getting POST /myhub/negotiate HTTP/1.1 504 with fiddler

1) reason
2) how to troubleshoot that magic?

**Comment by anurse** [comment] 2018-10-17 14:57
HTTP 504 is a Gateway Timeout. It indicates your server failed to respond. What kind of server are you running? Can you collect server logs as described in the [Diagnostics Guide](https://github.com/aspnet/SignalR/wiki/Diagnostics-Guide)?

**Comment by hannespreishuber** [comment] 2018-10-17 15:36
digginger deeper  -UWP Header
POST http://localhost:44350/myhub/negotiate HTTP/1.1
X-Requested-With: XMLHttpRequest
User-Agent: Microsoft.AspNetCore.Http.Connections.Client/1.0.4-rtm-31024
Host: localhost:44350
Content-Length: 0
Connection: Keep-Alive
Pragma: no-cache

Web Javascript Header
POST https://localhost:44350/myhub/negotiate HTTP/1.1
Host: localhost:44350
Connection: keep-alive
Content-Length: 0
Pragma: no-cache
Cache-Control: no-cache
Origin: https://localhost:44350
X-Requested-With: XMLHttpRequest
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
Content-Type: text/plain;charset=UTF-8
Accept: */*
Referer: https://localhost:44350/
Accept-Encoding: gzip, deflate, br
Accept-Language: de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7

**Comment by hannespreishuber** [comment] 2018-10-17 18:33
ok, found the issue https works http not

**Comment by anurse** [comment] 2018-10-17 18:57
Yeah, Fiddler can produce this error in certain circumstances, and it sounds like that's what's happens. I'll close this issue then.

**Closed by anurse** 2018-10-17 18:57 UTC
Labels: status: Waiting

**Comment by hannespreishuber** [comment] 2018-10-17 19:02
not it works "WITH" fiddler over https, not http - without it works not

**Comment by anurse** [comment] 2018-10-17 19:41
I'm trying to figure out if this needs to be an active SignalR bug or if we can close it. Have you identified a problem with SignalR specifically here? If not, we'll close this.

**Comment by hannespreishuber** [comment] 2018-10-18 05:06
the "non rocket science" prototype
https://github.com/hannespreishuber/WebSignalr

**Comment by anurse** [comment] 2018-10-18 16:43
The problem is that you are using a self-signed SSL certificate in your server so the UWP HTTP client is throwing because it doesn't trust the certificate. If you look at the exception message, this is a lot clearer:

```
System.Exception
  HResult=0x80072F0D
  Message=The text associated with this error code could not be found.

The certificate authority is invalid or incorrect

  Source=System.Private.CoreLib
  StackTrace:
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in E:\A\_work\278\s\src\mscorlib\src\System\Runtime\ExceptionServices\ExceptionDispatchInfo.cs:line 132
```

The dev cert ASP.NET registers isn't produced by a trusted certificate authority, so the UWP HTTP client doesn't trust it. To fix this, you can disable certificate validation in your client. However you should only do this during **development** and remove this configuration when shipping a production application as it is very insecure.

You can disable certificate validation using the following code when you build your `HubConnection`:

```csharp
bool ValidateCertificate(object sender, X509Certificate certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors)
{
    // TODO: You can do custom validation here, or just return true to always accept the certificate.
    // DO NOT use custom validation logic in a production application as it is insecure.
    return true;
}
connection = new HubConnectionBuilder()
     .WithUrl("https://localhost:44350/myhub", options =>
     {
         options.WebSocketConfiguration = (config) =>
         {
             config.RemoteCertificateValidationCallback = ValidateCertificate;
         };
         options.HttpMessageHandlerFactory = (handler) =>
         {
             if (handler is HttpClientHandler clientHandler)
             {
                 clientHandler.ServerCertificateCustomValidationCallback = ValidateCertificate;
             }
             return handler;
         };
     })
```

Note: You have to configure the callback in two places because WebSockets and standard HTTP requests have different configuration parameters for server certificate validation.

**Comment by hannespreishuber** [comment] 2018-10-18 17:58
thank you for support- sounds valid- and fiddler fix it
subquestion is https mandatory or do I have a second issue without ssl?

**Comment by anurse** [comment] 2018-10-18 20:06
I'd recommend you use HTTPS but you're welcome to use either HTTPS or HTTP.
