### ISSUE TITLE
New Nuget Package for Client Core

### ISSUE THREAD

**Issue by mintyfusion** [aspnet/SignalR#1406] opened 2018-02-02 23:45 UTC
Hello Guys,

I was wondering when the new version of Nuget package for client will be released. Last time was early October and we are looking for StopAsync() and that's missing in the last release.

Thanks for all your help.

Harsimrat

**Comment by anurse** [comment] 2018-02-02 23:52
The next version of ASP.NET Core SignalR will be `1.0.0-preview1`. We don't have a specific date for it, but I'd expect it to be a matter of weeks rather than months.

If you want to try nightly builds of the upcoming release, you can find instructions here: https://github.com/aspnet/Home#builds

Please note that the Preview 1 build will be part of ASP.NET Core 2.1, and will **require** that you update your application to ASP.NET Core 2.1. The Alpha builds were designed to work with ASP.NET Core 2.0 (because we hadn't released 2.1 yet).

**Comment by mintyfusion** [comment] 2018-02-03 00:09
Thanks you for the quick response. I'm confused with .NET Core 2.1.0

Looking at public roadmap and it won't be available until Q2 2018 : https://github.com/aspnet/Home/wiki/Roadmap

I was wondering would you use beta and build on that?

**Comment by anurse** [comment] 2018-02-03 18:26
The RTM release of 2.1.0 is expected in Q2 2018. Preview releases for 2.1 will be coming out relatively soon, we've actually already branched and locked the code for Preview 1 (the exact shipping date is not confirmed, but it'll be fairly soon).

The biggest risk with starting to use beta/preview builds now is that things may change significantly before RTM. We make every effort to ensure that breaking changes between previews are minimal and well documented, but since we're still trying to smooth things out and get the right experience, we do make dramatic changes sometime. For SignalR, I think the core APIs are fairly solid as we're basing them on the previous versions of SignalR for ASP.NET (non-Core).

**Closed** 2018-03-31 08:49 UTC
