### ISSUE TITLE
Add version to SignalR JavaScript client (signalr.js)

### ISSUE THREAD

**Issue by rachelappel** [aspnet/SignalR#2251] opened 2018-05-11 11:18 UTC
Add version to SignalR JavaScript client (signalr.js)

In [issue 6340](https://github.com/aspnet/Docs/issues/6340) a customer asks about the SignalR version in the JS client. A few customers have mentioned it elsewhere at conferences and such. It would be far easier to tell what's going on if you are just handed a project to support and the file is in there.

Is it something the team can add in? 

@anurse  @BrennanConroy  @mikaelm12  @JamesNK

**Comment by davidfowl** [comment] 2018-05-11 14:07
Happening here https://github.com/aspnet/SignalR/pull/2229

**Comment by anurse** [comment] 2018-05-11 16:06
Closing this as a duplicate of https://github.com/aspnet/SignalR/issues/2130

**Closed by anurse** 2018-05-11 16:06 UTC
