### ISSUE TITLE
AuthorizationHandlerContext.Resource is always null in authorization handler when connecting to SignalR hub

### ISSUE THREAD

**Issue by DaRosenberg** [aspnet/SignalR#2831] opened 2018-08-18 00:39 UTC
We are using a `Hub<T>` server-side in our ASP.NET Core 2.1 app. Connecting to this hub requires authorization, so we apply the `AuthorizeAttribute` to it, with a named policy:

```cs
[Authorize(Startup.ScopeReadAuthorizationPolicyName)]
public class NotificationHub : Hub<INotificationClient>
{
```

Our registered `AuthorizationHandler<T>` is correctly invoked to handle the authorization requirements of the policy, whenever a client tries to connect to the hub - so far so good.

However, the `AuthorizationHandlerContext.Resource` property (of the `context` parameter passed to the authorization handler) is always `null `in these cases, i.e. when the authorization handler is called for the hub. In normal MVC requests to our controllers, this property contains a reference to an `AuthorizationFilterContext` instance, which allows us to evaluate the authorization in relation to what's actually being passed in the request, which is a requirement for our service.

Is this is a SignalR omission, or is there any other way we can get access to the query string used to connect to the hub, from the context of our authorization handler?

* Versions of Server-Side NuGet Packages: **1.0.2**
* Versions of Client-Side NuGet/NPM Packages: **1.0.2**
* Are you using the C# client or the JavaScript client: **C#**
* The Server you are using (Kestrel/HttpSysServer/IIS/IIS Express/Azure Web App/etc.): **Kestrel**
* The Operating System on the Server (Windows/Linux/macOS): **Windows and Linux**
* The Operating System on the Client (Windows/Linux/macOS): **iOS (Xamarin.iOS)**

**Comment by BrennanConroy** [comment] 2018-08-18 01:01
Dupe of https://github.com/aspnet/SignalR/issues/676. Comment on that issue with your scenario and we'll see if it can be moved from backlog 😄

**Closed by BrennanConroy** 2018-08-18 01:01 UTC

**Comment by DaRosenberg** [comment] 2018-08-19 14:58
Thanks @BrennanConroy, will do.
