### ISSUE TITLE
Problem with INegotiateResponse in JavaScript client

### ISSUE THREAD

**Issue by jayarjo** [aspnet/SignalR#2534] opened 2018-06-25 07:05 UTC
From what I see `INegotiateResponse` expects a server response with camelcased properties but with lowercase first letter (`return JSON.parse(response.content as string) as INegotiateResponse;`).

```typescript
export interface INegotiateResponse {
    connectionId?: string;
    availableTransports?: IAvailableTransport[];
    url?: string;
    accessToken?: string;
}
```

Is the response format some kind of SignalR standard? 'cause we have at least one third-party SignalR server that sends the following negotiate response:

```
ConnectionId:"...id follows..."
ConnectionTimeout:110
ConnectionToken:"+...token follows..."
DisconnectTimeout:30
KeepAliveTimeout:20
LongPollDelay:0
ProtocolVersion:"1.2"
TransportConnectTimeout:5
TryWebSockets:true
Url:"/signalr"
```
I believe to avoid the obvious error properties should be normalized first or always lowercased.

**Comment by jayarjo** [comment] 2018-06-25 07:17
Actually I see now that response formats are different (e.g. `accessToken` vs. `ConnectionToken` ).

**Comment by jayarjo** [comment] 2018-06-25 07:56
Forked and tried to monkey-patch it, however it seems that there is major incompatibility problem far beyond property naming. Maybe you should reflect it somehow in the documentation.

**Comment by anurse** [comment] 2018-06-25 14:52
The response you're seeing is from an ASP.NET SignalR server (i.e. `Microsoft.AspNet.SignalR`). This repository and client only supports ASP.NET **Core** SignalR (`Microsoft.AspNetCore.SignalR`). If you are running an ASP.NET SignalR server (non-Core), you should use the `signalr` npm package (https://www.npmjs.com/package/signalr) rather than `@aspnet/signalr`

**Comment by anurse** [comment] 2018-06-25 14:55
Closing this issue for now, since it looks like this is a version mismatch. Feel free to comment further if you need assistance or if there is still an issue to resolve. Note that ASP.NET SignalR (non-Core) work is tracked at github.com/SignalR/SignalR if you do encounter an issue after aligning the versions.

**Closed by anurse** 2018-06-25 14:55 UTC

**Comment by jayarjo** [comment] 2018-06-25 15:13
I know SignalR is kind of your inbreed project for mostly ASP.NET community, but it is a great concept in general, so maybe you guys should consider to make it a bit less confusing. Just saying.

**Comment by jayarjo** [comment] 2018-06-25 15:28
@anurse wait a second... aren't you redirecting me to some legacy version now (one that was internally dependent on jQuery?), I thought it was deprecated in favor of this one (at least I think that's the impression I got from one tech talk on YouTube - can't find it now, but it was these two guys talking: https://www.youtube.com/watch?v=u0_vkWYYXRc)?

**Comment by anurse** [comment] 2018-06-25 16:53
You've mostly got it correct, the issue is that you're mixing versions. The ASP.NET Core SignalR client (`@aspnet/signalr` on NPM) is **not compatible** with the ASP.NET SignalR (non-Core) server (`Microsoft.AspNet.SignalR`). There are significant protocol and design changes (which is why both continue to be maintained).

What kind of server application are you running? Is it an ASP.NET 4.x application (using System.Web)? Is it a self-hosted console application (using `Microsoft.AspNet.SignalR.SelfHost`)? If you can tell me more about your application, it's easier for me to identify what the source of the confusion might be.

**Comment by jayarjo** [comment] 2018-06-25 18:32
I do not control the server-side unfortunately. But confusion is general. Also I'm not an ASP.NET guy myself at all, so this might be adding to the confusion. I learned about SignalR accidentally and had a hard time picturing the concept in its entirety in my head. Documentation is scarce, especially on the front-end side - had to read through the actual code. And now there's this conflict of versions that I've not seen mentioned anywhere. So not obvious to say at least :)

However I like the idea in general. It has a potential of becoming a universal way of communication between client and server, across systems and programming languages.

**Comment by anurse** [comment] 2018-06-25 18:42
ASP.NET SignalR wasn't really designed to be a general-purpose API like this, it didn't have a documented protocol (so writing third-party clients was very difficult) which is one reason this confusion can come up.

ASP.NET Core SignalR is trying to solve those problems, but as a result it has breaking changes. Anyway, in your case, the solution is pretty simple, you just need to use the right client. It could be more obvious, we're working on our docs to make that better, but alas this is sometimes how it goes during transitions like this :). To solve your specific issue, the client you want is available on NPM as `signalr` (https://www.npmjs.com/package/signalr), **not** `@aspnet/signalr`.

Hope that helps resolve some of the confusion. Feel free to reach out if you have more questions!
