### ISSUE TITLE
Considerations that need to be taken with long running connections?

### ISSUE THREAD

**Issue by pielegacy** [aspnet/SignalR#3147] opened 2018-10-18 00:38 UTC
For a project I am working on we rely on SignalR Core to act as a connection between our API and a processing agent that is installed on the clients workstation.

Our product basically sends _"tasks"_ for the agent to execute over SignalR Core, these tasks are scheduled with Hangfire and the most frequent of which is a task that runs every 10 minutes. This works as expected usually however with a particular client their agent appears to not be able to receive jobs at all after around 24 hours of the agent being active.

The code for sending the task does nothing special, the `agent.ConnectionId` value is updated by the agent every minute being sending a message over SignalR which updates the _"heartbeat"_ of the agent to the current time in UTC as well as setting the `ConnectionId` to the HttpContext ID of that particular SignalR connection.

```cs
_taskLogger.LogInformation("Preparing task monitor.", taskExecutionId);
async void MonitorAgentTimeout()
{
    var startTime = DateTime.UtcNow;
    while (!taskFinished)
    {
        await Task.Delay((int)_agentconnectiontimeout.TotalMilliseconds);

        if (!taskFinished)
        {
            var agent2 = await _unitOfWork.Repository<Agent>().GetByIdAsync(agentId, true);
            if (agent2.HeartBeat <= DateTime.UtcNow.AddMilliseconds(-1 * _agentconnectiontimeout.TotalMilliseconds))
            {
                _taskLogger.LogError($"Connection to agent lost, cancelling task.", taskExecutionId);
                CancelTaskExecution();
                break;
            }
            else if (startTime + _taskTimeout < DateTime.UtcNow)
            {
                _taskLogger.LogError($"Task execution timed out, cancelling task.", taskExecutionId);
                CancelTaskExecution();
                break;
            }
            else
            {
                _taskLogger.LogInformation($"'{task.Task.TaskName}' is still executing...", taskExecutionId);
            }
        }
    }
}

_taskLogger.LogInformation($"Sending task to '{agent.HostName}'.", taskExecutionId);
MonitorAgentTimeout();
await _taskQueueHubContext.Clients.Client(agent.ConnectionId).BroadcastMessage(
    encryptionMessage.FollowUpWith(new SignalRMessageTransferDto<string>() { Value = taskQueueMessageEncrypted, TaskExecutionId = taskExecutionId }));
```

Looking at the SignalR Diagnostic logs on the agent, it seems the message never reaches the agent and so the task execution gets stuck at the log message _"Sending task to Agent-Host"_. 

My question is not necessarily how do I fix my problem but whether there is a need for me to perform any additional steps with this long running connection. I don't see much documentation about it and I'm already restarting the SignalR Core connection from the agent end every 24 hours just to be sure so it's been hard diagnosing the root of the problem.

**Comment by davidfowl** [comment] 2018-10-18 04:31
> My question is not necessarily how do I fix my problem but whether there is a need for me to perform any additional steps with this long running connection. I don't see much documentation about it and I'm already restarting the SignalR Core connection from the agent end every 24 hours just to be sure so it's been hard diagnosing the root of the problem.

Networking is hard. Its hard to know what the problem might be without logs of both the server and client. If you want the client to stay alive you do need to write code to reconnect when the connection drops. [This code](https://github.com/aspnet/SignalR/blob/b0f7fbbe9920ec789a18328a5f96df3706d57356/samples/ClientSample/HubSample.cs#L60-L150) shows a basic example of doing that in a console application.

>I'm not sure if this will help in any way but it does mean that the BroadcastMessage message event is await for a fraction of the time of what it used to be awaited for with the same functionality.

This is a good change in general. You don't want to hold up the event loop on the client side as that will stop other messages from being sent to the client. It can also result in async dead locks if InvokeAsync is called inside of the handler.

PS: I would avoid using async void and use async Task instead. You can always ignore the returned Task from the method but you should generally avoid using async void altogether.

**Comment by pielegacy** [comment] 2018-10-18 04:35
Thanks David, I'll implement the Task recommendation. We've managed to re-create the issues several times on a basic tier development instance of the API and it seems to always be occurring at `await _taskQueueHubContext.Clients.Client(agent.ConnectionId).BroadcastMessage(
    encryptionMessage.FollowUpWith(new SignalRMessageTransferDto<string>() { Value = taskQueueMessageEncrypted, TaskExecutionId = taskExecutionId }));`. The client never receives the message either and it ultimately just holds up the task indefinitely.

**Comment by davidfowl** [comment] 2018-10-18 04:49
I'm not sure what you mean by "it ultimately just holds up the task indefinitely.". The Task returned from that method doesn't return when the client receives the message. There's no way to wait on the client to receive a message unless you implement that yourself (see https://github.com/aspnet/SignalR/issues/903).

If you can reproduce the issue at will then I suggest following the [diagnostic guide](https://github.com/aspnet/SignalR/wiki/Diagnostics-Guide ) in the issue template.

**Comment by pielegacy** [comment] 2018-10-18 05:11
Sorry what I meant by that was that any code after that BroadcastMessage will never be reached, for example the task completion source after the broadcast here will never get touched and the message being broadcasted doesn't reach the agent:

```cs
await _taskQueueHubContext.Clients.Client(agent.ConnectionId).BroadcastMessage(
    encryptionMessage.FollowUpWith(new SignalRMessageTransferDto<string>() { Value = taskQueueMessageEncrypted, TaskExecutionId = taskExecutionId }));

try
{
    var returnData = await tcs.Task;
    return returnData;
}
```

I followed the guide and got debug logs for the agent, I feel the server wasn't properly capturing the debug level logging from signalr but I'll send them for context.

[serverlogs.txt](https://github.com/aspnet/SignalR/files/2490283/serverlogs.txt)
[clientlogs.txt](https://github.com/aspnet/SignalR/files/2490284/clientlogs.txt)

 One thing to note is that after _Task Completed_ the SignalR client kept logging `Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport` messages in an almost infinite loop.

**Comment by pielegacy** [comment] 2018-10-18 05:46
Managed to get a better set of logs, note the disconnected exception in the clientlogs.txt was due to me attaching the remote debugger to the Azure App Service.

[serverlogs.txt](https://github.com/aspnet/SignalR/files/2490371/serverlogs.txt)
[clientlogs.txt](https://github.com/aspnet/SignalR/files/2490372/clientlogs.txt)

One thing to note is that we are unable to send any other messages to the agent over `BroadcastMessage` until we restart the client entirely.

**Comment by davidfowl** [comment] 2018-10-18 16:37
> for example the task completion source after the broadcast here will never get touched and the message being broadcasted doesn't reach the agent:

I believe you, but that isn't necessarily related to SignalR. You need to share more code to that I understand when that TCS gets triggered.

> One thing to note is that we are unable to send any other messages to the agent over BroadcastMessage until we restart the client entirely.

Isn't that just a result of how your code is put together? 

Can you throw together a sample of what you're actually doing. It's hard to glean anything from you code snippets and I sense there's something more complex here going on.

**Comment by pielegacy** [comment] 2018-10-18 22:16
Okay here are some larger snippets of what's going on, we've made the logging more verbose to pin point where the execution halts and you're right in saying that the code does completely execute `BroadcastMessage` on the API end and actually stalls at `await tcs.Task`. 

`SendTaskToAgent Snippet` (Serverend)
```cs
_taskLogger.LogInformation($"Configuring task listener for receiving task status.", taskExecutionId);
//send message to agent and wait for executionvar tcs = new TaskCompletionSource<SignalRMessageTransferDto<String>>();
var tcs = new TaskCompletionSource<SignalRMessageTransferDto<string>>();
if (!_connectionManager.TryGetConnection(agent.ConnectionId, out HttpConnectionContext connectionCntxt))
{
    throw new Exception("Unable to connect to agent, this may be due to a previous fatal error. Please ensure the agent is active or restart the agent's service.");
}
_taskLogger.LogInformation($"Attaching task listener for receiving task status.", taskExecutionId);
connectionCntxt.Items.Add("tcsTask_" + taskExecutionId, tcs);
_taskLogger.LogInformation($"Task listener attached...", taskExecutionId);
bool taskTimeout = false, taskFinished = false;

//void CancelTaskExecution()
//{
//    taskTimeout = true;
//    tcs.SetCanceled();
//}

// TODO: Re-enable when required
//_taskLogger.LogInformation("Preparing task monitor...", taskExecutionId);
//async void MonitorAgentTimeout()
//{
//    try
//    {
//        var startTime = DateTime.UtcNow;
//        while (!taskFinished)
//        {
//            await Task.Delay((int)_agentconnectiontimeout.TotalMilliseconds);

//            if (!taskFinished)
//            {
//                var agent2 = await _unitOfWork.Repository<Agent>().GetByIdAsync(agentId, true);
//                if (agent2.HeartBeat <= DateTime.UtcNow.AddMilliseconds(-1 * _agentconnectiontimeout.TotalMilliseconds))
//                {
//                    _taskLogger.LogError($"Connection to agent lost, cancelling task.", taskExecutionId);
//                    CancelTaskExecution();
//                    break;
//                }
//                else
//                {
//                    _taskLogger.LogInformation($"'{task.Task.TaskName}' is still executing...", taskExecutionId);
//                }
//            }
//        }
//    }
//    catch (Exception ex)
//    {
//        _taskLogger.LogError(ex, "Task monitor failed to configure, cancelling job...", taskExecutionId);
//        CancelTaskExecution();
//    }
//}
//MonitorAgentTimeout();
//_taskLogger.LogInformation("Task monitor configured.", taskExecutionId);

_taskLogger.LogInformation($"Preparing task to to be sent to '{agent.HostName}", taskExecutionId);
SignalRMessageTransferDto<string> taskToSend = encryptionMessage.FollowUpWith(new SignalRMessageTransferDto<string>() { Value = taskQueueMessageEncrypted, TaskExecutionId = taskExecutionId });
_taskLogger.LogInformation($"Retrieving reference to '{agent.HostName}' with context ID '{agent.ConnectionId}", taskExecutionId);
ITaskQueuesHub relatedClient = _taskQueueHubContext.Clients.Client(agent.ConnectionId);
_taskLogger.LogInformation($"Sending task to '{agent.HostName}'.", taskExecutionId);
await relatedClient.BroadcastMessage(taskToSend);
_taskLogger.LogInformation($"Task sent to '{agent.HostName}', awaiting completion.", taskExecutionId);

try
{
    var returnData = await tcs.Task;
    _taskLogger.LogInformation($"Task successfully executed on '{agent.HostName}'.", taskExecutionId);
    return returnData;
}
catch (Exception e)
{
    _taskLogger.LogInformation($"Task failed execution on '{agent.HostName}'. Reason: {e}", taskExecutionId);
    if (taskTimeout)
        return new SignalRMessageTransferDto<string>() { ErrorMessage = "Connection to agent lost, cancelling the job." };
    else
        return new SignalRMessageTransferDto<string>() { ErrorMessage = e.Message };
}
finally
{
    _taskLogger.LogInformation($"Task completed execution on '{agent.HostName}'.", taskExecutionId);
    connectionCntxt.Items.Remove("tcsTask_" + taskExecutionId);
    _taskLogger.LogInformation($"Task context cleanup for '{agent.HostName}'.", taskExecutionId);
    taskFinished = true;
}
```

`"BroadcastMessage"` Listener (This never gets called with our bug)

```cs
connection.On<SignalRMessageTransferDto<string>>("BroadcastMessage", async message =>
{
    var encryptionPair = TakeEncryptionPairForMessage(message);
    var taskQueueEncrypted = await encryptionPair.DecryptAsync(_serviceCryptography.CryptoServiceProvider, message.Value);
    var taskQueue = JsonConvert.DeserializeObject<TaskQueueContainerDto>(taskQueueEncrypted);
    ProcessTask(message, taskQueue);
}
```

`TaskCompleted` (This gets called by the agent when the task is finished)

```cs
/// <summary>
/// 
/// </summary>
/// <param name="data"></param>
/// <returns></returns>
public Task TaskCompleted(SignalRMessageTransferDto<string> data)
{
    //set taskqueue completion
    var taskQueue = _uow.Repository<TaskQueue>().GetById(data.TaskQueueId);
    taskQueue.DateCompleted = DateTime.UtcNow;
    _uow.Save();
    Context.Items.TryGetValue("tcsTask_" + taskQueue.TaskExecutionId, out object obj);
    if (obj != null)
    {
        //if we still have tcsTask in context, that means it hasn't timed out. (<5mins)
        var tcs = (TaskCompletionSource<SignalRMessageTransferDto<string>>)obj;
        tcs.SetResult(data);
    }
    return Task.CompletedTask;
}
```

**Comment by davidfowl** [comment] 2018-10-19 07:10
> One thing that's also worth noting is that the agent sends a heartbeat every minute over the same SignalR connection that is used to listen for tasks.

Those heartbeats are received on the server side as invocations? Are they client to server pings?

If you can reproduce the issue rather reliably, adding logging that tracks your custom task tracking system coupled with the SignalR logs should help you track down exactly what things ran up until the hang.

At a super high level, things like this that can cause issues:
- You cannot block the callback on the client side, asynchronously or synchronously. You will end up blocking the client side event loop and you will no longer receive any other messages. 
- If you await `connection.InvokeAsync` inside of the client side callback then it will hang the client logic. The event loop on the client will be blocked and the invoke needs that connection to complete the task returned (classic deadlock but async).
- If you block asynchronously or synchronously in a server side hub method, you will not be able to call any other methods on that same connection. We don't support overlapping calls to the hub on the same connection.
- When you call TaskCompletionSource.SetResult(), it will resume the await on the **same thread** as the one calling SetResult. If you are running some other code on that thread you never expected to run, it can cause these sorts of async dead locks.  Your TaskCompletionSource should be created with `TaskCreationOptions.RunContinuationsAsynchronously`

1. Given that, I'd look at a few things. Look at the code that runs as part of calling SetResult. 
2. Look at your event handlers on the client side to see if any are waiting for a long time on something else.

**Comment by pielegacy** [comment] 2018-10-19 07:14
I will look into these Monday, thanks David 😊 I can close this issue if you’d like only as the scope of what I originally asked for help with has definitely expanded

**Comment by anurse** [comment] 2018-10-19 15:46
Sure, let's close this for now, but please feel free to keep commenting and we can help try to track this down. If we identify an issue in SignalR, we can open an issue to track it :).

**Closed by anurse** 2018-10-19 15:46 UTC

**Comment by anurse** [comment] 2018-10-19 15:48
I filed https://github.com/aspnet/SignalR/issues/3159 because the deadlock between Invoke and On handlers has come up a few times so we should resolve that somehow.

**Comment by pielegacy** [comment] 2018-10-19 19:35
Awesome, thanks guys for your help it’s been super beneficial
