### ISSUE TITLE
UTF-8 cyrillic strings cause System.FormatException

### ISSUE THREAD

**Issue by romanov** [aspnet/SignalR#669] opened 2017-07-16 17:24 UTC
It's impossible to send pure strings with any cyrillic letters.

Steps to reproduce:

1. Hub method
`public async Task Say(string text)`
2. Client.js
`_connection.send("Say", "тест");`

Server debug shows that:
`System.FormatException: Missing delimiter ';' after payload`

Is it a JSON serialization issue?

**Comment by davidfowl** [comment] 2017-07-16 17:26
This is a dupe of https://github.com/aspnet/SignalR/issues/550.

**Closed by davidfowl** 2017-07-16 17:26 UTC
