### ISSUE TITLE
Windows detection

### ISSUE THREAD

**Issue by JamesNK** [aspnet/SignalR#3182] opened 2018-10-23 20:08 UTC
Does this https://github.com/aspnet/Extensions/pull/424 issue apply to these places: https://github.com/aspnet/SignalR/search?q=Environment.OSVersion.Version&type=Code

**Comment by JamesNK** [comment] 2018-10-24 19:51
It is also used by the .NET client to determine whether the client supports websockets - https://github.com/aspnet/SignalR/blob/78a0a68cd161e91e80d740e39e8548532e236d5d/src/Microsoft.AspNetCore.Http.Connections.Client/HttpConnection.cs#L574-L592

**Comment by anurse** [comment] 2018-10-26 17:42
Take a quick look at this @BrennanConroy in case we need to make this change in our prod code.

**Comment by anurse** [comment] 2018-10-30 23:34
I took a look and we should be OK. The problem is that OS Version gets fuzzy between Windows 8 and Windows 10. However, we just need to be able to detect we're on **at least Windows 8**, which we are able to do.

I'm comfortable closing this until we hear customer feedback that there's an issue here.

**Closed by anurse** 2018-10-30 23:34 UTC
Labels: PRI: 2 - Preferred, type: Bug
