### ISSUE TITLE
Websocket connection closes with error code 1007

### ISSUE THREAD

**Issue by SimonChris** [aspnet/SignalR#2323] opened 2018-05-19 10:53 UTC
I am making a simple collaborative editor, in which the user types text into a HTML TextArea, which is then sent to the other users. 

I am using the newest RC1 build of SignalR Core, with the JavaScript client.

The onChange handler on the TextArea transmits the content of the TextArea to the other users like this:

`this.hubConnection.invoke('SendContent', contentString)`, where contentString is the value property of the TextArea.

The C# hub function looks like this

`public async Task SendContent(string text)
{
        _contentString = text;
        await Clients.Others.SendAsync("ReceiveContent", _contentString);
}`

This works fine at first, but after 20-30 seconds of typing, the connnection aprubtly closes with the error message:

`Connection disconnected with error 'Error: Websocket closed with status code: 1007 ()'.`

Looking up error code 1007, it seems like the string is not UTF-8 encoded, but that doesn't really makes sense, since it works at first, but just fails randomly later. Also, after reestablishing connection, I can send the same string with no problems. This happens consistently after less than a minute of typing. The error occurs even if I comment out all the code in the hub function, so it's definitely a problem with the connection.

Turning on Trace logging just shows that a bunch of text is being transmitted over the websocket connection, but no clue as to why it suddenly closes.

The connection is running behind an IIS server and the error also happens using IIS Express from Visual Studio.

I've reproduced the problem on both Chrome and Edge.

I have made things work for now by enforcing SSE transport, but I would prefer to be able to use websockets. I have no problem using websockets with any of my other SignalR hubs, maybe because they don't send as much data as quickly?

**Comment by SimonChris** [comment] 2018-05-19 14:08
Testing some more, it seems like this is related to using non-standard characters, such as the nordic letters æøå. If I simply hold down one of those buttons for a few seconds, the websocket disconnects, whereas using standard letters does not cause any issues.

The odd thing is that I still cannot reproduce the issue with any specific string. I have to type in non-standard letters for at least a few seconds before anything happens.

**Comment by SimonChris** [comment] 2018-05-19 15:00
Steps to reproduce for people without nordic keyboards:
1) Create an input element or a textarea with an onChange handler that submits the entire content to a a SignalR hub function that accepts a string, through a websocket connection.
2) Copy-paste the following string into the input element: "æææææææææææææææææææææææææææææææææææææææææææææææææææææææææææææææææææææææææææææææææææææææææææææææææææææææææææææææææææææææ"
3) Type random crap for a few seconds.
The websocket connection should now disconnect with an error code 1007.

The funny thing is that I need a relative large amount of nordic triggers to trigger the issue. It's not enough with just a few at the beginning.

**Comment by anurse** [comment] 2018-05-19 17:01
Could you collect some of the logs suggested by the [Diagnostics Guide](https://github.com/aspnet/SignalR/wiki/Diagnostics-Guide)? 

It would be particularly useful to get a network trace, as that might show what data is triggering the issue. The fact that you're seeing a UTF-8 encoding error when using certain characters would indicate that the problem is that a multi-byte UTF-8 character is getting split between two messages improperly somewhere.

**Comment by davidfowl** [comment] 2018-05-19 18:08
Isn’t this the issues we fixed in RTM?

**Comment by anurse** [comment] 2018-05-19 20:06
Good point, it might be https://github.com/aspnet/SignalR/issues/2187

@SimonChris could you try one of the RTM candidate builds referenced here: https://github.com/dotnet/versions/tree/master/build-info/dotnet/product/cli/release/2.1-rtm and see if that fixes your issue?

**Comment by SimonChris** [comment] 2018-05-20 09:01
I have installed the RTM candidates on my development machine, but this does not make any difference. Do I need to do something more than simply install them? Visual Studio does recognize that it is now using the 2.1.300 SDK and shows some obsolete refences warning.

I will try to make the diagnostics logs.

**Comment by davidfowl** [comment] 2018-05-20 09:03
What does your project file look like?

**Comment by SimonChris** [comment] 2018-05-20 09:18
You mean the .csproj file? Like this:
`<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net461</TargetFramework>
    <RuntimeIdentifier>win7-x86</RuntimeIdentifier>
  </PropertyGroup>

  <PropertyGroup>
    <UserSecretsId>aspnet-JuraDemo-28fc7a4a-09f9-4f2d-a9aa-a7753650ad51</UserSecretsId>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="BuildBundlerMinifier" Version="2.7.385" />
    <PackageReference Include="FileHelpers" Version="3.2.7" />
    <PackageReference Include="Google.Apis.Auth" Version="1.33.1" />
    <PackageReference Include="iTextSharp" Version="5.5.13" />
    <PackageReference Include="itextsharp.xmlworker" Version="5.5.13" />
    <PackageReference Include="Magick.NET-Q16-AnyCPU" Version="7.4.5" />
    <PackageReference Include="MailKit" Version="2.0.3" />
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.3.0-beta2" />
    <PackageReference Include="Microsoft.AspNetCore" Version="2.1.0-rc1-final" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Cookies" Version="2.1.0-rc1-final" />
    <PackageReference Include="Microsoft.AspNetCore.Cors" Version="2.1.0-rc1-final" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="2.1.0-rc1-final" />
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.1.0-rc1-final" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="2.1.0-rc1-final" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.1.0-rc1-final" />
    <PackageReference Include="Microsoft.AspNetCore.Rewrite" Version="2.1.0-rc1-final" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.0.0-rc1-final" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="2.1.0-rc1-final" />
    <PackageReference Include="Microsoft.CodeAnalysis" Version="2.8.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.1.0-rc1-final" PrivateAssets="All" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.1.0-rc1-final" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer.Design" Version="2.0.0-preview1-final" PrivateAssets="All" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.1.0-rc1-final" PrivateAssets="All" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="2.1.0-rc1-final" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="2.1.0-rc1-final" />
    <PackageReference Include="Microsoft.Extensions.Primitives" Version="2.1.0-rc1-final" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.1.0-rc1-final" PrivateAssets="All" />
    <PackageReference Include="Microsoft.VisualStudio.Web.BrowserLink" Version="2.1.0-rc1-final" />
    <PackageReference Include="Microsoft.WindowsAzure.ConfigurationManager" Version="3.2.3" />
    <PackageReference Include="NReco.PdfRenderer" Version="1.1.2" />
    <PackageReference Include="OpenXmlPowerTools" Version="4.5.3.2" />
    <PackageReference Include="Pdfbox" Version="1.1.1" />
    <PackageReference Include="React.AspNet" Version="3.3.0" />
    <PackageReference Include="SendGrid" Version="9.9.0" />
    <PackageReference Include="Stripe.net" Version="11.9.0" />
    <PackageReference Include="Tesseract" Version="3.0.2" />
    <PackageReference Include="Twilio" Version="5.13.1" />
    <PackageReference Include="WindowsAzure.Storage" Version="9.1.1" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="1.0.0" />
    <DotNetCliToolReference Include="Microsoft.Extensions.SecretManager.Tools" Version="1.0.0" />
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="1.0.0" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Select.HtmlToPdf">
      <HintPath>Assemblies\Select.HtmlToPdf.dll</HintPath>
    </Reference>
    <Reference Include="WindowsBase" />
  </ItemGroup>
  <ItemGroup>
    <Content Update="wwwroot/LexaaBooking-fd5e4c0d5e50.p12">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <None Update="Assemblies\liblept172.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Assemblies\libtesseract304.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Assemblies\Select.Html.dep">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
    </None>
    <None Update="tessdata\chi_sim.traineddata">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="tessdata\chi_tra.traineddata">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="tessdata\dan.traineddata">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="tessdata\dan_frak.traineddata">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="tessdata\eng.cube.bigrams">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="tessdata\eng.cube.fold">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="tessdata\eng.cube.lm">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="tessdata\eng.cube.nn">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="tessdata\eng.cube.params">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="tessdata\eng.cube.size">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="tessdata\eng.cube.word-freq">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="tessdata\eng.tesseract_cube.nn">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="tessdata\eng.traineddata">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="tessdata\enm.traineddata">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="x64\liblept172.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="x64\libtesseract304.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="x86\liblept172.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="x86\libtesseract304.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <DotNetCliToolReference Include="Microsoft.Extensions.SecretManager.Tools" Version="1.0.1" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="FrontEnd\" />
    <Folder Include="tessdata\">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Folder>
  </ItemGroup>

</Project>`

I am using ASP.Net Core, but targeting .NET 4.6.

**Comment by SimonChris** [comment] 2018-05-20 09:29
Here is a server log.
[ServerLog.txt](https://github.com/aspnet/SignalR/files/2020200/ServerLog.txt)

**Comment by SimonChris** [comment] 2018-05-20 09:39
Client log and network trace.
[ClientLog.log](https://github.com/aspnet/SignalR/files/2020208/ClientLog.log)
[localhost.txt](https://github.com/aspnet/SignalR/files/2020209/localhost.txt)

**Comment by davidfowl** [comment] 2018-05-20 09:42
Ah, if you're using .NET Framework then you need to update the packages and that installer we gave you won't help. You can try using the myget feed here https://dotnet.myget.org/feed/dotnet-core/package/nuget/Microsoft.AspNetCore.SignalR

**Comment by SimonChris** [comment] 2018-05-20 09:53
When I try to install the package, I get a ton of downgrade warnings like this:
`Install-Package : NU1605: Detected package downgrade: Microsoft.Extensions.Primitives from 2.1.0-rtm-30796 to 2.1.0-rc1-final. Reference the package directly from 
the project to select a different version. `

This warning is repeated several times and then the install is rolled back. How can I resolve this?

**Comment by SimonChris** [comment] 2018-05-20 13:51
I managed to disable the error message and install the package. NuGet now says I'm running:

`Microsoft.AspNetCore.SignalR (1.0.0-rtm-30796)`

Unfortunately, the error still occurs. The websocket connection disconnects with an error code 1007.

I don't suppose there is a similar update for the JavaScript client?

**Comment by davidfowl** [comment] 2018-05-20 15:04
Ok there might be another error. Can you show your project file after the upgrade?

**Comment by SimonChris** [comment] 2018-05-20 15:31
[Project.txt](https://github.com/aspnet/SignalR/files/2020423/Project.txt)

The only difference from before the upgrade is the line:

`<PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.0.0-rtm-30796" />`

**Comment by davidfowl** [comment] 2018-05-21 06:17
The reason for the downgrade errors is because SignalR requires a newer version of ASP.NET Core (2.1 to be specific). You can work around that by updating  2.1.0-rc1-final to 2.1.0-rtm-30796 for the Microsoft.AspNetCore.* and Microsoft.Extensions.* packages.

Since the issue is still occuring though it looks like it might be something different causing things to fail.

Coming back to this:

> Connection disconnected with error 'Error: Websocket closed with status code: 1007 ()'.

> Looking up error code 1007, it seems like the string is not UTF-8 encoded, but that doesn't really makes sense, since it works at first, but just fails randomly later. Also, after reestablishing connection, I can send the same string with no problems. This happens consistently after less than a minute of typing. The error occurs even if I comment out all the code in the hub function, so it's definitely a problem with the connection.

It might be a bug in the underlying websocket logic or an issue with how we're sending data over the websocket.

**Comment by davidfowl** [comment] 2018-05-21 06:27
@SimonChris are you using IIS?

**Comment by davidfowl** [comment] 2018-05-21 06:28
@SimonChris Actually, can you fill out the issue template? It asks a bunch of questions about environment that we need to move forward here. You can see it here https://github.com/aspnet/SignalR/blob/dev/.github/ISSUE_TEMPLATE.md

**Comment by davidfowl** [comment] 2018-05-21 06:30
Looks like the only place 1007 is returned is deep within the guts of the websocket implementation as it's trying to validate that the payload is valid UTF8 https://github.com/dotnet/corefx/blob/3326f3f24dd083f0966c8f71c7d1e8c2caa1ddae/src/Common/src/System/Net/WebSockets/ManagedWebSocket.cs#L732-L736

**Comment by SimonChris** [comment] 2018-05-21 06:35
Versions of Server-Side NuGet Packages:
Microsoft.AspNetCore 2.1.0-rc1-final
Microsoft.AspNetCore.SignalR 1.0.0-rc1-final
As mentioned, this also happens if I upgrade SignalR to the RTM version. I haven't tried upgrading ASP.NET Core itself yet. I am targeting .NET 4.6.

Versions of Client-Side NuGet/NPM Packages:
@aspnet/signalr@1.0.0-rc1-update1

Are you using the C# client or the JavaScript client:
The JavaScript Client

The Server you are using (Kestrel/HttpSysServer/IIS/IIS Express/Azure Web App/etc.):
IIS Express when testing from Visual Studio. IIS on the deployment machine. The error occurs in both places.

The Operating System on the Server (Windows/Linux/macOS):
Windows Server 2016. Windows 10 when testing locally. The error occurs both places.

The Operating System on the Client (Windows/Linux/macOS):
Windows 10

The Browser on the client, if using the JavaScript client (IE/Chrome/Edge/Firefox/etc.):
I have reproduced the error with Chrome and Edge.

**Comment by SimonChris** [comment] 2018-05-21 06:37
Copy-pasting half a dozen of the æ's is enough to trigger the error for me. It happens sooner the more æ's i use.

**Comment by SimonChris** [comment] 2018-05-21 08:12
I've tried running without IIS and the error still happens. I've also upgraded all of the RC1 packages to the RTM equivalents, with no change.

**Comment by SimonChris** [comment] 2018-05-21 17:46
Can it be related to the fact that I am using ASP.Net Core, but targeting .NET 4.6? I noticed that your websocket link goes to the .NET Core Foundational classes, but I am not using .NET Core.

**Comment by BrennanConroy** [comment] 2018-05-21 19:44
We've been able to repro it now, will start investigating

**Comment by BrennanConroy** [comment] 2018-05-21 22:33
We found that it is an issue in the `ManagedWebSocket` implementation. Filed https://github.com/dotnet/corefx/issues/29834

Nice catch @SimonChris! Unfortunately I don't really know of a workaround currently... @anurse @davidfowl any ideas?

**Comment by anurse** [comment] 2018-05-22 00:41
Breaking your message into smaller chunks might help avoid this, but that wouldn't guarantee it won't happen. It's a tricky one unfortunately.

**Comment by davidfowl** [comment] 2018-05-22 05:47
@SimonChris one workaround might be to use message pack instead of JSON. That'll avoid the UTF8 check altogether.

**Comment by davidfowl** [comment] 2018-05-22 07:31
Ah, cool, do that for now then. @BrennanConroy has the fix here https://github.com/dotnet/corefx/pull/29840

**Comment by BrennanConroy** [comment] 2018-05-23 16:57
Closing, as we have a tracking issue for the patch here: https://github.com/aspnet/SignalR/issues/2349

**Closed by BrennanConroy** 2018-05-23 16:57 UTC
Labels: 2.1.1-patch-candidate, investigate
