### ISSUE TITLE
SendAsync fails quietly when message length exceeds maxJsonLength 102400

### ISSUE THREAD

**Issue by guylando** [aspnet/SignalR#2201] opened 2018-05-04 16:15 UTC
The situation is that the code works well in my dev machine. But on server although I can see that server invokes SendAsync on the connection id the client is connected to (I watch the client in chrome devtools), the client does NOT receive the message. Also tried to send by UserId and doesnt work as well.
I already tried verify that user id and connection id are correct.

What can cause SendAsync to not send anything to the target?

Thanks!

**Comment by anurse** [comment] 2018-05-04 16:16
Do you have a single server or multiple servers behind a load balancer? Can you provide more details on your server environment (Azure? What OS? etc.)

**Comment by guylando** [comment] 2018-05-04 16:32
It seems to happen for connections where the query string is very long, does this make sense?

**Comment by davidfowl** [comment] 2018-05-04 16:34
What transport is being used?

**Comment by guylando** [comment] 2018-05-04 18:05
After further debugging. 
Even calling Clients.All.SendAsync does NOT send the message to the client.
Websocket transport.
Also I tried to send message from another place at this situation and nothing worked.
Seems the connection is alive but server cant send anything to the client after this:

![image](https://user-images.githubusercontent.com/14879163/39643738-67e9f618-4fde-11e8-894c-8b8fc6f1f932.png)

The long message from client to server which after it received {} message and then only keepalive is:

{"arguments":["CompetitionsUsers",{"compusersids":"111806,426318,806318,711806,575964,834075,026318,057257,664075,125964,375964,391806,234075,591806,945964,645964,457257,787257,964075,206318","caller":1}],"target":"register","type":1}

seems this message made the server not able to send any other message.
the code handling the register message on server basically just added the connection to a group.

**Comment by guylando** [comment] 2018-05-04 18:07
Is there maybe something wrong with the server code which handled this request:
`
[HubMethodName("register")]
        public async Task RegisterToHub(string hub, Dictionary<string, string> queryParams)
        {
await this.Groups.AddAsync(this.Context.ConnectionId, hub);
        }
`

**Comment by guylando** [comment] 2018-05-04 18:08
NOTE: If calling this with less values then it WORKS AS EXPECTED:
if change
111806,426318,806318,711806,575964,834075,026318,057257,664075,125964,375964,391806,234075,591806,945964,645964,457257,787257,964075,206318
to
111806,426318

**Comment by guylando** [comment] 2018-05-04 18:10
Also another conclusion: it DOES NOT WORK on dev machine either when using the long parameter. Tried the parameter above which contains 20 numbers and it reproduced the problem on my dev machine (httpsys) too.

**Comment by guylando** [comment] 2018-05-04 18:33
I am checking where the limit is.

This SOMETIMES works:
{"arguments":["CompetitionsUsers",{"compusersids":"711806,806318,426318,834075,964075,787257,575964","caller":1}],"target":"register","type":1}

This NEVER works:
{"arguments":["CompetitionsUsers",{"compusersids":"711806,806318,426318,834075,964075,787257,575964,234075","caller":1}],"target":"register","type":1}

This ALWAYS works:
{"arguments":["CompetitionsUsers",{"compusersids":"711806,806318,426318,834075,787257,964075","caller":1}],"target":"register","type":1}

**Comment by guylando** [comment] 2018-05-04 19:02
ok, I found out where the problem happens: the length of the numbers sent to the server determined the size of the messages the server sent the client afterwards.
so basically the answer to the first question of when can this happen that the server SendAsync does not work is: when the server message is too long.
I am trying to find the limitation in the documentation now...

**Comment by davidfowl** [comment] 2018-05-04 21:05
There's is no inherent limit. I'd suggest turning on more verbose logging on the server to get more details on the server side.

**Comment by guylando** [comment] 2018-05-05 00:06
I had Trace level logging turned on and it quietly failed for 103000+ size messages, while having no troubles with under 102000 size messages.
At this moment I optimized the data sent to lower its size and it seems to solve the problem.

**Comment by guylando** [comment] 2018-05-05 11:46
Exception thrown: 'System.ArgumentException' in mscorlib.dll
Exception thrown: 'System.ArgumentException' in Newtonsoft.Json.dll
Exception thrown: 'System.ArgumentException' in Newtonsoft.Json.dll
Exception thrown: 'System.ArgumentException' in Newtonsoft.Json.dll
Exception thrown: 'System.ArgumentException' in Newtonsoft.Json.dll
Exception thrown: 'System.ArgumentException' in Newtonsoft.Json.dll
Exception thrown: 'System.ArgumentException' in Newtonsoft.Json.dll
Exception thrown: 'System.ArgumentException' in Newtonsoft.Json.dll
Exception thrown: 'System.ArgumentException' in Newtonsoft.Json.dll
Exception thrown: 'System.ArgumentException' in Newtonsoft.Json.dll
Exception thrown: 'System.ArgumentException' in Newtonsoft.Json.dll
Exception thrown: 'System.IndexOutOfRangeException' in System.Memory.dll
Exception thrown: 'System.IndexOutOfRangeException' in Newtonsoft.Json.dll
Exception thrown: 'System.IndexOutOfRangeException' in Newtonsoft.Json.dll
Exception thrown: 'System.IndexOutOfRangeException' in Newtonsoft.Json.dll

**Comment by guylando** [comment] 2018-05-05 12:02
I found the documentation for the limit: https://msdn.microsoft.com/en-us/library/system.web.configuration.scriptingjsonserializationsection.maxjsonlength.aspx
The default is 102400 characters as I saw in my tests.

Can this be configured in net core? Can exception be thrown if message exceed this limit?

**Comment by guylando** [comment] 2018-05-05 16:50
Well since it happens exactly at 102400 which is the limit as specified in links, seems related.
As I already said, using Trace level logs thats all what is visible in the logs.

**Comment by BrennanConroy** [comment] 2018-05-05 17:11
Since you're using VS for your logging you need to configure the debug logger via `AddDebug` otherwise you wont be getting logs in the output window

**Comment by davidfowl** [comment] 2018-05-05 17:54
That’s added by default if you’re using the >== 2.0 template. We just need to see the actual error, try running without IIS express. That might make it more obvious.

**Comment by guylando** [comment] 2018-05-05 18:43
I use loggerFactory.AddDebug(LogLevel.Trace) in my startup and I do see all trace logs of the mvc requests handling in my output window. What I ment is that what I written above is the only thing that comes up for this issue.

**Comment by guylando** [comment] 2018-05-05 20:16
`
Exception thrown: 'System.ArgumentException' in mscorlib.dll
Exception thrown: 'System.ArgumentException' in Newtonsoft.Json.dll
Exception thrown: 'System.ArgumentException' in Newtonsoft.Json.dll
Exception thrown: 'System.ArgumentException' in Newtonsoft.Json.dll
Exception thrown: 'System.ArgumentException' in Newtonsoft.Json.dll
Exception thrown: 'System.ArgumentException' in Newtonsoft.Json.dll
Exception thrown: 'System.ArgumentException' in Newtonsoft.Json.dll
Exception thrown: 'System.ArgumentException' in Newtonsoft.Json.dll
Exception thrown: 'System.ArgumentException' in Newtonsoft.Json.dll
Exception thrown: 'System.ArgumentException' in Newtonsoft.Json.dll
Exception thrown: 'System.ArgumentException' in Newtonsoft.Json.dll
Microsoft.AspNetCore.SignalR.HubConnectionContext: Debug: Failed writing message.

System.ArgumentException: The output byte buffer is too small to contain the encoded data, encoding 'Unicode (UTF-8)' fallback 'System.Text.EncoderReplacementFallback'.
Parameter name: bytes
   at System.Text.Encoding.ThrowBytesOverflow()
   at System.Text.Encoding.ThrowBytesOverflow(EncoderNLS encoder, Boolean nothingEncoded)
   at System.Text.UTF8Encoding.GetBytes(Char* chars, Int32 charCount, Byte* bytes, Int32 byteCount, EncoderNLS baseEncoder)
   at System.Text.EncoderNLS.Convert(Char* chars, Int32 charCount, Byte* bytes, Int32 byteCount, Boolean flush, Int32& charsUsed, Int32& bytesUsed, Boolean& completed)
   at Microsoft.AspNetCore.SignalR.Internal.Protocol.Utf8BufferTextWriter.WriteInternal(ReadOnlySpan`1 buffer)
   at Microsoft.AspNetCore.SignalR.Internal.Protocol.Utf8BufferTextWriter.Write(Char[] buffer, Int32 index, Int32 count)
   at Newtonsoft.Json.JsonTextWriter.WriteValue(DateTime value)
   at Newtonsoft.Json.JsonWriter.WriteValue(JsonWriter writer, PrimitiveTypeCode typeCode, Object value)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Microsoft.AspNetCore.SignalR.Internal.Protocol.JsonHubProtocol.WriteArguments(Object[] arguments, JsonTextWriter writer)
   at Microsoft.AspNetCore.SignalR.Internal.Protocol.JsonHubProtocol.WriteMessageCore(HubMessage message, IBufferWriter`1 stream)
   at Microsoft.AspNetCore.SignalR.Internal.Protocol.JsonHubProtocol.WriteMessage(HubMessage message, IBufferWriter`1 output)
   at Microsoft.AspNetCore.SignalR.Internal.Protocol.HubProtocolExtensions.WriteToArray(IHubProtocol hubProtocol, HubMessage message)
   at Microsoft.AspNetCore.SignalR.Internal.Protocol.HubMessage.WriteMessage(IHubProtocol protocol)
   at Microsoft.AspNetCore.SignalR.HubConnectionContext.WriteCore(HubMessage message)
`

**Comment by davidfowl** [comment] 2018-05-05 21:59
Ah good. This issue was found and fixed 2 days ago https://github.com/aspnet/SignalR/issues/2187. Unfortunately it’s in the preview and upcoming RC, you might be able to work around it by using message pack instead of JSON for now.

**Comment by guylando** [comment] 2018-05-05 22:03
@davidfowl do you know the explanation of why it happened specifically for messages over 102400 characters length? I didnt see it mentioned in that thread

**Comment by guylando** [comment] 2018-05-05 22:07
also, can you please provide more info on using message pack instead of JSON?
1)how to specify it in code
2)does it have any disadvantages? or only advantages of making traffic shorter? is it best practice to always use it?

**Comment by davidfowl** [comment] 2018-05-05 23:13
The issue is that the underlying buffer we’re using is too small to encode specific characters (likely non ascii). It has nothing to do with the specific size of the data your sending, it just so happens that the combination of the buffer size we use and the message you sent, that number of bytes observed the problem.

**Comment by davidfowl** [comment] 2018-05-05 23:16
you need to install another library on the server and client. The APIs are different in the preview and rc1 but I believe we have a sample somewhere (I’ve also seen it in blog posts if you search).

There are some quirks with the message pack library around camel casing and other things around support for de/serializing certain types

**Comment by davidfowl** [comment] 2018-05-06 04:59
Closing this as dupe of https://github.com/aspnet/SignalR/issues/2187

**Closed by davidfowl** 2018-05-06 04:59 UTC
