### ISSUE TITLE
SignalR npm package should point to ES5 script version

### ISSUE THREAD

**Issue by whut** [aspnet/SignalR#983] opened 2017-10-04 10:54 UTC
## Issue

SignalR npm package (1.0.0-alpha1-final) point to the ES6 version in package.json [in the main element](https://github.com/aspnet/SignalR/blob/dev/client-ts/package.json#L5):

```json
{
  "name": "@aspnet/signalr-client",
  "version": "1.0.0",
  "description": "ASP.NET Core SignalR",
  "main": "dist/src/index.js",
  ...
```

This leads to plenty of issues in environments targeting browsers, so main target of SignalR, like already reported: #923, #867, #777, #729, #416, #177. 

## Solution

SignalR "main" element should point to ES5 version. Then there will be no issues with IE11 compatiblity and uglify.js and no need to transcompile SignalR by SignalR users.

## Problem Details

SignalR does not work in environments like angular-cli or create-react-app because they use uglifyjs which does not support ES6. This is OK that uglifyjs does not support ES6, because for browser scenarios ES5 must be used to maintain compatibility with IE11 (thanks Microsoft that you stop development of IE11, leading to the same situation like with IE6 before🙂). Instead, as community best practice, all npm packages targeting browser environment ship an ES5 version and point to it in the "main" element. At some point in probably not-so-distant future, the "baseline" JavaScript version used in browsers will be ES6 and we will be using uglify-es, but until then ES5 should be the default in npm packages.

The general issue is for example described here: https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify. From it I learned the recommendation of using ES5 as default in package.json. The create-react-app approach (and I believe angular-cli have the same) is to transcompile application source code to ES5, but assume that all dependencies are already in ES5. This is done to ensure fast startup times during development and avoid any issues that could arise from using different transcompiler than the upstream.

## Workaround

Instead of importing SignalR like:

```javascript
import { HubConnection } from '@aspnet/signalr-client'
```

Import the ES5 version of SignalR:

```javascript
import { HubConnection } from '@aspnet/signalr-client/dist/browser/signalr-clientES5-1.0.0-alpha1-final.js'
```

**Comment by whut** [comment] 2017-10-05 06:12
Added workaround above.

**Comment by moozzyk** [comment] 2017-10-06 17:21
Looks like Uglify is getting updated to support ES6 and there is a beta of angular-cli that [can handle](https://github.com/aspnet/SignalR/issues/729#issuecomment-333492378) ES6 signalr client.

**Comment by budcribar** [comment] 2017-10-07 00:50
Won't this(SignalR "main" element should point to ES5 version) also solve my problem of using the embedded web browser control which does not understand ES6?

**Comment by moozzyk** [comment] 2017-10-09 18:14
The trade-off is size vs. postprocessing. I did build an ES5 version to see what the difference is and AFAIR the ES5 version was ~1/3 bigger. If the most popular tools (angular-cli, react-native, UglifyJS etc.) start supporting ES6 we probably could leave the ES6 version as it is. If there are a lot of scenarios where this is still a problem we should reconsider or ship ES5 and ES6 version (we already do this for a browserified version of the client).

**Comment by budcribar** [comment] 2017-10-09 21:58
For those using angular-cli (me) size is not an issue since it will be tree-shaken and minimized

**Comment by fruitraccoon** [comment] 2017-11-01 08:10
I ran into this issue using `create-react-app` with TypeScript, and TypeScript adds an extra dimension to using the workaround reported above because the type definition files are not in the `dist/browser` directory. To work around this, I used the following:

    import { HubConnection as HubConnectionType } from '@aspnet/signalr-client/dist/src/HubConnection.d';
    var { HubConnection } = require('@aspnet/signalr-client/dist/browser/signalr-clientES5-1.0.0-alpha2-final');

I could then create my connection thusly:

    const connection = new HubConnection('/chat') as HubConnectionType;

Ugly, but works.

**Comment by SergBozhko** [comment] 2017-11-02 15:22
Angular-cli has updated 1.5.0. It's solved this problem. 

Current version of @aspnet/signalr-client: '1.0.0-alpha2-final' in my project.
Now i'm using  import { HubConnection } from '@aspnet/signalr-client' without errors while production building.

Angular-cli releases link: https://github.com/angular/angular-cli/releases

**Comment by dimamarksman** [comment] 2017-12-13 08:12
@SergBozhko `@aspnet/signalr-client` + `import { HubConnection } from '@aspnet/signalr-client'` does not work in IE11 for me.
I'm using `angular-cli 1.6.0`

**Comment by blurhkh** [comment] 2017-12-25 13:06
@dimamarksman
Because ES6 syntax in the package will not be converted even if the target of tsconfig.json is es5.
You can rename the  js file( which includes source of signalr-client) in then dist folder to xxx.ts,then use 'tsc xxx.ts' to convert it to es5.
It works for me.

**Comment by anurse** [comment] 2018-01-02 17:26
We'll be reviewing the NPM package layout soon (though it may not land for preview1) and this is something I'll look at trying to improve. It's been a little while since we wrote a major new JavaScript library so we're catching up on the new patterns a bit :)

**Comment by kgrvr** [comment] 2018-01-08 05:07
I'm getting a weird issue when using `signalr-clientES5-1.0.0-alpha1-final.js`
The messages I send gets delivered after I send another message. I don't know why it's happening but it's not happening when I'm using `signalr-client-1.0.0-alpha2-final.min.js`. My same code is working exactly fine.
And using `signalr-client-1.0.0-alpha2-final.min.js` file, my app is not opening in IE

**Comment by anurse** [comment] 2018-01-08 18:56
I'd expect `signalr-client-1.0.0-alpha2-final.min.js` to fail in IE, since it requires ES2015 features (`class`, etc.). The `ES5` version is the one intended for browsers. As for your bug, is this the same issue you reported in #1259 ?

**Comment by kgrvr** [comment] 2018-01-11 15:41
Actually no. And I'm not able to reproduce that myself too. I don't know why it was happening. That behavior is very much irregular. 
And as far as this issue is concerned, it's happening only when I use ES5 version of signalr client. Normal version is working exactly fine.

**Comment by anurse** [comment] 2018-01-11 17:48
Could you file a new issue for the bug you're seeing and provide code that illustrates what you're doing and where the issue is occurring?

**Comment by sasquad92** [comment] 2018-01-15 11:03
I had same issue with react and changing
` import { HubConnection } from '@aspnet/signalr-client';`
to
`import { HubConnection } from '@aspnet/signalr-client/dist/browser/signalr-clientES5-1.0.0-alpha2-final.min.js';`
works for me.

**Comment by sorenhoyer** [comment] 2018-01-29 10:26
Same problem with Create React App. The workaround is not a good solution when using dev versions, having to change the import every single time the version changes, but thanks for the workaround anyways. Hopefully this will be fixed soon. :)

**Comment by davidfowl** [comment] 2018-01-29 11:23
@anurse we've made the es5 version the only version right? If so, can you point people to the dev versions to try out.

**Comment by anurse** [comment] 2018-01-29 17:02
That's correct, see the [Packages](https://github.com/aspnet/SignalR#packages) and [Deploying](https://github.com/aspnet/SignalR#deploying) sections of the readme for this repo.

Also, please note that the package has been **renamed** in the recent nightly builds. It is now called `@aspnet/signalr`. The UMD bundle for browsers, referred to in the README, is now ES5-compatible and should work in IE.

Going to close this now as that should resolve this issue

**Closed by anurse** 2018-01-29 17:02 UTC

**Comment by guylando** [comment] 2018-05-06 13:07
@anurse 
I solved similar error like recommended by using
import * as signalR from '@aspnet/signalr/dist/browser/signalr.min';
HOWEVER
when using:
import * as signalRMsgPack from '@aspnet/signalr-protocol-msgpack/dist/browser/signalr-protocol-msgpack.min';
it tried to import a non-browser version of signalr and again I got these errors from webpack:
 Unexpected token: name (NullLogger) [./node_modules/@aspnet/signalr/dist/esm/Loggers.js:4,0]

how can I import signalRMsgPack  correctly?

**Comment by guylando** [comment] 2018-05-06 13:26
UPDATE: Fixed(!) by modifying in signalr-protocol-msgpack.min.js in the first lines
from:
require("@aspnet/signalr")
to
require("@aspnet/signalr/dist/browser/signalr.min")

**Comment by anurse** [comment] 2018-05-07 16:02
@guylando it's generally a bad idea to import a specific script out of the package, because we **do not guarantee** that the package layout will be consistent from version to version. Can you confirm you are using the latest version of the server (currently `1.0.0-rc1-final`) and JavaScript client (currently: `1.0.0-rc1-update1`) and clarify exactly what error you're seeing, so we can find the correct solution?

**Comment by davidfowl** [comment] 2018-05-07 17:35
@guylando Yes we did.

**Comment by anurse** [comment] 2018-05-07 18:19
If RC1 works for you, I'd suggest sticking with that, since the RTM builds are unofficial builds (until RTM is released).
