### ISSUE TITLE
SignalR .net core 2.2 does not support Windows Desktop Applications

### ISSUE THREAD

**Issue by akira32** [aspnet/SignalR#3259] opened 2018-11-05 09:18 UTC
I want to integrate SignalR .ent core 2.2 to windows form. But I found an article as below:
[.NET Core 3 and Support for Windows Desktop Applications](https://blogs.msdn.microsoft.com/dotnet/2018/05/07/net-core-3-and-support-for-windows-desktop-applications/)

Can I use .NET core library and use Windows form to assign it as a reference?
Does somebody have any idea about using SignalR .net core on Windows Form?

**Comment by akira32** [comment] 2018-11-06 06:55
Sorry! My OS and Visual Studio is Chinese Traditional. So I translate the error messages.
I create a Windows Form with .NET Framework 4.7.1 and copy the Code of SignalRSample to Windows Form Projects. The Windows Form Project add some missing by Nuget. Some reference does not use 2.2 version. For Example: The Microsoft.AspNetCore.SignalR is use 1.0.4.0.

Can I use Windows Form with .NET Framework 4.7.1 as a SignalR Server(version 2.2 or other version)?

I meet some error messages as below:

Level | Code | Description | Project | File | Line | Status
-- | -- | -- | -- | -- | -- | --
Error | CS1061 | 'IObservable   <int>' does not contain the definition of 'AsChannelReader', nor can it   find the first argument of the extension method 'AsChannelReader' that   accepts the type 'IObservable <int>' (Is it missing the use of a   directive or component reference?) | WinFormsSignalRServer | WinFormsSignalRServer\Hubs\Streaming.cs | 20 | used
Error | CS1061 | IServiceCollection' does not contain the definition   of 'AddCors', nor can it find the extension method 'AddCors' Accepts the   first argument of type 'IServiceCollection' (Is it missing the using   directive or component reference?) | WinFormsSignalRServer | WinFormsSignalRServer\Startup.cs | 34 | used
Error | CS1061 | IApplicationBuilder' does not contain the definition   of 'UseFileServer' and can't find the extension method 'UseFileServer'   Accepts the first argument of type 'IApplicationBuilder' (Is it missing the   using directive or component reference?) | WinFormsSignalRServer | WinFormsSignalRServer\Startup.cs | 49 | used
Error | CS1061 | IApplicationBuilder' does not contain the definition   of 'UseCors', nor can the extension method 'UseCors' accept the first   argument of type 'IApplicationBuilder' (do you miss the using directive or   component reference?) | WinFormsSignalRServer | HIS5\WinFormsSignalRServer\Startup.cs | 56 | used

**Comment by anurse** [comment] 2018-11-06 16:43
> Can I use Windows Form with .NET Framework 4.7.1 as a SignalR Server(version 2.2 or other version)?

You can, but you need to manually install the individual packages required for the server components. In .NET Core, these packages are automatically available for you, but in .NET Framework you have to add each individual component. For example:

* For `UseCors` and `AddCors` you need [`Microsoft.AspNetCore.Cors`](https://www.nuget.org/packages/Microsoft.AspNetCore.Cors)
* For `UseFileServer` you need [`Microsoft.AspNetCore.StaticFiles`](https://www.nuget.org/packages/Microsoft.AspNetCore.StaticFiles)
* [`AsChannelReader` is defined in the sample itself](https://github.com/aspnet/SignalR/blob/2d4fb0af6fd2ef2e3a059a2a15a56484d8800d35/samples/SignalRSamples/ObservableExtensions.cs) so you need to copy it from there.

Please note that running an ASP.NET Core SignalR **Server** from a Windows Forms application is **not a supported scenario**.

**Comment by akira32** [comment] 2018-11-07 01:51
@anurse , Thank your answer.

**Comment by akira32** [comment] 2018-11-07 02:40
The Windows Form for SignalR Server is created successfully. And the connection with ClientSample is fine.
But there is another problem when I click the Start Button that will block system IO.
Does somebody know how to solve this problem?

```
		private void buttonStart_Click(object sender, EventArgs e)
		{
			var config = new ConfigurationBuilder()
			//.AddCommandLine(args)
			.Build();

			var host = new WebHostBuilder()
				.UseConfiguration(config)
				.UseSetting(WebHostDefaults.PreventHostingStartupKey, "true")
				//.ConfigureLogging(factory =>
				//{
				//	factory.AddConsole();
				//})
				.UseKestrel(options =>
				{
					// Default port
					options.ListenLocalhost(5000);

					options.ListenAnyIP(5000);

					// Hub bound to TCP end point
					options.Listen(IPAddress.Any, 9001, builder =>
					{
						builder.UseHub<Chat>();
					});
				})
				.UseContentRoot(Directory.GetCurrentDirectory())
				.UseIISIntegration()
				.UseStartup<Startup>()
				.Build();

			host.Run();
		}
```

**Comment by anurse** [comment] 2018-11-07 17:54
`host.Run` is a blocking call. You need to use `host.StartAsync`. You'll also need to keep track of the `host` object so you can call `host.StopAsync` when you want to stop the app (which you should always do before your app exits).

**Comment by BrennanConroy** [comment] 2018-11-10 06:56
Closing as your comment before editing was that the issue is resolved. And https://github.com/aspnet/SignalR/issues/3287 was created for the question after your edit.

**Closed by BrennanConroy** 2018-11-10 06:56 UTC
