### ISSUE TITLE
Get SignalR into the Metapackage

### ISSUE THREAD

**Issue by anurse** [aspnet/SignalR#1267] opened 2018-01-03 19:48 UTC
We need SignalR to be in the Microsoft.AspNetCore.All metapackage.

**Comment by muratg** [comment] 2018-01-04 19:44
cc @JunTaoLuo @natemcmaster FYI

**Comment by anurse** [comment] 2018-01-04 22:04
A prereq for this is splitting MsgPack into a separate assembly. Filing a bug for that. I think I can get that done this week.

**Comment by natemcmaster** [comment] 2018-01-04 22:13
Besides MsgPack and NodeJS, are there any other 3rd party tools or dependencies? i.e. newtonsoft.json? any testing tools?

**Comment by anurse** [comment] 2018-01-04 22:46
In the .NET side, Newtonsoft.Json is the only other 3rd-party dependency. For the NPM package there are some additional dependencies, but I don't think that's relevant to our source build

**Comment by natemcmaster** [comment] 2018-01-04 22:50
Ok. This should be fine.

**Comment by davidfowl** [comment] 2018-01-10 03:25
Dupe of https://github.com/aspnet/MetaPackages/issues/235

**Closed** 2018-01-10 18:01 UTC
Labels: task
