### ISSUE TITLE
Support for server hubs receiving results from clients

### ISSUE THREAD

**Issue by anurse** [aspnet/SignalR#335] opened 2017-03-23 16:23 UTC
We don't have any support yet for servers receiving results when calling client methods. This issue is to track adding that functionality. When we do implement this, we should consider permitting Streaming from client to server as well.

**Comment by anurse** [comment] 2017-03-23 16:23
@muratg @davidfowl I believe this was post-preview, yes?

**Comment by davidfowl** [comment] 2017-03-23 22:04
Yes

**Comment by chemitaxis** [comment] 2017-03-24 19:54
Hi! Is SignalR Core ready for production apps? Thanks

**Comment by moozzyk** [comment] 2017-03-24 22:53
@chemitaxis - it has not even previewed yet...

**Comment by davidfowl** [comment] 2018-09-29 09:09
Dupe of https://github.com/aspnet/SignalR/issues/903

**Closed by davidfowl** 2018-09-29 09:09 UTC
Labels: type: Enhancement
