### ISSUE TITLE
Error parsing Unicode characters

### ISSUE THREAD

**Issue by kant2002** [aspnet/SignalR#723] opened 2017-08-15 18:37 UTC
Looks like SignalR by default does not able send emoji symbols correctly.

I often has error `Uncaught Error: Message is incomplete` at following lines:

```
// Required space is: (";") + length (payload len)
            if (!hasSpace(input, offset, 1 + length)) {
                throw new Error("Message is incomplete");
            }
```

Message looks fine for me. Seems to be this is related to any non-ASCII symbol. Initially I discover error with Emojy, but looks like enough just send Cyricllic character like `б`

**Comment by davidfowl** [comment] 2017-08-15 18:39
Dupe of https://github.com/aspnet/SignalR/issues/550

**Comment by kant2002** [comment] 2017-08-15 18:39
👍 Sorry, I found it. Want to close myself

**Closed by davidfowl** 2017-08-15 18:39 UTC
