### ISSUE TITLE
The remote party closed the WebSocket connection without completing the close handshake

### ISSUE THREAD

**Issue by los93sol** [aspnet/SignalR#691] opened 2017-08-04 14:37 UTC
I cannot reliably reproduce this as it seems to only happen when a debugger is not attached, but if the remote party closes the websocket without completing the handshake it causes Kestrel to crash.  Looking at the stacktrace I am not sure if the issue is with SignalR or elsewhere.

Here is the code from the hub where the client disconnects....
        
        public override Task OnDisconnectedAsync(Exception exception)
        {
            if (exception == null)
            {
                Console.WriteLine("Client Disconnected from Hub: " + Context.ConnectionId);
            }
            else
            {
                Console.WriteLine("A client did not disconnect cleanly");
            }

            return base.OnDisconnectedAsync(exception);
        }

Client Disconnected from Hub: 2debeeec-2c3f-4085-b18c-aab5cf4d4f47
fail: Microsoft.AspNetCore.Sockets.ConnectionManager[2]
      08/03/2017 15:06:43: ConnectionId 2debeeec-2c3f-4085-b18c-aab5cf4d4f47: Failed disposing connection.
System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake. ---> Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions.Internal.ConnectionResetException: Error -4077 ECONNRESET connection reset by peer ---> Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvException: Error -4077 ECONNRESET connection reset by peer
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Internal.System.IO.Pipelines.PipeCompletion.ThrowFailed()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.System.IO.Pipelines.Pipe.GetResult(ReadResult& result)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.System.IO.Pipelines.Pipe.Microsoft.AspNetCore.Server.Kestrel.Internal.System.IO.Pipelines.IReadableBufferAwaiter.GetResult()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.MessageBody.<ReadAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.FrameRequestStream.<ReadAsyncInternal>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.WebSockets.ManagedWebSocket.<EnsureBufferContainsAsync>d__70.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.WebSockets.ManagedWebSocket.<ReceiveAsyncPrivate>d__61.MoveNext()
   at System.Net.WebSockets.ManagedWebSocket.<ReceiveAsyncPrivate>d__61.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Sockets.Internal.Transports.WebSocketsTransport.<StartReceiving>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Sockets.Internal.Transports.WebSocketsTransport.<ProcessSocketAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Sockets.Internal.Transports.WebSocketsTransport.<ProcessRequestAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Sockets.DefaultConnectionContext.<WaitOnTasks>d__56.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Sockets.DefaultConnectionContext.<DisposeAsync>d__55.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Sockets.ConnectionManager.<DisposeAndRemoveAsync>d__14.MoveNext()

**Comment by los93sol** [comment] 2017-08-04 14:42
A few other details that may be helpful...

-Occurs on latest bits running on a Pi 3 on Windows IOT Core
-The client is a the signalr-client.js client, also latest

**Comment by moozzyk** [comment] 2017-08-04 16:50
I assume that when you say "crashing" it means that OnDisconnected is called with a non-null exception but the server continues to run and handle new connections, and the issue is that OnDisconnected is called long after the client disconnected. 
If this is the case [this](https://github.com/aspnet/SignalR/issues/282) should solve it.

**Comment by moozzyk** [comment] 2017-08-04 16:54
Possibly related: https://github.com/aspnet/AspNetCoreModule/issues/77

**Comment by los93sol** [comment] 2017-08-04 22:13
@moozyk It actually crashes Kestrel completely and stops responding to all requests when it happens

**Comment by los93sol** [comment] 2017-08-11 23:45
Any updates on this?

**Comment by moozzyk** [comment] 2017-08-15 17:09
A similar issue was reported here: https://github.com/aspnet/SignalR/issues/720.

**Comment by moozzyk** [comment] 2017-08-18 17:58
@los93sol - the related issue was fixed. Can you try the latest bits and see if it still reproduces? The fix will be in packages newer than 1.0.0-alpha1-26703.

**Comment by BrennanConroy** [comment] 2017-08-24 20:32
Closing, this should be fixed, if it happens again please reopen.

**Closed by BrennanConroy** 2017-08-24 20:32 UTC

**Comment by Shhzdmrz** [comment] 2018-05-13 06:10
Still facing this exception for preview2 in React Native client. When the app killed without closing the connection properly.

```exception
The remote party closed the WebSocket connection without completing the close handshake. ---> Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Unexpected end of request content.
   
"at Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException.Throw(RequestRejectionReason reason)\r\n   
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1MessageBody.PumpAsync()\r\n   
at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()\r\n   
at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)\r\n   
at System.IO.Pipelines.Pipe.GetReadAsyncResult()\r\n   
at System.IO.Pipelines.Pipe.DefaultPipeReader.GetResult(Int16 token)\r\n   
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.MessageBody.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)\r\n   
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)\r\n   
at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, Boolean throwOnPrematureClosure)\r\n   
at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)"

**Comment by davidfowl** [comment] 2018-05-13 06:12
Upgrade to rc1

**Comment by davidfowl** [comment] 2018-05-13 06:13
Actually that specific exception will be fixed by the time the RTM ships. It was fixed here https://github.com/aspnet/KestrelHttpServer/commit/5c17bff55d018946572245c435a0361bde06ffd1

**Comment by Shhzdmrz** [comment] 2018-05-13 06:14
Tried and ended with [this issue](https://github.com/aspnet/SignalR/issues/2254)
