### ISSUE TITLE
Exception when connecting to server from Xamarin iOS and Android - Xamarin forms

### ISSUE THREAD

**Issue by kevinvella** [aspnet/SignalR#2457] opened 2018-06-08 13:01 UTC
Server Side version
- Microsoft.AspNetCore.All (2.0.0)
- Microsoft.AspNetCore.SignalR (1.0.0)
- Microsoft.AspNetCore.SignalR.Core (1.0.0)

Client Side version
- Microsoft.AspNetCore.SignalR.Client (1.0.0)
- Microsoft.AspNetCore.SignalR.Client.Core (1.0.0)

Server
- LocalHost - Kestrel
- Cloud - Azure Web App

OS on Server - Windows (Azure web app)
OS on LocalHost - macOS

OS on client
Xamarin forms (Android and iOS)

Client Side Code:
```
        try
            {
                _hub = new HubConnectionBuilder()
                    .WithUrl("http://127.0.0.1:47964/messanger")
                .Build();

                _hub.On<string>("Message",
                (value) => {
                    Message?.Invoke(this, new MessageEventArgs(value, string.Empty));
                });

                await _hub.StartAsync();
            }
            catch (Exception ex)
            {
                Debug.WriteLine($"SignalR Error...{ex.Message}");
            }
```

Exception
```
{System.TypeLoadException: Could not resolve the signature of a virtual method
  at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) [0x0001b] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.12.0.4/src/Xamarin.iOS/mcs/class/corlib/System.Reflection/MonoMethod.cs:671 
  at System.Reflection.MonoCMethod.DoInvoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0007a] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.12.0.4/src/Xamarin.iOS/mcs/class/corlib/System.Reflection/MonoMethod.cs:652 
  at System.Reflection.MonoCMethod.Invoke (System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.12.0.4/src/Xamarin.iOS/mcs/class/corlib/System.Reflection/MonoMethod.cs:680 
  at System.Reflection.ConstructorInfo.Invoke (System.Object[] parameters) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.12.0.4/src/Xamarin.iOS/mcs/class/corlib/System.Reflection/ConstructorInfo.cs:62 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor (Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite constructorCallSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope scope) [0x00035] in <15b87bbf30da4bf4b95652066811831b>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[TArgument,TResult].VisitCallSite (Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceCallSite callSite, TArgument argument) [0x00056] in <15b87bbf30da4bf4b95652066811831b>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped (Microsoft.Extensions.DependencyInjection.ServiceLookup.ScopedCallSite scopedCallSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope scope) [0x0002d] in <15b87bbf30da4bf4b95652066811831b>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton (Microsoft.Extensions.DependencyInjection.ServiceLookup.SingletonCallSite singletonCallSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope scope) [0x0000d] in <15b87bbf30da4bf4b95652066811831b>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[TArgument,TResult].VisitCallSite (Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceCallSite callSite, TArgument argument) [0x00072] in <15b87bbf30da4bf4b95652066811831b>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor (Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite constructorCallSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope scope) [0x0001b] in <15b87bbf30da4bf4b95652066811831b>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[TArgument,TResult].VisitCallSite (Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceCallSite callSite, TArgument argument) [0x00056] in <15b87bbf30da4bf4b95652066811831b>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped (Microsoft.Extensions.DependencyInjection.ServiceLookup.ScopedCallSite scopedCallSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope scope) [0x0002d] in <15b87bbf30da4bf4b95652066811831b>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton (Microsoft.Extensions.DependencyInjection.ServiceLookup.SingletonCallSite singletonCallSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope scope) [0x0000d] in <15b87bbf30da4bf4b95652066811831b>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[TArgument,TResult].VisitCallSite (Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceCallSite callSite, TArgument argument) 
…
```

Sample project
[https://github.com/kevinvella/SignalRTest](https://github.com/kevinvella/SignalRTest)

Log File on client
[SignalR_Log.txt](https://github.com/aspnet/SignalR/files/2084423/SignalR_Log.txt)

On console it works with the same code

**Comment by anurse** [comment] 2018-06-08 15:57
#1886 is tracking this. Xamarin is not supported by 2.1.0 but it is a high priority to fix it. The teams are working together closely to get this done.

Closing this as a duplicate of the other issue. Feel free to comment further if you have questions!

**Closed by anurse** 2018-06-08 15:57 UTC

**Comment by kevinvella** [comment] 2018-06-08 17:15
@anurse Sorry for the duplicate post. Didn't see that when i was looking for closed issues. Thanks for update

**Comment by anurse** [comment] 2018-06-08 21:57
No problem!
